package no.nav.mulighetsrommet.database

import com.codahale.metrics.health.HealthCheckRegistry
import com.zaxxer.hikari.HikariConfig
import com.zaxxer.hikari.HikariDataSource
import kotliquery.Session
import kotliquery.TransactionalSession
import kotliquery.sessionOf
import java.util.*
import javax.sql.DataSource

open class DatabaseAdapter(val config: DatabaseConfig) : Database {

    private val dataSource: HikariDataSource

    private val session: Session
        get() = sessionOf(dataSource, strict = true)

    init {
        val hikariConfig = HikariConfig().apply {
            jdbcUrl = config.jdbcUrl
            config.schema?.let {
                schema = config.schema
            }
            driverClassName = "org.postgresql.Driver"
            username = config.user
            password = config.password.value
            maximumPoolSize = config.maximumPoolSize
            healthCheckRegistry = HealthCheckRegistry()

            config.googleCloudSqlInstance?.let {
                dataSourceProperties = Properties().apply {
                    setProperty("socketFactory", "com.google.cloud.sql.postgres.SocketFactory")
                    setProperty("cloudSqlInstance", config.googleCloudSqlInstance)
                }
            }

            validate()
        }
        dataSource = HikariDataSource(hikariConfig)
    }

    fun close() {
        if (!dataSource.isClosed) {
            dataSource.close()
        }
    }

    override fun getDatasource(): DataSource {
        return dataSource
    }

    override fun isHealthy(): Boolean {
        return (dataSource.healthCheckRegistry as? HealthCheckRegistry)
            ?.runHealthChecks()
            ?.all { it.value.isHealthy }
            ?: false
    }

    override fun <T> useSession(operation: (Session) -> T): T {
        return session.use { operation(it) }
    }

    // Dette er basically en kopi av session.transaction metoden bare i en suspend variant
    override suspend fun <T> transactionSuspend(operation: suspend (TransactionalSession) -> T): T {
        val sess = session
        try {
            sess.connection.begin()
            sess.transactional = true
            val tx =
                TransactionalSession(sess.connection, sess.returnGeneratedKeys, sess.autoGeneratedKeys, sess.strict)
            val result = operation.invoke(tx)
            sess.connection.commit()
            return result
        } catch (e: Exception) {
            sess.connection.rollback()
            throw e
        } finally {
            sess.transactional = false
            sess.close()
        }
    }
}
