apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: mulighetsrommet-arena-adapter-manager
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/poao/poao-frontend:2025.05.05_06.50-1fe97d204c27
  port: 8080
  ingresses:
    - https://mulighetsrommet-arena-adapter-manager.intern.nav.no
  replicas:
    min: 1
    max: 1
  resources:
    requests:
      cpu: 1m
      memory: 256Mi
    limits:
      memory: 512Mi
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  gcp:
    buckets:
      - name: mulighetsrommet-arena-adapter-manager-prod
        cascadingDelete: false
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: debefa6e-1865-446d-b22b-9579fc735de3 # team-mulighetsrommet
    sidecar:
      enabled: true
      autoLogin: true
  accessPolicy:
    outbound:
      rules:
        - application: mulighetsrommet-arena-adapter
        - application: mulighetsrommet-api
        - application: tiltakshistorikk
        - application: tiltaksokonomi
  env:
    - name: JSON_CONFIG
      value: >
        {
          "gcs": {
            "bucketName": "mulighetsrommet-arena-adapter-manager-prod"
          },
          "auth": {
            "loginProvider": "AZURE_AD"
          },
          "proxies": [
            {
              "fromPath": "/mulighetsrommet-arena-adapter",
              "toUrl": "http://mulighetsrommet-arena-adapter",
              "preserveFromPath": false,
              "toApp": {
                "name": "mulighetsrommet-arena-adapter",
                "namespace": "team-mulighetsrommet",
                "cluster": "prod-gcp"
              }
            },
            {
              "fromPath": "/mulighetsrommet-api",
              "toUrl": "http://mulighetsrommet-api",
              "preserveFromPath": false,
              "toApp": {
                "name": "mulighetsrommet-api",
                "namespace": "team-mulighetsrommet",
                "cluster": "prod-gcp"
              }
            },
            {
              "fromPath": "/tiltakshistorikk",
              "toUrl": "http://tiltakshistorikk",
              "preserveFromPath": false,
              "toApp": {
                "name": "tiltakshistorikk",
                "namespace": "team-mulighetsrommet",
                "cluster": "prod-gcp"
              }
            },
            {
              "fromPath": "/tiltaksokonomi",
              "toUrl": "http://tiltaksokonomi",
              "preserveFromPath": false,
              "toApp": {
                "name": "tiltaksokonomi",
                "namespace": "team-mulighetsrommet",
                "cluster": "prod-gcp"
              }
            }
          ]
        }
