apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: mulighetsrommet-arena-adapter-manager
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
spec:
  image: ghcr.io/navikt/poao-frontend/poao-frontend:2023.04.13_12.56-e509a7e7034a
  port: 8080
  ingresses:
    - https://mulighetsrommet-arena-adapter-manager.intern.nav.no
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 75
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: 676673aa-ec8f-4606-8399-723dce26b361 # team-mulighetsrommet
    sidecar:
      enabled: true
      autoLogin: true
  gcp:
    buckets:
      - name: mulighetsrommet-arena-adapter-manager-prod
        cascadingDelete: false
  accessPolicy:
    outbound:
      rules:
        - application: mulighetsrommet-arena-adapter
  env:
    - name: JSON_CONFIG
      value: >
        {
          "gcs": {
            "bucketName": "mulighetsrommet-arena-adapter-manager-prod"
          },
          "auth": {
            "loginProvider": "AZURE_AD"
          },
          "proxies": [
            {
              "fromPath": "/mulighetsrommet-arena-adapter",
              "toUrl": "http://mulighetsrommet-arena-adapter",
              "preserveFromPath": false,
              "toApp": {
                "name": "mulighetsrommet-arena-adapter",
                "namespace": "team-mulighetsrommet",
                "cluster": "prod-gcp"
              }
            }
          ]
        }
