version: 2
updates:

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily

  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily

  # Test versjonsoppdatering av docker images i nais config
  - package-ecosystem: docker
    directory: "frontend/mr-admin-flate/.nais"
    schedule:
      interval: daily
