version: 2

registries:
  google-artifact-registry:
    type: docker-registry
    url: https://europe-north1-docker.pkg.dev
    username: _json_key_base64
    password: ${{ secrets.GOOGLE_ARTIFACT_REGISTRY_READ_TOKEN }}

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Europe/Oslo
    open-pull-requests-limit: 10

  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Europe/Oslo
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Europe/Oslo
    open-pull-requests-limit: 10
    groups:
      playwright:
        patterns:
          - "playwright"
          - "@playwright/test"
      nav-designsystem:
        patterns:
          - "@navikt/aksel-*"
          - "@navikt/ds-*"
      react:
        patterns:
          - "react"
          - "react-dom"
      patches:
        update-types:
          - "patch"
        exclude-patterns:
          - "react"
          - "react-dom"
          - "@navikt/aksel-*"
          - "@navikt/ds-*"
      minorversions:
        update-types:
          - "minor"
        exclude-patterns:
          - "react"
          - "react-dom"
          - "@navikt/aksel-*"
          - "@navikt/ds-*"

  # Test versjonsoppdatering av docker images i nais config
  - package-ecosystem: docker
    directory: "/frontend/arena-adapter-manager/.nais/"
    registries:
      - google-artifact-registry
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: "/frontend/mr-admin-flate/.nais/"
    registries:
      - google-artifact-registry
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: "/frontend/mulighetsrommet-veileder-flate/.nais/"
    registries:
      - google-artifact-registry
    schedule:
      interval: daily
