version: 2

registries:
  maven-github:
    type: maven-repository
    url: https://github-package-registry-mirror.gc.nav.no/cached/maven-release
    username: x-access-token
    password: no-secret-required

  google-artifact-registry:
    type: docker-registry
    url: https://europe-north1-docker.pkg.dev
    username: _json_key_base64
    password: ${{ secrets.GOOGLE_ARTIFACT_REGISTRY_READ_TOKEN }}

  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.READER_TOKEN }}

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Europe/Oslo
    open-pull-requests-limit: 10

  - package-ecosystem: gradle
    directory: "/"
    registries:
      - maven-github
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Europe/Oslo
    open-pull-requests-limit: 10
    groups:
      # Trukket ut til egen gruppe siden nye versjoner av biblioteket kan introdusere regler som gjør at bygget feiler
      ktlint:
        patterns:
          - "com.pinterest.ktlint:ktlint-cli"

      patches:
        update-types:
          - "patch"
        exclude-patterns:
          - "com.pinterest.ktlint:ktlint-cli"

      minorversions:
        update-types:
          - "minor"
        exclude-patterns:
          - "com.pinterest.ktlint:ktlint-cli"

  - package-ecosystem: npm
    directory: "/"
    registries:
      - npm-github
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Europe/Oslo
    open-pull-requests-limit: 10
    groups:
      # Trukket ut til egen gruppe siden biblioteket enda ikke er stabilt
      hey-api:
        patterns:
          - "@hey-api/openapi-ts"

      playwright:
        patterns:
          - "playwright"
          - "@playwright/test"

      nav-designsystem:
        patterns:
          - "@navikt/aksel-*"
          - "@navikt/ds-*"

      react:
        patterns:
          - "react"
          - "react-dom"

      rsjf:
        patterns:
          - "@rjsf/*"

      patches:
        update-types:
          - "patch"
        exclude-patterns:
          - "playwright"
          - "@playwright/test"
          - "react"
          - "react-dom"
          - "@navikt/aksel-*"
          - "@navikt/ds-*"
          - "@rjsf/*"

      minorversions:
        update-types:
          - "minor"
        exclude-patterns:
          - "playwright"
          - "@playwright/test"
          - "react"
          - "react-dom"
          - "@navikt/aksel-*"
          - "@navikt/ds-*"
          - "@rjsf/*"

  # Test versjonsoppdatering av docker images i nais config
  - package-ecosystem: docker
    directory: "/frontend/arena-adapter-manager/.nais/"
    registries:
      - google-artifact-registry
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: "/frontend/mr-admin-flate/.nais/"
    registries:
      - google-artifact-registry
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: "/frontend/mulighetsrommet-veileder-flate/.nais/"
    registries:
      - google-artifact-registry
    schedule:
      interval: daily
