apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: mr-admin-flate-demo
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
spec:
  image: ghcr.io/navikt/poao-frontend/poao-frontend:2023.04.13_12.56-e509a7e7034a
  port: 8080
  ingresses:
    - https://mulighetsrommet-admin-flate.ekstern.dev.nav.no
    - https://mulighetsrommet-admin-flate-demo.ekstern.dev.nav.no
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 75
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  gcp:
    buckets:
      - name: mr-admin-flate-demo
        cascadingDelete: false
  env:
    - name: JSON_CONFIG
      value: >
        {
          "gcs": {
            "bucketName": "mr-admin-flate-demo"
          }
          "header": {
            "csp": {
              "scriptSrc": ["'self'", "unsafe-inline", "esm.sh", "intern.dev.nav.no"]
            }
          },
        }
