apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: mr-admin-flate
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/poao/poao-frontend:2025.05.05_06.50-1fe97d204c27
  port: 8080
  ingresses:
    - https://tiltaksadministrasjon.intern.nav.no
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    min: 2
    max: 3
    scalingStrategy:
      cpu:
        thresholdPercentage: 75
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 256Mi
  azure:
    application:
      enabled: true
      tenant: nav.no
      allowAllUsers: false
      claims:
        extra:
          - NAVident
        groups:
          - id: debefa6e-1865-446d-b22b-9579fc735de3 # team-mulighetsrommet
          - id: 33053061-86da-4d6b-9372-33238fabd25f # 0000-GA-TILTAK-tiltaksgjennomforinger_skriv
          - id: 46ba8787-eb24-4f7b-830f-4c5e9256de65 # 0000-GA-TILTAK-avtaler_skriv
          - id: 2cf8d881-c2da-47b5-b409-fa088440a629 # 0000-GA-TILTAK-ANSVARLIG

    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /assets/*
        - /asset-manifest.json
        - /mulighetsrommet-api/**
  gcp:
    buckets:
      - name: mr-admin-flate-prod
        cascadingDelete: false
  accessPolicy:
    outbound:
      rules:
        - application: mulighetsrommet-api
        - application: amt-deltaker-bff
          namespace: amt
  env:
    - name: JSON_CONFIG
      value: >
        {
          "gcs": {
            "bucketName": "mr-admin-flate-prod"
          },
          "auth": {
            "loginProvider": "AZURE_AD"
          },
          "header": {
            "csp": {
              "scriptSrc": ["'self'", "'unsafe-inline'", "*.nav.no", "*.nav.no"],
              "connectSrc": ["'self'", "'unsafe-inline'", "*.nav.no", "login.microsoftonline.com"]
            }
          },
          "proxies": [
            {
              "fromPath": "/mulighetsrommet-api",
              "toUrl": "http://mulighetsrommet-api",
              "preserveFromPath": false,
              "toApp": {
                "name": "mulighetsrommet-api",
                "namespace": "team-mulighetsrommet",
                "cluster": "prod-gcp"
              }
            },
            {
              "fromPath": "/amt-deltaker-bff",
              "preserveFromPath": false,
              "toUrl": "http://amt-deltaker-bff.amt",
              "toApp": {
                "name": "amt-deltaker-bff",
                "namespace": "amt",
                "cluster": "prod-gcp"
              }
            }
          ]
        }
