apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: mr-admin-flate
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
spec:
  image: ghcr.io/navikt/poao-frontend/poao-frontend:2023.02.20_08.24-b2e15514d880
  port: 8080
  ingresses:
    - https://mulighetsrommet-admin-flate.intern.nav.no
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  azure:
    application:
      enabled: true
      tenant: nav.no
      allowAllUsers: false
      claims:
        extra:
          - NAVident
        groups:
          - id: 676673aa-ec8f-4606-8399-723dce26b361 # team-mulighetsrommet
          - id: 2cf8d881-c2da-47b5-b409-fa088440a629 # 0000-GA-TILTAK-ANSVARLIG
          - id: b714d314-24c3-4bee-95cf-8f7374734785 # 0000-GA-FAGANSVARLIG
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /assets/*
        - /asset-manifest.json
  gcp:
    buckets:
      - name: mr-admin-flate-prod
        cascadingDelete: false
  accessPolicy:
    outbound:
      rules:
        - application: poao-unleash
          namespace: poao
          cluster: prod-gcp
        - application: mulighetsrommet-api
  env:
    - name: JSON_CONFIG
      value: >
        {
          "gcs": {
            "bucketName": "mr-admin-flate-prod"
          },
          "auth": {
            "loginProvider": "AZURE_AD"
          },
          "proxies": [
            {
              "fromPath": "/unleash",
              "toUrl": "http://poao-unleash.poao.svc.cluster.local",
              "preserveFromPath": false,
               "toApp": {
                "name": "poao-unleash",
                "namespace": "poao",
                "cluster": "prod-gcp"
              }
            },
            {
              "fromPath": "/mulighetsrommet-api",
              "toUrl": "http://mulighetsrommet-api",
              "preserveFromPath": false,
              "toApp": {
                "name": "mulighetsrommet-api",
                "namespace": "team-mulighetsrommet",
                "cluster": "prod-gcp"
              }
            }
          ]
        }
