apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: mr-admin-flate
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/poao/poao-frontend:2024.11.21_09.54-0ac322d0d0af
  port: 8080
  ingresses:
    - https://tiltaksadministrasjon.intern.dev.nav.no
    - https://tiltaksadministrasjon.ansatt.dev.nav.no
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    min: 1
    max: 1
    scalingStrategy:
      cpu:
        thresholdPercentage: 75
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 256Mi
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: 639e2806-4cc2-484c-a72a-51b4308c52a1 # team-mulighetsrommet
          - id: 279039a0-39fd-4860-afdd-a1a2ccaa6323 # 0000-AZ-TILTAK-tiltaksgjennomforinger_skriv
          - id: 48026f54-6259-4c35-a148-bc4257bcaf03 # 0000-ZA-TILTAK-avtaler_skriv
          - id: 52bb9196-b071-4cc7-9472-be4942d33c4b # 0000-GA-TILTAK-ANSVARLIG
        extra:
          - NAVident
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /assets/*
        - /asset-manifest.json
        - /mulighetsrommet-api/**
  gcp:
    buckets:
      - name: mr-admin-flate-dev
        cascadingDelete: false
  accessPolicy:
    outbound:
      rules:
        - application: mulighetsrommet-api
        - application: amt-deltaker-bff
          namespace: amt
  env:
    - name: JSON_CONFIG
      value: >
        {
          "gcs": {
            "bucketName": "mr-admin-flate-dev"
          },
          "auth": {
            "loginProvider": "AZURE_AD"
          },
          "header": {
            "csp": {
              "scriptSrc": ["'self'", "'unsafe-inline'", "*.intern.dev.nav.no", "*.nav.no"],
              "connectSrc": ["'self'", "'unsafe-inline'", "*.nav.no", "login.microsoftonline.com"]
            }
          },
          "proxies": [
            {
              "fromPath": "/mulighetsrommet-api",
              "toUrl": "http://mulighetsrommet-api",
              "preserveFromPath": false,
              "toApp": {
                "name": "mulighetsrommet-api",
                "namespace": "team-mulighetsrommet",
                "cluster": "dev-gcp"
              }
            },
            {
              "fromPath": "/amt-deltaker-bff",
              "preserveFromPath": false,
              "toUrl": "http://amt-deltaker-bff.amt",
              "toApp": {
                "name": "amt-deltaker-bff",
                "namespace": "amt",
                "cluster": "dev-gcp"
              }
            }
          ]
        }
