apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: mr-admin-flate-demo
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/poao/poao-frontend:2024.01.12_07.12-9746fba905ca
  port: 8080
  ingresses:
    - https://mulighetsrommet-admin-flate.ekstern.dev.nav.no
    - https://mulighetsrommet-admin-flate-demo.ekstern.dev.nav.no
    - https://tiltaksadministrasjon.ekstern.dev.nav.no
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    min: 1
    max: 1
    scalingStrategy:
      cpu:
        thresholdPercentage: 75
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  gcp:
    buckets:
      - name: mr-admin-flate-demo
        cascadingDelete: false
  env:
    - name: JSON_CONFIG
      value: >
        {
          "gcs": {
            "bucketName": "mr-admin-flate-demo"
          },
          "header": {
            "csp": {
              "scriptSrc": ["'self'", "'unsafe-inline'", "*.intern.dev.nav.no", "*.nav.no"],
              "connectSrc": ["'self'", "'unsafe-inline'", "*.nav.no", "login.microsoftonline.com"]
            }
          }
        }
