packages:
  # all packages in direct subdirs of packages/
  - "frontend/*"

# Sørger for at installerte pakker må være 7 dager gamle før de kan installeres (likt som dependabot cooldown)
# Et sikkerhetstiltak i tilfelle en pakke blir komprimittert
minimumReleaseAge: 10080 # 24 x 60 x 7

# Unntak for manuelt oppdaterte pakker innenfor minimumReleaseAge
minimumReleaseAgeExclude:
  - vite@8.0.5
  # CVE-2026-41242
  - "@grafana/faro-react@2.4.0"
  - "@grafana/faro-web-tracing@2.4.0"
  - "@grafana/faro-web-sdk@2.4.0"
  - "@grafana/faro-core@2.4.0"

# Gjør at peer dependencies ikke blir installert automatisk og at vi i stedet må ta aktiv stilling
# til hvilke peer dependencies vi ønsker å støtte
autoInstallPeers: false

overrides:
  "vite@>=4.0.0 <4.5.4": ">=4.5.4"

# Whitelist av pakker som har lov til å kjøre (pre|post)install scripts
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - "esbuild"
  - "msw"
