# Sørger for at installerte pakker må være 48 timer gamle før de kan installeres
# Et sikkerhetstiltak i tilfelle en pakke blir komprimittert
minimumReleaseAge: 2880

# Gjør at peer dependencies ikke blir installert automatisk og at vi i stedet må ta aktiv stilling
# til hvilke peer dependencies vi ønsker å støtte
autoInstallPeers: false

packages:
  # all packages in direct subdirs of packages/
  - "frontend/*"
