# Sørger for at installerte pakker må være 7 dager gamle før de kan installeres (likt som dependabot cooldown)
# Et sikkerhetstiltak i tilfelle en pakke blir komprimittert
minimumReleaseAge: 10080 # 24 x 60 x 7

# Unntak for manuelt oppdaterte pakker innenfor minimumReleaseAge
minimumReleaseAgeExclude:
  - react@19.0.1 #CVE-2025-55182
  - react-dom@19.0.1 #CVE-2025-55182
  - react-router@7.12.0 #CVE-2026-21884, CVE-2026-22029, CVE-2026-22030

# Gjør at peer dependencies ikke blir installert automatisk og at vi i stedet må ta aktiv stilling
# til hvilke peer dependencies vi ønsker å støtte
autoInstallPeers: false

packages:
  # all packages in direct subdirs of packages/
  - "frontend/*"
