name: Setup frontend
description: Steps for setup of the frontend modules

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
    - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version: 24
        cache: pnpm
        registry-url: "https://npm.pkg.github.com"
    - run: pnpm install
      shell: bash
    - name: Cache Turborepo
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: |
          .turbo
          frontend/*/.turbo
        key: turborepo-${{ github.ref_name }}-${{ github.sha }}
        restore-keys: |
          turborepo-${{ github.ref_name }}-
          turborepo-
