name: Setup frontend
description: Steps for setup of the frontend modules

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm
        registry-url: "https://npm.pkg.github.com"
    - run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      shell: bash
    - name: Cache Turborepo
      uses: actions/cache@v4
      with:
        path: |
          .turbo
          frontend/*/.turbo
        key: turborepo-${{ github.ref_name }}-${{ github.sha }}
        restore-keys: |
          turborepo-${{ github.ref_name }}-
          turborepo-
