name: Setup frontend
description: Steps for setup of the frontend modules

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: 24
        cache: pnpm
        registry-url: "https://npm.pkg.github.com"
    - run: pnpm install
      shell: bash
    - name: Cache Turborepo
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: |
          .turbo
          frontend/*/.turbo
        key: turborepo-${{ github.ref_name }}-${{ github.sha }}
        restore-keys: |
          turborepo-${{ github.ref_name }}-
          turborepo-
