name: Setup frontend
description: Steps for setup of the frontend modules

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: pnpm
        registry-url: "https://npm.pkg.github.com"
    - run: pnpm install
      shell: bash
    - name: Cache Turborepo
      uses: actions/cache@v4
      with:
        path: |
          .turbo
          frontend/*/.turbo
        key: turborepo-${{ github.ref_name }}-${{ github.sha }}
        restore-keys: |
          turborepo-${{ github.ref_name }}-
          turborepo-
