version: '2'
services:
  mulighetsrommet-api-db:
    image: "postgres:12.3-alpine"
    restart: "always"
    volumes:
      - "mulighetsrommet:/var/lib/postgresql/data"
    ports:
      - "5442:5432"
    environment:
      POSTGRES_USER: "valp"
      POSTGRES_PASSWORD: "valp"
      POSTGRES_DB: "mulighetsrommet-api-db"
    mem_limit: "8g"
volumes:
  mulighetsrommet:
