version: '2'
services:
  postgres:
    image: "postgres:12.3-alpine"
    restart: "always"
    volumes:
      - "amt-informasjon-api:/var/lib/postgresql/data"
    ports:
      - "5442:5432"
    environment:
      POSTGRES_USER: "valp"
      POSTGRES_PASSWORD: "valp"
      POSTGRES_DB: "amt-informasjon-api"
    mem_limit: "8g"
  zookeeper:
    image: "confluentinc/cp-zookeeper:latest"
    ports:
      - "2191:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: "confluentinc/cp-kafka:latest"
    depends_on:
      - zookeeper
    ports:
      - "10002:10002"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:10002
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafdrop:
    image: obsidiandynamics/kafdrop
    depends_on:
      - kafka
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
volumes:
  amt-informasjon-api:
