insert into deltaker_registrering_innholdselement (innholdskode, tekst)
values ('arbeidsutproving',
        'Arbeidsutprøving'),
       ('jobbsoking',
        'Støtte til å søke jobber'),
       ('arbeidspraksis',
        'Arbeidspraksis'),
       ('karriereveiledning',
        'Karriereveiledning'),
       ('kartlegge-helse',
        'Kartlegge hvordan helsen din påvirker muligheten din til å jobbe'),
       ('kartlegge-forventninger',
        'Kartlegge dine forventninger til å jobbe'),
       ('kartlegge-arbeidsplassen',
        'Kartlegge hvilken støtte og tilpasning du trenger på arbeidsplassen'),
       ('kartlegge-delta-tiltak',
        'Kartlegge hvilken støtte du trenger for å delta på et arbeidsmarkedstiltak'),
       ('kartlegge-grunnleggende-ferdigheter',
        'Kartlegge grunnleggende ferdigheter som språk og hvordan du leser, skriver, regner og bruker datamaskin'),
       ('veiledning-livsstil',
        'Veiledning om livsstil og kosthold'),
       ('motivasjon',
        'Motivasjons- og mestringsaktiviteter'),
       ('veiledning-sosialt',
        'Veiledning i sosial mestring'),
       ('veiledning-trening',
        'Individuelt treningsopplegg med veiledning'),
       ('oppfolging-arbeidsplassen',
        'Oppfølging på arbeidsplassen'),
       ('veiledning-arbeidsgiver',
        'Veiledning til arbeidsgiver'),
       ('tilpasse-arbeidsoppgaver',
        'Hjelp til å tilpasse arbeidsoppgaver og arbeidsplassen')
on conflict (innholdskode) do update set tekst = excluded.tekst;
