/**
 * Script for å populere tabeller med strukturert informasjon om
 * hvilke personopplysninger avtaler på en gitt tiltakstype kan velge mellom.
 */

insert into tiltakstype_personopplysning(tiltakskode, personopplysning, hjelpetekst)
select *
from (values ('AVKLARING'::tiltakskode, 'NAVN'::personopplysning, null),
             ('AVKLARING'::tiltakskode, 'KJONN'::personopplysning, null),
             ('AVKLARING'::tiltakskode, 'ADRESSE'::personopplysning, null),
             ('AVKLARING'::tiltakskode, 'TELEFONNUMMER'::personopplysning, null),
             ('AVKLARING'::tiltakskode, 'FOLKEREGISTER_IDENTIFIKATOR'::personopplysning,
              null),
             ('AVKLARING'::tiltakskode, 'FODSELSDATO'::personopplysning, null),
             ('AVKLARING'::tiltakskode, 'BEHOV_FOR_BISTAND_FRA_NAV'::personopplysning,
              null),
             ('AVKLARING'::tiltakskode, 'YTELSER_FRA_NAV'::personopplysning, null),
             ('AVKLARING'::tiltakskode, 'BILDE'::personopplysning, null),
             ('AVKLARING'::tiltakskode, 'EPOST'::personopplysning, null),
             ('AVKLARING'::tiltakskode, 'BRUKERNAVN'::personopplysning, null),
             ('AVKLARING'::tiltakskode, 'ARBEIDSERFARING_OG_VERV'::personopplysning,
              null),
             ('AVKLARING'::tiltakskode, 'SERTIFIKATER_OG_KURS'::personopplysning,
              null),
             ('AVKLARING'::tiltakskode, 'IP_ADRESSE'::personopplysning, null),
             ('AVKLARING'::tiltakskode, 'UTDANNING_OG_FAGBREV'::personopplysning,
              null),
             ('AVKLARING'::tiltakskode, 'PERSONLIGE_EGENSKAPER_OG_INTERESSER',
              null),
             ('AVKLARING'::tiltakskode, 'SPRAKKUNNSKAP', null),
             ('AVKLARING'::tiltakskode, 'ADFERD'::personopplysning, null),
             ('AVKLARING'::tiltakskode, 'SOSIALE_FORHOLD'::personopplysning, null),
             ('AVKLARING'::tiltakskode, 'HELSEOPPLYSNINGER'::personopplysning,
              null),
             ('AVKLARING'::tiltakskode, 'RELIGION'::personopplysning,
              null)) as t(tiltakskode, personvernopplysning, hjelpetekst)
where exists (select 1 from tiltakstype where tiltakskode = 'AVKLARING'::tiltakskode)
on conflict(tiltakskode, personopplysning) do update
    set hjelpetekst = excluded.hjelpetekst;

insert into tiltakstype_personopplysning(tiltakskode, personopplysning, hjelpetekst)
select *
from (values ('OPPFOLGING'::tiltakskode, 'NAVN'::personopplysning, null),
             ('OPPFOLGING'::tiltakskode, 'KJONN'::personopplysning, null),
             ('OPPFOLGING'::tiltakskode, 'ADRESSE'::personopplysning, null),
             ('OPPFOLGING'::tiltakskode, 'TELEFONNUMMER'::personopplysning, null),
             ('OPPFOLGING'::tiltakskode, 'FOLKEREGISTER_IDENTIFIKATOR'::personopplysning,
              null),
             ('OPPFOLGING'::tiltakskode, 'FODSELSDATO'::personopplysning, null),
             ('OPPFOLGING'::tiltakskode, 'BEHOV_FOR_BISTAND_FRA_NAV'::personopplysning,
              null),
             ('OPPFOLGING'::tiltakskode, 'YTELSER_FRA_NAV'::personopplysning,
              null),
             ('OPPFOLGING'::tiltakskode, 'BILDE'::personopplysning, null),
             ('OPPFOLGING'::tiltakskode, 'EPOST'::personopplysning, null),
             ('OPPFOLGING'::tiltakskode, 'BRUKERNAVN'::personopplysning, null),
             ('OPPFOLGING'::tiltakskode, 'ARBEIDSERFARING_OG_VERV'::personopplysning,
              null),
             ('OPPFOLGING'::tiltakskode, 'SERTIFIKATER_OG_KURS'::personopplysning,
              null),
             ('OPPFOLGING'::tiltakskode, 'IP_ADRESSE'::personopplysning, null),
             ('OPPFOLGING'::tiltakskode, 'UTDANNING_OG_FAGBREV'::personopplysning,
              null),
             ('OPPFOLGING'::tiltakskode, 'PERSONLIGE_EGENSKAPER_OG_INTERESSER',
              null),
             ('OPPFOLGING'::tiltakskode, 'SPRAKKUNNSKAP', null),
             ('OPPFOLGING'::tiltakskode, 'ADFERD'::personopplysning, null),
             ('OPPFOLGING'::tiltakskode, 'SOSIALE_FORHOLD'::personopplysning, null),
             ('OPPFOLGING'::tiltakskode, 'HELSEOPPLYSNINGER'::personopplysning,
              null),
             ('OPPFOLGING'::tiltakskode, 'RELIGION'::personopplysning,
              null)) as t(tiltakskode, personvernopplysning, hjelpetekst)
where exists (select 1 from tiltakstype where tiltakskode = 'OPPFOLGING'::tiltakskode)
on conflict(tiltakskode, personopplysning) do update
    set hjelpetekst = excluded.hjelpetekst;

insert into tiltakstype_personopplysning(tiltakskode, personopplysning, hjelpetekst)
select *
from (values ('JOBBKLUBB'::tiltakskode, 'NAVN'::personopplysning, null),
             ('JOBBKLUBB'::tiltakskode, 'KJONN'::personopplysning, null),
             ('JOBBKLUBB'::tiltakskode, 'ADRESSE'::personopplysning, null),
             ('JOBBKLUBB'::tiltakskode, 'TELEFONNUMMER'::personopplysning, null),
             ('JOBBKLUBB'::tiltakskode, 'FOLKEREGISTER_IDENTIFIKATOR'::personopplysning,
              null),
             ('JOBBKLUBB'::tiltakskode, 'FODSELSDATO'::personopplysning, null),
             ('JOBBKLUBB'::tiltakskode, 'BEHOV_FOR_BISTAND_FRA_NAV'::personopplysning,
              null),
             ('JOBBKLUBB'::tiltakskode, 'YTELSER_FRA_NAV'::personopplysning, null),
             ('JOBBKLUBB'::tiltakskode, 'BILDE'::personopplysning, null),
             ('JOBBKLUBB'::tiltakskode, 'EPOST'::personopplysning, null),
             ('JOBBKLUBB'::tiltakskode, 'BRUKERNAVN'::personopplysning, null),
             ('JOBBKLUBB'::tiltakskode, 'ARBEIDSERFARING_OG_VERV'::personopplysning,
              null),
             ('JOBBKLUBB'::tiltakskode, 'SERTIFIKATER_OG_KURS'::personopplysning,
              null),
             ('JOBBKLUBB'::tiltakskode, 'IP_ADRESSE'::personopplysning, null),
             ('JOBBKLUBB'::tiltakskode, 'UTDANNING_OG_FAGBREV'::personopplysning,
              null),
             ('JOBBKLUBB'::tiltakskode, 'PERSONLIGE_EGENSKAPER_OG_INTERESSER',
              null),
             ('JOBBKLUBB'::tiltakskode, 'SPRAKKUNNSKAP', null),
             ('JOBBKLUBB'::tiltakskode, 'ADFERD'::personopplysning, null),
             ('JOBBKLUBB'::tiltakskode, 'SOSIALE_FORHOLD'::personopplysning, null),
             ('JOBBKLUBB'::tiltakskode, 'HELSEOPPLYSNINGER'::personopplysning,
              null),
             ('JOBBKLUBB'::tiltakskode, 'RELIGION'::personopplysning,
              null)) as t(tiltakskode, personvernopplysning, hjelpetekst)
where exists (select 1 from tiltakstype where tiltakskode = 'JOBBKLUBB'::tiltakskode)
on conflict(tiltakskode, personopplysning) do update
    set hjelpetekst = excluded.hjelpetekst;

insert into tiltakstype_personopplysning(tiltakskode, personopplysning, hjelpetekst)
select *
from (values ('DIGITALT_OPPFOLGINGSTILTAK'::tiltakskode, 'NAVN'::personopplysning,
              null),
             ('DIGITALT_OPPFOLGINGSTILTAK'::tiltakskode, 'KJONN'::personopplysning,
              null),
             ('DIGITALT_OPPFOLGINGSTILTAK'::tiltakskode, 'ADRESSE'::personopplysning,
              null),
             ('DIGITALT_OPPFOLGINGSTILTAK'::tiltakskode, 'TELEFONNUMMER'::personopplysning,
              null),
             ('DIGITALT_OPPFOLGINGSTILTAK'::tiltakskode, 'FOLKEREGISTER_IDENTIFIKATOR'::personopplysning,
              null),
             ('DIGITALT_OPPFOLGINGSTILTAK'::tiltakskode, 'FODSELSDATO'::personopplysning,
              null),
             ('DIGITALT_OPPFOLGINGSTILTAK'::tiltakskode, 'BEHOV_FOR_BISTAND_FRA_NAV'::personopplysning,
              null),
             ('DIGITALT_OPPFOLGINGSTILTAK'::tiltakskode, 'YTELSER_FRA_NAV'::personopplysning,
              null),
             ('DIGITALT_OPPFOLGINGSTILTAK'::tiltakskode, 'BILDE'::personopplysning,
              null),
             ('DIGITALT_OPPFOLGINGSTILTAK'::tiltakskode, 'EPOST'::personopplysning,
              null),
             ('DIGITALT_OPPFOLGINGSTILTAK'::tiltakskode, 'BRUKERNAVN'::personopplysning,
              null),
             ('DIGITALT_OPPFOLGINGSTILTAK'::tiltakskode, 'ARBEIDSERFARING_OG_VERV'::personopplysning,
              null),
             ('DIGITALT_OPPFOLGINGSTILTAK'::tiltakskode, 'SERTIFIKATER_OG_KURS'::personopplysning,
              null),
             ('DIGITALT_OPPFOLGINGSTILTAK'::tiltakskode, 'IP_ADRESSE'::personopplysning,
              null),
             ('DIGITALT_OPPFOLGINGSTILTAK'::tiltakskode, 'UTDANNING_OG_FAGBREV'::personopplysning,
              null),
             ('DIGITALT_OPPFOLGINGSTILTAK'::tiltakskode, 'PERSONLIGE_EGENSKAPER_OG_INTERESSER',
              null),
             ('DIGITALT_OPPFOLGINGSTILTAK'::tiltakskode, 'SPRAKKUNNSKAP', null),
             ('DIGITALT_OPPFOLGINGSTILTAK'::tiltakskode, 'ADFERD'::personopplysning,
              null),
             ('DIGITALT_OPPFOLGINGSTILTAK'::tiltakskode, 'SOSIALE_FORHOLD'::personopplysning,
              null),
             ('DIGITALT_OPPFOLGINGSTILTAK'::tiltakskode, 'HELSEOPPLYSNINGER'::personopplysning,
              null),
             ('DIGITALT_OPPFOLGINGSTILTAK'::tiltakskode, 'RELIGION'::personopplysning,
              null)) as t(tiltakskode, personvernopplysning, hjelpetekst)
where exists (select 1 from tiltakstype where tiltakskode = 'DIGITALT_OPPFOLGINGSTILTAK'::tiltakskode)
on conflict(tiltakskode, personopplysning) do update
    set hjelpetekst = excluded.hjelpetekst;

insert into tiltakstype_personopplysning(tiltakskode, personopplysning, hjelpetekst)
select *
from (values ('GRUPPE_ARBEIDSMARKEDSOPPLAERING'::tiltakskode, 'NAVN'::personopplysning,
              null),
             ('GRUPPE_ARBEIDSMARKEDSOPPLAERING'::tiltakskode, 'KJONN'::personopplysning,
              null),
             ('GRUPPE_ARBEIDSMARKEDSOPPLAERING'::tiltakskode, 'ADRESSE'::personopplysning,
              null),
             ('GRUPPE_ARBEIDSMARKEDSOPPLAERING'::tiltakskode, 'TELEFONNUMMER'::personopplysning,
              null),
             ('GRUPPE_ARBEIDSMARKEDSOPPLAERING'::tiltakskode, 'FOLKEREGISTER_IDENTIFIKATOR'::personopplysning,
              null),
             ('GRUPPE_ARBEIDSMARKEDSOPPLAERING'::tiltakskode, 'FODSELSDATO'::personopplysning,
              null),
             ('GRUPPE_ARBEIDSMARKEDSOPPLAERING'::tiltakskode, 'BEHOV_FOR_BISTAND_FRA_NAV'::personopplysning,
              null),
             ('GRUPPE_ARBEIDSMARKEDSOPPLAERING'::tiltakskode, 'YTELSER_FRA_NAV'::personopplysning,
              null),
             ('GRUPPE_ARBEIDSMARKEDSOPPLAERING'::tiltakskode, 'BILDE'::personopplysning,
              null),
             ('GRUPPE_ARBEIDSMARKEDSOPPLAERING'::tiltakskode, 'EPOST'::personopplysning,
              null),
             ('GRUPPE_ARBEIDSMARKEDSOPPLAERING'::tiltakskode, 'BRUKERNAVN'::personopplysning,
              null),
             ('GRUPPE_ARBEIDSMARKEDSOPPLAERING'::tiltakskode, 'ARBEIDSERFARING_OG_VERV'::personopplysning,
              null),
             ('GRUPPE_ARBEIDSMARKEDSOPPLAERING'::tiltakskode, 'SERTIFIKATER_OG_KURS'::personopplysning,
              null),
             ('GRUPPE_ARBEIDSMARKEDSOPPLAERING'::tiltakskode, 'IP_ADRESSE'::personopplysning,
              null),
             ('GRUPPE_ARBEIDSMARKEDSOPPLAERING'::tiltakskode, 'UTDANNING_OG_FAGBREV'::personopplysning,
              null),
             ('GRUPPE_ARBEIDSMARKEDSOPPLAERING'::tiltakskode, 'PERSONLIGE_EGENSKAPER_OG_INTERESSER',
              null),
             ('GRUPPE_ARBEIDSMARKEDSOPPLAERING'::tiltakskode, 'SPRAKKUNNSKAP', null),
             ('GRUPPE_ARBEIDSMARKEDSOPPLAERING'::tiltakskode, 'ADFERD'::personopplysning,
              null),
             ('GRUPPE_ARBEIDSMARKEDSOPPLAERING'::tiltakskode, 'SOSIALE_FORHOLD'::personopplysning,
              null),
             ('GRUPPE_ARBEIDSMARKEDSOPPLAERING'::tiltakskode, 'HELSEOPPLYSNINGER'::personopplysning,
              null),
             ('GRUPPE_ARBEIDSMARKEDSOPPLAERING'::tiltakskode, 'RELIGION'::personopplysning,
              null)) as t(tiltakskode, personvernopplysning, hjelpetekst)
where exists (select 1 from tiltakstype where tiltakskode = 'GRUPPE_ARBEIDSMARKEDSOPPLAERING'::tiltakskode)
on conflict(tiltakskode, personopplysning) do update
    set hjelpetekst = excluded.hjelpetekst;

insert into tiltakstype_personopplysning(tiltakskode, personopplysning, hjelpetekst)
select *
from (values ('GRUPPE_FAG_OG_YRKESOPPLAERING'::tiltakskode, 'NAVN'::personopplysning,
              null),
             ('GRUPPE_FAG_OG_YRKESOPPLAERING'::tiltakskode, 'KJONN'::personopplysning,
              null),
             ('GRUPPE_FAG_OG_YRKESOPPLAERING'::tiltakskode, 'ADRESSE'::personopplysning,
              null),
             ('GRUPPE_FAG_OG_YRKESOPPLAERING'::tiltakskode, 'TELEFONNUMMER'::personopplysning,
              null),
             ('GRUPPE_FAG_OG_YRKESOPPLAERING'::tiltakskode, 'FOLKEREGISTER_IDENTIFIKATOR'::personopplysning,
              null),
             ('GRUPPE_FAG_OG_YRKESOPPLAERING'::tiltakskode, 'FODSELSDATO'::personopplysning,
              null),
             ('GRUPPE_FAG_OG_YRKESOPPLAERING'::tiltakskode, 'BEHOV_FOR_BISTAND_FRA_NAV'::personopplysning,
              null),
             ('GRUPPE_FAG_OG_YRKESOPPLAERING'::tiltakskode, 'YTELSER_FRA_NAV'::personopplysning,
              null),
             ('GRUPPE_FAG_OG_YRKESOPPLAERING'::tiltakskode, 'BILDE'::personopplysning,
              null),
             ('GRUPPE_FAG_OG_YRKESOPPLAERING'::tiltakskode, 'EPOST'::personopplysning,
              null),
             ('GRUPPE_FAG_OG_YRKESOPPLAERING'::tiltakskode, 'BRUKERNAVN'::personopplysning,
              null),
             ('GRUPPE_FAG_OG_YRKESOPPLAERING'::tiltakskode, 'ARBEIDSERFARING_OG_VERV'::personopplysning,
              null),
             ('GRUPPE_FAG_OG_YRKESOPPLAERING'::tiltakskode, 'SERTIFIKATER_OG_KURS'::personopplysning,
              null),
             ('GRUPPE_FAG_OG_YRKESOPPLAERING'::tiltakskode, 'IP_ADRESSE'::personopplysning,
              null),
             ('GRUPPE_FAG_OG_YRKESOPPLAERING'::tiltakskode, 'UTDANNING_OG_FAGBREV'::personopplysning,
              null),
             ('GRUPPE_FAG_OG_YRKESOPPLAERING'::tiltakskode, 'PERSONLIGE_EGENSKAPER_OG_INTERESSER',
              null),
             ('GRUPPE_FAG_OG_YRKESOPPLAERING'::tiltakskode, 'SPRAKKUNNSKAP', null),
             ('GRUPPE_FAG_OG_YRKESOPPLAERING'::tiltakskode, 'ADFERD'::personopplysning,
              null),
             ('GRUPPE_FAG_OG_YRKESOPPLAERING'::tiltakskode, 'SOSIALE_FORHOLD'::personopplysning,
              null),
             ('GRUPPE_FAG_OG_YRKESOPPLAERING'::tiltakskode, 'HELSEOPPLYSNINGER'::personopplysning,
              null),
             ('GRUPPE_FAG_OG_YRKESOPPLAERING'::tiltakskode, 'RELIGION'::personopplysning,
              null)) as t(tiltakskode, personvernopplysning, hjelpetekst)
where exists (select 1 from tiltakstype where tiltakskode = 'GRUPPE_FAG_OG_YRKESOPPLAERING'::tiltakskode)
on conflict(tiltakskode, personopplysning) do update
    set hjelpetekst = excluded.hjelpetekst;

insert into tiltakstype_personopplysning(tiltakskode, personopplysning, hjelpetekst)
select *
from (values ('ARBEIDSRETTET_REHABILITERING'::tiltakskode, 'NAVN'::personopplysning,
              null),
             ('ARBEIDSRETTET_REHABILITERING'::tiltakskode, 'KJONN'::personopplysning,
              null),
             ('ARBEIDSRETTET_REHABILITERING'::tiltakskode, 'ADRESSE'::personopplysning,
              null),
             ('ARBEIDSRETTET_REHABILITERING'::tiltakskode, 'TELEFONNUMMER'::personopplysning,
              null),
             ('ARBEIDSRETTET_REHABILITERING'::tiltakskode, 'FOLKEREGISTER_IDENTIFIKATOR'::personopplysning,
              null),
             ('ARBEIDSRETTET_REHABILITERING'::tiltakskode, 'FODSELSDATO'::personopplysning,
              null),
             ('ARBEIDSRETTET_REHABILITERING'::tiltakskode, 'BEHOV_FOR_BISTAND_FRA_NAV'::personopplysning,
              null),
             ('ARBEIDSRETTET_REHABILITERING'::tiltakskode, 'YTELSER_FRA_NAV'::personopplysning,
              null),
             ('ARBEIDSRETTET_REHABILITERING'::tiltakskode, 'BILDE'::personopplysning,
              null),
             ('ARBEIDSRETTET_REHABILITERING'::tiltakskode, 'EPOST'::personopplysning,
              null),
             ('ARBEIDSRETTET_REHABILITERING'::tiltakskode, 'BRUKERNAVN'::personopplysning,
              null),
             ('ARBEIDSRETTET_REHABILITERING'::tiltakskode, 'ARBEIDSERFARING_OG_VERV'::personopplysning,
              null),
             ('ARBEIDSRETTET_REHABILITERING'::tiltakskode, 'SERTIFIKATER_OG_KURS'::personopplysning,
              null),
             ('ARBEIDSRETTET_REHABILITERING'::tiltakskode, 'IP_ADRESSE'::personopplysning,
              null),
             ('ARBEIDSRETTET_REHABILITERING'::tiltakskode, 'UTDANNING_OG_FAGBREV'::personopplysning,
              null),
             ('ARBEIDSRETTET_REHABILITERING'::tiltakskode, 'PERSONLIGE_EGENSKAPER_OG_INTERESSER',
              null),
             ('ARBEIDSRETTET_REHABILITERING'::tiltakskode, 'SPRAKKUNNSKAP', null),
             ('ARBEIDSRETTET_REHABILITERING'::tiltakskode, 'ADFERD'::personopplysning,
              null),
             ('ARBEIDSRETTET_REHABILITERING'::tiltakskode, 'SOSIALE_FORHOLD'::personopplysning,
              null),
             ('ARBEIDSRETTET_REHABILITERING'::tiltakskode, 'HELSEOPPLYSNINGER'::personopplysning,
              null),
             ('ARBEIDSRETTET_REHABILITERING'::tiltakskode, 'RELIGION'::personopplysning,
              null)) as t(tiltakskode, personvernopplysning, hjelpetekst)
where exists (select 1 from tiltakstype where tiltakskode = 'ARBEIDSRETTET_REHABILITERING'::tiltakskode)
on conflict(tiltakskode, personopplysning) do update
    set hjelpetekst = excluded.hjelpetekst;

insert into tiltakstype_personopplysning(tiltakskode, personopplysning, hjelpetekst)
select *
from (values ('ARBEIDSFORBEREDENDE_TRENING'::tiltakskode, 'NAVN'::personopplysning,
              null),
             ('ARBEIDSFORBEREDENDE_TRENING'::tiltakskode, 'KJONN'::personopplysning,
              null),
             ('ARBEIDSFORBEREDENDE_TRENING'::tiltakskode, 'ADRESSE'::personopplysning,
              null),
             ('ARBEIDSFORBEREDENDE_TRENING'::tiltakskode, 'TELEFONNUMMER'::personopplysning,
              null),
             ('ARBEIDSFORBEREDENDE_TRENING'::tiltakskode, 'FOLKEREGISTER_IDENTIFIKATOR'::personopplysning,
              null),
             ('ARBEIDSFORBEREDENDE_TRENING'::tiltakskode, 'FODSELSDATO'::personopplysning,
              null),
             ('ARBEIDSFORBEREDENDE_TRENING'::tiltakskode, 'BEHOV_FOR_BISTAND_FRA_NAV'::personopplysning,
              null),
             ('ARBEIDSFORBEREDENDE_TRENING'::tiltakskode, 'YTELSER_FRA_NAV'::personopplysning,
              null),
             ('ARBEIDSFORBEREDENDE_TRENING'::tiltakskode, 'BILDE'::personopplysning,
              null),
             ('ARBEIDSFORBEREDENDE_TRENING'::tiltakskode, 'EPOST'::personopplysning,
              null),
             ('ARBEIDSFORBEREDENDE_TRENING'::tiltakskode, 'BRUKERNAVN'::personopplysning,
              null),
             ('ARBEIDSFORBEREDENDE_TRENING'::tiltakskode, 'ARBEIDSERFARING_OG_VERV'::personopplysning,
              null),
             ('ARBEIDSFORBEREDENDE_TRENING'::tiltakskode, 'SERTIFIKATER_OG_KURS'::personopplysning,
              null),
             ('ARBEIDSFORBEREDENDE_TRENING'::tiltakskode, 'IP_ADRESSE'::personopplysning,
              null),
             ('ARBEIDSFORBEREDENDE_TRENING'::tiltakskode, 'UTDANNING_OG_FAGBREV'::personopplysning,
              null),
             ('ARBEIDSFORBEREDENDE_TRENING'::tiltakskode, 'PERSONLIGE_EGENSKAPER_OG_INTERESSER',
              null),
             ('ARBEIDSFORBEREDENDE_TRENING'::tiltakskode, 'SPRAKKUNNSKAP', null),
             ('ARBEIDSFORBEREDENDE_TRENING'::tiltakskode, 'ADFERD'::personopplysning,
              null),
             ('ARBEIDSFORBEREDENDE_TRENING'::tiltakskode, 'SOSIALE_FORHOLD'::personopplysning,
              null),
             ('ARBEIDSFORBEREDENDE_TRENING'::tiltakskode, 'HELSEOPPLYSNINGER'::personopplysning,
              null),
             ('ARBEIDSFORBEREDENDE_TRENING'::tiltakskode, 'RELIGION'::personopplysning,
              null)) as t(tiltakskode, personvernopplysning, hjelpetekst)
where exists (select 1 from tiltakstype where tiltakskode = 'ARBEIDSFORBEREDENDE_TRENING'::tiltakskode)
on conflict(tiltakskode, personopplysning) do update
    set hjelpetekst = excluded.hjelpetekst;

insert into tiltakstype_personopplysning(tiltakskode, personopplysning, hjelpetekst)
select *
from (values ('VARIG_TILRETTELAGT_ARBEID_SKJERMET'::tiltakskode, 'NAVN'::personopplysning,
              null),
             ('VARIG_TILRETTELAGT_ARBEID_SKJERMET'::tiltakskode, 'KJONN'::personopplysning,
              null),
             ('VARIG_TILRETTELAGT_ARBEID_SKJERMET'::tiltakskode, 'ADRESSE'::personopplysning,
              null),
             ('VARIG_TILRETTELAGT_ARBEID_SKJERMET'::tiltakskode, 'TELEFONNUMMER'::personopplysning,
              null),
             ('VARIG_TILRETTELAGT_ARBEID_SKJERMET'::tiltakskode, 'FOLKEREGISTER_IDENTIFIKATOR'::personopplysning,
              null),
             ('VARIG_TILRETTELAGT_ARBEID_SKJERMET'::tiltakskode, 'FODSELSDATO'::personopplysning,
              null),
             ('VARIG_TILRETTELAGT_ARBEID_SKJERMET'::tiltakskode, 'BEHOV_FOR_BISTAND_FRA_NAV'::personopplysning,
              null),
             ('VARIG_TILRETTELAGT_ARBEID_SKJERMET'::tiltakskode, 'YTELSER_FRA_NAV'::personopplysning,
              null),
             ('VARIG_TILRETTELAGT_ARBEID_SKJERMET'::tiltakskode, 'BILDE'::personopplysning,
              null),
             ('VARIG_TILRETTELAGT_ARBEID_SKJERMET'::tiltakskode, 'EPOST'::personopplysning,
              null),
             ('VARIG_TILRETTELAGT_ARBEID_SKJERMET'::tiltakskode, 'BRUKERNAVN'::personopplysning,
              null),
             ('VARIG_TILRETTELAGT_ARBEID_SKJERMET'::tiltakskode, 'ARBEIDSERFARING_OG_VERV'::personopplysning,
              null),
             ('VARIG_TILRETTELAGT_ARBEID_SKJERMET'::tiltakskode, 'SERTIFIKATER_OG_KURS'::personopplysning,
              null),
             ('VARIG_TILRETTELAGT_ARBEID_SKJERMET'::tiltakskode, 'IP_ADRESSE'::personopplysning,
              null),
             ('VARIG_TILRETTELAGT_ARBEID_SKJERMET'::tiltakskode, 'UTDANNING_OG_FAGBREV'::personopplysning,
              null),
             ('VARIG_TILRETTELAGT_ARBEID_SKJERMET'::tiltakskode, 'PERSONLIGE_EGENSKAPER_OG_INTERESSER',
              null),
             ('VARIG_TILRETTELAGT_ARBEID_SKJERMET'::tiltakskode, 'SPRAKKUNNSKAP',
              null),
             ('VARIG_TILRETTELAGT_ARBEID_SKJERMET'::tiltakskode, 'ADFERD'::personopplysning,
              null),
             ('VARIG_TILRETTELAGT_ARBEID_SKJERMET'::tiltakskode, 'SOSIALE_FORHOLD'::personopplysning,
              null),
             ('VARIG_TILRETTELAGT_ARBEID_SKJERMET'::tiltakskode, 'HELSEOPPLYSNINGER'::personopplysning,
              null),
             ('VARIG_TILRETTELAGT_ARBEID_SKJERMET'::tiltakskode, 'RELIGION'::personopplysning,
              null)) as t(tiltakskode, personvernopplysning, hjelpetekst)
where exists (select 1 from tiltakstype where tiltakskode = 'VARIG_TILRETTELAGT_ARBEID_SKJERMET'::tiltakskode)
on conflict(tiltakskode, personopplysning) do update
    set hjelpetekst = excluded.hjelpetekst;
