drop view if exists refusjonskrav_aft_view;
drop view if exists refusjonskrav_admin_dto_view;

-- rename columns
alter table refusjonskrav_deltakelse_manedsverk rename column refusjonskrav_id to utbetaling_id;
alter table refusjonskrav_deltakelse_periode rename column refusjonskrav_id to utbetaling_id;
alter table refusjonskrav_beregning_aft rename column refusjonskrav_id to utbetaling_id;
alter table tilsagn_utbetaling rename column refusjonskrav_id to utbetaling_id;

-- rename indexes
alter index refusjonskrav_beregning_aft_pkey rename to utbetaling_beregning_aft_pkey;
alter index refusjonskrav_deltakelse_mane_refusjonskrav_id_deltakelse_i_key rename to utbetaling_deltakelse_mane_refusjonskrav_id_deltakelse_i_key;
alter index refusjonskrav_deltakelse_periode_deltakelse_id_periode_excl rename to utbetaling_deltakelse_periode_deltakelse_id_periode_excl;
alter index refusjonskrav_pkey rename to utbetaling_pkey;
alter index refusjonskrav_deltakelse_manedsverk_deltakelse_idx rename to utbetaling_deltakelse_manedsverk_deltakelse_idx;
alter index refusjonskrav_deltakelse_manedsverk_refusjonskrav_idx rename to utbetaling_deltakelse_manedsverk_utbetaling_idx;
alter index refusjonskrav_deltakelse_periode_deltakelse_idx rename to utbetaling_deltakelse_periode_deltakelse_idx;
alter index refusjonskrav_deltakelse_periode_refusjonskrav_idx rename to utbetaling_deltakelse_periode_utbetaling_idx;

-- rename constraints
alter table refusjonskrav_beregning_aft rename constraint refusjonskrav_beregning_aft_refusjonskrav_id_fkey to utbetaling_beregning_aft_utbetaling_id_fkey;
alter table refusjonskrav_deltakelse_manedsverk rename constraint refusjonskrav_deltakelse_manedsverk_refusjonskrav_id_fkey to utbetaling_deltakelse_manedsverk_utbetaling_id_fkey;
alter table refusjonskrav_deltakelse_periode rename constraint refusjonskrav_deltakelse_periode_refusjonskrav_id_fkey to utbetaling_deltakelse_periode_utbetaling_id_fkey;
alter table refusjonskrav rename constraint refusjonskrav_gjennomforing_id_fkey to utbetaling_gjennomforing_id_fkey;
alter table tilsagn_utbetaling rename constraint tilsagn_utbetaling_refusjonskrav_id_fkey to tilsagn_utbetaling_utbetaling_id_fkey;

-- rename tables
alter table refusjonskrav_deltakelse_manedsverk rename to utbetaling_deltakelse_manedsverk;
alter table refusjonskrav_deltakelse_periode rename to utbetaling_deltakelse_periode;
alter table refusjonskrav rename to utbetaling;
alter table refusjonskrav_beregning_aft rename to utbetaling_beregning_aft;

-- rename enums
alter type refusjonskrav_status rename to utbetaling_status;
