-- rename constraints
alter table gjennomforing_amo_kategorisering rename constraint tiltaksgjennomforing_amo_kategorisering_pkey to gjennomforing_amo_kategorisering_pkey;
alter table gjennomforing_amo_kategorisering_sertifisering rename constraint tiltaksgjennomforing_amo_kategorisering_sertifisering_pkey to gjennomforing_amo_kategorisering_sertifisering_pkey;
alter table gjennomforing_administrator rename constraint tiltaksgjennomforing_ansvarlig_pkey to gjennomforing_ansvarlig_pkey;
alter table gjennomforing_arrangor_kontaktperson rename constraint tiltaksgjennomforing_arrangor_kontaktperson_pkey to gjennomforing_arrangor_kontaktperson_pkey;
alter table gjennomforing_nav_enhet rename constraint tiltaksgjennomforing_enhet_pkey to gjennomforing_enhet_pkey;
alter table gjennomforing rename constraint tiltaksgjennomforing_lopenummer_key to gjennomforing_lopenummer_key;
alter table gjennomforing rename constraint tiltaksgjennomforing_pkey to gjennomforing_pkey;
alter table gjennomforing_utdanningsprogram rename constraint tiltaksgjennomforing_utdanningsprogram_pkey to gjennomforing_utdanningsprogram_pkey;
alter table gjennomforing_amo_kategorisering_sertifisering rename constraint tiltaksgjennomforing_amo_kategorisering_sertifi_konsept_id_fkey to gjennomforing_amo_kategorisering_sertifi_konsept_id_fkey;
alter table gjennomforing rename constraint tiltaksgjennomforing_arrangor_id_fkey to gjennomforing_arrangor_id_fkey;
alter table gjennomforing rename constraint tiltaksgjennomforing_avtale_id_fkey to gjennomforing_avtale_id_fkey;
alter table gjennomforing rename constraint tiltaksgjennomforing_nav_region_fkey to gjennomforing_nav_region_fkey;
alter table gjennomforing_utdanningsprogram rename constraint utdanning_programomrade_tiltaksgjennomfor_programomrade_id_fkey to utdanning_programomrade_gjennomfor_programomrade_id_fkey;
alter table gjennomforing_utdanningsprogram rename constraint utdanning_programomrade_tiltaksgjennomforing_utdanning_id_fkey to utdanning_programomrade_gjennomforing_utdanning_id_fkey;
