export const avtaletekster = {
  avtalenavnLabel: "Avtalenavn",
  avtalenummerLabel: "Avtalenummer",
  tiltakstypeLabel: "Tiltakstype",
  avtaletypeLabel: "Avtaletype",
  startdatoLabel: "Startdato",
  sluttdatoLabel: "Sluttdato",
  prisOgBetalingLabel: "Pris- og betalingsbetingelser",
  administratorerForAvtalenLabel: "Administratorer for avtalen",
  ingenAdministratorerSattLabel: "Ingen administratorer satt for avtalen",
  seOriginalavtaleLabel: "Se originalavtale",
  urlAvtaleWebsaklabel: "URl til avtale i Websak",
  fylkessamarbeidLabel: "Fylkessamarbeid",
  navRegionerLabel: "NAV-regioner",
  navEnheterLabel: "NAV-enheter (kontorer)",
  ansvarligEnhetFraArenaLabel: "Ansvarlig enhet fra Arena",
  tiltaksarrangorHovedenhetLabel: "Tiltaksarrangør hovedenhet",
  tiltaksarrangorUnderenheterLabel: "Tiltaksarrangør underenheter",
  kontaktpersonHosTiltaksarrangorLabel: "Kontaktperson hos tiltaksarrangør",
} as const;
