export const gjennomforingTekster = {
  tiltaksnavnLabel: "Tiltaksnavn",
  tiltaksnummerLabel: "Tiltaksnummer i Arena",
  avtaleLabel: "Avtale",
  avtaleMedTiltakstype: (tiltakstype: string) => `Avtale (tiltakstype: ${tiltakstype})`,
  ingenAvtaleForGjennomforingenLabel: "Ingen avtale for gjennomføringen",
  tiltakstypeLabel: "Tiltakstype",
  oppstartstypeLabel: "Oppstartstype",
  avtaleStartdatoLabel: "Avtalens startdato",
  avtaleSluttdatoLabel: "Avtalens sluttdato",
  startdatoLabel: "Startdato",
  sluttdatoLabel: "Sluttdato",
  antallPlasserLabel: "Antall plasser",
  deltidsprosentLabel: "Deltidsprosent",
  apentForPameldingLabel: "Åpent for påmelding",
  estimertVentetidLabel: "Estimert ventetid",
  administratorerForGjennomforingenLabel: "Administratorer for gjennomføringen",
  ingenAdministratorerSattForGjennomforingenLabel: "Ingen administratorer satt for gjennomføringen",
  tilgjengeligIModiaLabel: "Tilgjengelig i Modia for:",
  navEnheterKontorerLabel: "Nav-enheter (kontorer)",
  navEnheterKontorerTooltip:
    "Bestemmer hvem gjennomføringen skal vises til i Modia, basert på hvilken oppfølgingsenhet brukeren har tilhørighet til.",
  navEnheterAndreLabel: "Nav-enheter (andre)",
  navEnheterAndreTooltip:
    "Bestemmer hvilke andre Nav-enheter (spesialenheter, etc.) som gjennomføringen skal kunne vises for i Modia. Det er ofte ikke behov for å velge noen av disse, men det finnes unntak der dette kan være aktuelt. Dette kan velges hvis tiltaket kun er tilgjengelig for brukere ved en spesiell oppfølgingsenhet (f.eks. egne ansatte), eller om tiltaket kun er relevant for brukergrupper som følges opp av ansatte ved andre spesialenheter som ikke nødvendigvis er kategorisert som en oppfølgingsenhet.",
  ansvarligEnhetFraArenaLabel: "Ansvarlig enhet fra Arena",
  kontaktpersonNav: {
    navnLabel: "Nav ansatt",
    omradeLabel: "Område",
    beskrivelseLabel: "Beskrivelse",
  },
  tiltaksarrangorHovedenhetLabel: "Tiltaksarrangør hovedenhet",
  tiltaksarrangorUnderenhetLabel: "Tiltaksarrangør underenhet",
  kontaktpersonerHosTiltaksarrangorLabel: "Kontaktpersoner hos tiltaksarrangør",
  stedForGjennomforingLabel: "Sted for gjennomføring",
  kurstypeLabel: "Kurstype",
  forerkortLabel: "Førerkort",
  sertifiseringerLabel: "Sertifiseringer",
  norskproveLabel: "Norskprøve",
  innholdElementerLabel: "Elementer i kurset",
  amoKategoriseringMangler: "Du må velge kurstype for avtalen",
} as const;
