package no.nav.mulighetsrommet.database.kotest.extensions

import io.kotest.core.listeners.AfterSpecListener
import io.kotest.core.listeners.BeforeSpecListener
import io.kotest.core.spec.Spec
import io.kotest.core.test.TestCaseOrder
import kotliquery.TransactionalSession
import kotliquery.queryOf
import no.nav.mulighetsrommet.api.ApplicationConfigTest
import no.nav.mulighetsrommet.api.KafkaTopics
import no.nav.mulighetsrommet.api.TransactionalQueryContext
import no.nav.mulighetsrommet.api.application.ApiDatabase
import no.nav.mulighetsrommet.api.persistence.OutboxTopics
import no.nav.mulighetsrommet.api.persistence.SqlApiDatabase
import no.nav.mulighetsrommet.database.Database
import no.nav.mulighetsrommet.database.DatabaseConfig
import no.nav.mulighetsrommet.database.FlywayMigrationManager
import org.assertj.db.api.Assertions
import org.assertj.db.api.TableAssert
import org.assertj.db.type.AssertDbConnectionFactory
import no.nav.mulighetsrommet.api.ApiDatabase as LegacyApiDatabase

class ApiDatabaseTestListener(
    private val config: DatabaseConfig = ApplicationConfigTest.database,
) : BeforeSpecListener, AfterSpecListener {
    private var delegate: Database? = null

    private val flywayMigration: FlywayMigrationManager = FlywayMigrationManager(
        config = FlywayMigrationManager.MigrationConfig(cleanDisabled = false),
        slackNotifier = null,
    )

    val db: LegacyApiDatabase
        get() {
            return delegate
                ?.let { LegacyApiDatabase(it, ApplicationConfigTest.kafka.topics) }
                ?: throw RuntimeException("Database has not yet been initialized")
        }

    val newDb: ApiDatabase
        get() {
            return delegate
                ?.let { SqlApiDatabase(it, ApplicationConfigTest.kafka.topics.toOutboxTopics()) }
                ?: throw RuntimeException("Database has not yet been initialized")
        }

    override suspend fun beforeSpec(spec: Spec) {
        // It's not optimal to force a sequential test order, but since tests (for now) all share the same database
        // instance they can't be run in parallel
        spec.testCaseOrder = TestCaseOrder.Sequential

        delegate = Database(config)

        flywayMigration.migrate(db.db)
    }

    override suspend fun afterSpec(spec: Spec) {
        truncateAll()
        delegate?.close()
    }

    fun assertTable(tableName: String): TableAssert {
        val connection = AssertDbConnectionFactory.of(db.getDatasource()).create()
        val table = connection.table(tableName).build()
        return Assertions.assertThat(table)
    }

    inline fun <T> run(block: TransactionalQueryContext.(TransactionalSession) -> T): T = db.transaction {
        block(session)
    }

    inline fun <T> runAndRollback(block: TransactionalQueryContext.() -> T): T = db.db.session { s ->
        try {
            s.connection.begin()
            s.transactional = true
            val tx = TransactionalSession(s.connection, s.returnGeneratedKeys, s.autoGeneratedKeys, s.strict)
            val context = TransactionalQueryContext(tx, ApplicationConfigTest.kafka.topics)
            return block.invoke(context)
        } finally {
            s.connection.rollback()
            s.transactional = false
            s.close()
        }
    }

    fun truncateAll(): Unit = db.db.session { session ->
        val excludedTables = setOf(
            "flyway_schema_history",
            "deltaker_registrering_innholdselement",
            "kostnadssted",
            "endringshistorikk_type",
            "nav_ansatt_rolle_type",
            "utbetaling_blokkering_type",
            "utbetaling_status_type",
            "utbetaling_linje_status_type",
            "tilsagn_type",
            "tilsagn_status_type",
            "vedtak_resultat",
            "tilskudd_opplaering",
            "tilskudd_behandling_status",
            "totrinnskontroll_type",
            "totrinnskontroll_status_type",
            "personopplysning",
        )

        val tableNames = session
            .list(queryOf("SELECT table_name FROM information_schema.tables WHERE table_schema='public' AND table_type='BASE TABLE'")) {
                it.string("table_name")
            }
        tableNames
            .filter { it !in excludedTables }
            .forEach {
                session.execute(queryOf("truncate table $it restart identity cascade"))
            }
    }
}

private fun KafkaTopics.toOutboxTopics(): OutboxTopics {
    return OutboxTopics(sisteTiltakstyperTopic)
}
