package no.nav.mulighetsrommet.database.kotest.extensions

import io.kotest.core.listeners.AfterSpecListener
import io.kotest.core.listeners.BeforeSpecListener
import io.kotest.core.spec.Spec
import io.kotest.core.test.TestCaseOrder
import kotliquery.TransactionalSession
import no.nav.mulighetsrommet.admin.AdminDatabase
import no.nav.mulighetsrommet.api.ApiDatabase
import no.nav.mulighetsrommet.api.ApplicationConfigTest
import no.nav.mulighetsrommet.api.KafkaTopics
import no.nav.mulighetsrommet.api.TransactionalQueryContext
import no.nav.mulighetsrommet.api.persistence.OutboxTopics
import no.nav.mulighetsrommet.api.persistence.SqlAdminDatabase
import no.nav.mulighetsrommet.api.persistence.truncateTablesWithDynamicData
import no.nav.mulighetsrommet.database.Database
import no.nav.mulighetsrommet.database.DatabaseConfig
import no.nav.mulighetsrommet.database.FlywayMigrationManager
import org.assertj.db.api.Assertions
import org.assertj.db.api.TableAssert
import org.assertj.db.type.AssertDbConnectionFactory

class ApiDatabaseTestListener(
    private val config: DatabaseConfig = ApplicationConfigTest.database,
) : BeforeSpecListener, AfterSpecListener {
    private var delegate: Database? = null

    private val flywayMigration: FlywayMigrationManager = FlywayMigrationManager(
        config = FlywayMigrationManager.MigrationConfig(cleanDisabled = false),
        slackNotifier = null,
    )

    val db: ApiDatabase
        get() {
            return delegate
                ?.let { ApiDatabase(it, ApplicationConfigTest.kafka.topics) }
                ?: throw RuntimeException("Database has not yet been initialized")
        }

    val newDb: AdminDatabase
        get() {
            return delegate
                ?.let { SqlAdminDatabase(it, ApplicationConfigTest.kafka.topics.toOutboxTopics()) }
                ?: throw RuntimeException("Database has not yet been initialized")
        }

    override suspend fun beforeSpec(spec: Spec) {
        // It's not optimal to force a sequential test order, but since tests (for now) all share the same database
        // instance they can't be run in parallel
        spec.testCaseOrder = TestCaseOrder.Sequential

        delegate = Database(config)

        flywayMigration.migrate(db.db)
    }

    override suspend fun afterSpec(spec: Spec) {
        truncateAll()
        delegate?.close()
    }

    fun assertTable(tableName: String): TableAssert {
        val connection = AssertDbConnectionFactory.of(db.getDatasource()).create()
        val table = connection.table(tableName).build()
        return Assertions.assertThat(table)
    }

    inline fun <T> run(block: TransactionalQueryContext.(TransactionalSession) -> T): T = db.transaction {
        block(session)
    }

    inline fun <T> runAndRollback(block: TransactionalQueryContext.() -> T): T = db.db.session { s ->
        try {
            s.connection.begin()
            s.transactional = true
            val tx = TransactionalSession(s.connection, s.returnGeneratedKeys, s.autoGeneratedKeys, s.strict)
            val context = TransactionalQueryContext(tx, ApplicationConfigTest.kafka.topics)
            return block.invoke(context)
        } finally {
            s.connection.rollback()
            s.transactional = false
            s.close()
        }
    }

    fun truncateAll(): Unit = db.db.session { session ->
        truncateTablesWithDynamicData(session)
    }
}

private fun KafkaTopics.toOutboxTopics(): OutboxTopics {
    return OutboxTopics(sisteTiltakstyperTopic, totrinnskontrollTopic)
}
