apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: arrangor-flate
    namespace: team-mulighetsrommet
    labels:
        team: team-mulighetsrommet
spec:
    # prettier-ignore
    image: {{ image }}
    port: 3000
    replicas:
        min: 1
    resources:
        requests:
            cpu: 50m
    ingresses:
        - https://arrangor-refusjon.intern.dev.nav.no
    prometheus:
        enabled: true
        path: /metrics
    liveness:
        initialDelay: 20
        path: /internal/isAlive
    readiness:
        initialDelay: 20
        path: /internal/isReady
    accessPolicy:
        outbound:
            rules:
                - application: nav-dekoratoren
                  namespace: personbruker
    tokenx:
        enabled: false # TODO Enable tokenx
    idporten:
        enabled: false # TODO Enable idporten
        sidecar:
            enabled: false # TODO Enable sidecar for idporten
            level: Level4
            autoLogin: false
            autoLoginIgnorePaths:
                - /internal/*
