kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: tiltakshistorikk
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
spec:
  image: "{{image}}"
  port: 8080
  ingresses:
    - https://mulighetsrommet-tiltakshistorikk.intern.dev.nav.no
  replicas:
    min: 1
    max: 2
    scalingStrategy:
      cpu:
        thresholdPercentage: 75
  resources:
    requests:
      cpu: 50m
      memory: 512Mi
    limits:
      memory: 8192Mi
  liveness:
    path: /internal/liveness
    initialDelay: 20
  readiness:
    path: /internal/readiness
    initialDelay: 20
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  secureLogs:
    enabled: true
  prometheus:
    enabled: true
    path: /internal/prometheus
  kafka:
    pool: nav-dev
  gcp:
    sqlInstances:
      - name: tiltakshistorikk-v1
        type: POSTGRES_17
        tier: db-f1-micro
        diskAutoresize: true
        databases:
          - name: tiltakshistorikk
            envVarPrefix: DB
        flags:
          - name: max_connections
            value: "200"
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: 639e2806-4cc2-484c-a72a-51b4308c52a1 # team-mulighetsrommet
        extra:
          - azp_name
  accessPolicy:
    inbound:
      rules:
        - application: mulighetsrommet-api
        - application: mulighetsrommet-arena-adapter
        - application: mulighetsrommet-arena-adapter-manager
    outbound:
      rules:
        - application: tiltak-datadeling
          namespace: team-tiltak
