kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: tiltakshistorikk
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
spec:
  image: "{{image}}"
  port: 8080
  ingresses:
    - https://mulighetsrommet-tiltakshistorikk.intern.nav.no
  secureLogs:
    enabled: true
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/readiness
    initialDelay: 20
  liveness:
    path: /internal/liveness
    initialDelay: 20
  replicas:
    min: 2
    max: 4
    scalingStrategy:
      cpu:
        thresholdPercentage: 75
  resources:
    requests:
      cpu: 50m
      memory: 512Mi
    limits:
      memory: 8192Mi
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  gcp:
    sqlInstances:
      - name: tiltakshistorikk-v1
        type: POSTGRES_17
        tier: db-custom-1-3840
        diskAutoresize: true
        pointInTimeRecovery: false
        databases:
          - name: tiltakshistorikk
            envVarPrefix: DB
        flags:
          - name: max_connections
            value: "200"
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: debefa6e-1865-446d-b22b-9579fc735de3 # team-mulighetsrommet
        extra:
          - azp_name
  kafka:
    pool: nav-prod
  accessPolicy:
    inbound:
      rules:
        - application: mulighetsrommet-api
        - application: mulighetsrommet-arena-adapter
