apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  name: bq-tiltakstype-view
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/project-id: {{ project }}
    cnrm.cloud.google.com/state-into-spec: merge

spec:
  resourceID: tiltakstyper
  description: "Dataprodukt som viser tiltakstyper med navn, tiltakskode og om tiltakstypen gir rett til tiltakspenger"
  datasetRef:
    external: datastream_mulighetsrommet_api_db
  view:
    useLegacySql: false
    query: >-
      SELECT
        id,
        navn,
        tiltakskode,
        rett_paa_tiltakspenger
      FROM public_tiltakstype
