apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  name: bq-tiltaksgjennomforing-opphav-antall-opprettet-view
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/project-id: {{project}}
    cnrm.cloud.google.com/state-into-spec: merge

spec:
  resourceID: tiltaksgjennomforing_opphav_antall_opprettet_view # Navn på viewet uttad
  description: "Dataprodukt som viser hvor mange tiltaksgjennomføringer som er opprettet gruppert på opphav"
  datasetRef:
    external: datastream_mulighetsrommet_api_db
  view:
    useLegacySql: false
    query: >-
      select tiltakstype.navn, opphav, count(*) as antall_opprettet
      from tiltaksgjennomforing
               join tiltakstype on tiltaksgjennomforing.tiltakstype_id = tiltakstype.id
      group by opphav, tiltakstype.navn
      order by navn
