apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  name: bq-tiltakstype-view
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/project-id: {{project}}
    cnrm.cloud.google.com/state-into-spec: merge

spec:
  resourceID: tiltakstype_view # Navn på viewet uttad
  description: "Dataprodukt for tiltakstyper som eies av Team Valp og Team Komet"
  datasetRef:
    external: datastream_mulighetsrommet_api_db
  view:
    useLegacySql: false
    query: >-
      SELECT
        id,
        navn,
        tiltakskode,
        arena_kode as arena_tiltakskode
      FROM datastream_mulighetsrommet_api_db.public_tiltakstype
      WHERE tiltakskode is not null
