package no.nav.mulighetsrommet.api.persistence

import io.kotest.core.listeners.AfterSpecListener
import io.kotest.core.listeners.BeforeSpecListener
import io.kotest.core.spec.Spec
import io.kotest.core.test.TestCaseOrder
import kotliquery.TransactionalSession
import kotliquery.queryOf
import no.nav.mulighetsrommet.api.application.ApiDatabase
import no.nav.mulighetsrommet.api.application.QueryContext
import no.nav.mulighetsrommet.database.Database
import no.nav.mulighetsrommet.database.FlywayMigrationManager
import org.assertj.db.api.Assertions
import org.assertj.db.api.TableAssert
import org.assertj.db.type.AssertDbConnectionFactory

class SqlApiDatabaseTestListener : BeforeSpecListener, AfterSpecListener {

    private var delegate: Database? = null

    private val flywayMigration: FlywayMigrationManager = FlywayMigrationManager(
        config = FlywayMigrationManager.MigrationConfig(cleanDisabled = false),
        slackNotifier = null,
    )

    val db: ApiDatabase
        get() = delegate?.let { SqlApiDatabase(it, outboxConfig) }
            ?: throw RuntimeException("Database has not yet been initialized")

    override suspend fun beforeSpec(spec: Spec) {
        spec.testCaseOrder = TestCaseOrder.Sequential
        delegate = Database(databaseConfig)
        flywayMigration.migrate(delegate!!)
    }

    override suspend fun afterSpec(spec: Spec) {
        truncateAll()
        delegate?.close()
    }

    fun assertTable(tableName: String): TableAssert {
        val connection = AssertDbConnectionFactory.of(delegate!!.getDatasource()).create()
        val table = connection.table(tableName).build()
        return Assertions.assertThat(table)
    }

    fun <T> run(block: QueryContext.() -> T): T = db.transaction {
        block()
    }

    fun <T> runAndRollback(block: QueryContext.() -> T): T = delegate!!.session { s ->
        try {
            s.connection.begin()
            s.transactional = true
            val tx = TransactionalSession(s.connection, s.returnGeneratedKeys, s.autoGeneratedKeys, s.strict)
            return SqlQueryContext(tx, outboxConfig).block()
        } finally {
            s.connection.rollback()
            s.transactional = false
            s.close()
        }
    }

    fun truncateAll(): Unit = delegate!!.session { session ->
        val excludedTables = setOf(
            "flyway_schema_history",
            "kostnadssted",
            "endringshistorikk_type",
            "nav_ansatt_rolle_type",
            "utbetaling_blokkering_type",
            "utbetaling_status_type",
            "utbetaling_linje_status_type",
            "tilsagn_type",
            "tilsagn_status_type",
            "vedtak_resultat",
            "tilskudd_opplaering",
            "tilskudd_behandling_status",
            "totrinnskontroll_type",
            "personopplysning",
        )

        val tableNames = session.list(
            queryOf("SELECT table_name FROM information_schema.tables WHERE table_schema='public' AND table_type='BASE TABLE'"),
        ) {
            it.string("table_name")
        }

        tableNames.filter { it !in excludedTables }.forEach {
            session.execute(queryOf("truncate table $it restart identity cascade"))
        }
    }
}
