package no.nav.mulighetsrommet.api.persistence

import io.kotest.core.listeners.AfterSpecListener
import io.kotest.core.listeners.BeforeSpecListener
import io.kotest.core.spec.Spec
import io.kotest.core.test.TestCaseOrder
import kotliquery.TransactionalSession
import no.nav.mulighetsrommet.database.Database
import no.nav.mulighetsrommet.database.FlywayMigrationManager

class SqlAdminDatabaseTestListener : BeforeSpecListener, AfterSpecListener {

    @PublishedApi
    internal var delegate: Database? = null

    private val flywayMigration: FlywayMigrationManager = FlywayMigrationManager(
        config = FlywayMigrationManager.MigrationConfig(cleanDisabled = false),
        slackNotifier = null,
    )

    override suspend fun beforeSpec(spec: Spec) {
        spec.testCaseOrder = TestCaseOrder.Sequential
        delegate = Database(databaseConfig)
        flywayMigration.migrate(delegate!!)
    }

    override suspend fun afterSpec(spec: Spec) {
        truncateAll()
        delegate?.close()
    }

    inline fun <T> run(block: SqlQueryContext.() -> T): T = delegate!!.transaction {
        SqlQueryContext(it, outboxConfig).block()
    }

    inline fun <T> runAndRollback(block: SqlQueryContext.() -> T): T = delegate!!.session { s ->
        try {
            s.connection.begin()
            s.transactional = true
            val tx = TransactionalSession(s.connection, s.returnGeneratedKeys, s.autoGeneratedKeys, s.strict)
            return SqlQueryContext(tx, outboxConfig).block()
        } finally {
            s.connection.rollback()
            s.transactional = false
            s.close()
        }
    }

    fun truncateAll(): Unit = delegate!!.session { session ->
        truncateTablesWithDynamicData(session)
    }
}
