kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: mulighetsrommet-kafka-manager
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/poao/kafka-manager:2024.02.22-13.54-8f3d052
  port: 8080
  webproxy: true
  ingresses:
    - https://mulighetsrommet-kafka-manager.intern.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 1 # 1 instance is required since in-memory session management is used
    scalingStrategy:
      cpu:
        thresholdPercentage: 75
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  secureLogs:
    enabled: true
  kafka: # Optional. Required for Aiven
    pool: nav-prod
  azure: # Required
    application:
      enabled: true
      tenant: nav.no
      claims:
        groups:
          - id: debefa6e-1865-446d-b22b-9579fc735de3 # team-mulighetsrommet
  env:
    - name: APP_CONFIG_JSON # Required
      value: >
        {
          "topics": [
            {
              "name": "teamarenanais.aapen-arena-tiltakgjennomforingendret-v1-p",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "teamarenanais.aapen-arena-tiltakdeltakerendret-v1-p",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "teamarenanais.aapen-arena-tiltakendret-v1-p",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "teamarenanais.aapen-arena-tiltakssakendret-v1-p",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "teamarenanais.aapen-arena-avtaleinfoendret-v1-p",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "team-mulighetsrommet.siste-tiltaksgjennomforinger-v1",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
             {
              "name": "team-mulighetsrommet.siste-tiltakstyper-v1",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "team-mulighetsrommet.arena-migrering-tiltaksgjennomforinger-v1",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "pto.siste-oppfolgingsperiode-v1",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "amt.deltaker-v1",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            }
          ]
        }
