kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: mulighetsrommet-kafka-manager
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/poao/kafka-manager:2025.03.17-10.29-b41c15c
  port: 8080
  webproxy: true
  ingresses:
    - https://mulighetsrommet-kafka-manager.intern.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 1 # 1 instance is required since in-memory session management is used
    scalingStrategy:
      cpu:
        thresholdPercentage: 75
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 1m
      memory: 512Mi
  secureLogs:
    enabled: true
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        groups:
          # team-mulighetsrommet
          - id: "debefa6e-1865-446d-b22b-9579fc735de3"
  env:
    - name: APP_CONFIG_JSON
      value: >
        {
          "topics": [
            {
              "name": "teamarenanais.aapen-arena-tiltakgjennomforingendret-v1-p",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "teamarenanais.aapen-arena-tiltakdeltakerendret-v1-p",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "teamarenanais.aapen-arena-tiltakendret-v1-p",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "teamarenanais.aapen-arena-tiltakssakendret-v1-p",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "teamarenanais.aapen-arena-avtaleinfoendret-v1-p",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "team-mulighetsrommet.siste-tiltaksgjennomforinger-v1",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "teamarenanais.aapen-arena-histtiltakdeltakerendret-v1-p",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "team-mulighetsrommet.siste-tiltakstyper-v2",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "team-mulighetsrommet.siste-tiltakstyper-v3",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "team-mulighetsrommet.datavarehus-tiltak-v1",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "team-mulighetsrommet.arena-migrering-tiltaksgjennomforinger-v1",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "team-mulighetsrommet.tiltaksokonomi.bestillinger-v1",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "team-mulighetsrommet.tiltaksokonomi.bestilling-status-v1",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "team-mulighetsrommet.tiltaksokonomi.faktura-status-v1",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
           {
              "name": "amt.tiltakskoordinators-deltakerliste-v1",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            }
          ]
        }
