package no.nav.mulighetsrommet.api.navansatt.model

enum class NavAnsattRolle {
    TEAM_MULIGHETSROMMET,
    KONTAKTPERSON,
    TILTAKSGJENNOMFORINGER_SKRIV,
    AVTALER_SKRIV,
    TILTAKADMINISTRASJON_GENERELL,
    TILTAKADMINISTRASJON_ENDRINGSMELDING,
    OKONOMI_BESLUTTER,
}
