package no.nav.mulighetsrommet.api.navansatt.model

enum class Rolle {
    TEAM_MULIGHETSROMMET,
    KONTAKTPERSON,
    TILTAKADMINISTRASJON_GENERELL,
    TILTAKADMINISTRASJON_ENDRINGSMELDING,
    TILTAKSGJENNOMFORINGER_SKRIV,
    AVTALER_SKRIV,
    SAKSBEHANDLER_OKONOMI,
    BESLUTTER_TILSAGN,
    ATTESTANT_UTBETALING,
}
