kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: tiltaksokonomi
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
spec:
  image: "{{image}}"
  port: 8080
  ingresses:
    - https://mulighetsrommet-tiltaksokonomi.intern.dev.nav.no
  secureLogs:
    enabled: true
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/readiness
    initialDelay: 20
  liveness:
    path: /internal/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 2
    scalingStrategy:
      cpu:
        thresholdPercentage: 75
  resources:
    requests:
      cpu: 50m
      memory: 512Mi
    limits:
      memory: 8192Mi
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  gcp:
    sqlInstances:
      - name: tiltaksokonomi-v1
        type: POSTGRES_17
        tier: db-f1-micro
        diskAutoresize: true
        databases:
          - name: tiltaksokonomi
            envVarPrefix: DB
        flags:
          - name: max_connections
            value: "200"
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: 639e2806-4cc2-484c-a72a-51b4308c52a1 # team-mulighetsrommet
        extra:
          - azp_name
  kafka:
    pool: nav-dev
  accessPolicy:
    inbound:
      rules:
        - application: mulighetsrommet-arena-adapter-manager
        - application: oebs-po-ap-api-q1
          namespace: team-oebs
          cluster: dev-fss
          permissions:
            roles:
              - oebs-api
    outbound:
      external:
        - host: data.brreg.no
        - host: oebs-po-ap-api-q1.dev-fss-pub.nais.io
