kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: tiltaksokonomi
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
spec:
  image: "{{image}}"
  port: 8080
  ingresses:
    - https://mulighetsrommet-tiltaksokonomi.intern.nav.no
  replicas:
    min: 2
    max: 4
    scalingStrategy:
      cpu:
        thresholdPercentage: 75
  resources:
    requests:
      cpu: 50m
      memory: 512Mi
    limits:
      memory: 8192Mi
  liveness:
    path: /internal/liveness
    initialDelay: 20
  readiness:
    path: /internal/readiness
    initialDelay: 20
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  secureLogs:
    enabled: true
  prometheus:
    enabled: true
    path: /internal/prometheus
  kafka:
    pool: nav-prod
  gcp:
    sqlInstances:
      - name: tiltaksokonomi-v1
        type: POSTGRES_17
        tier: db-custom-1-3840
        diskAutoresize: true
        pointInTimeRecovery: true
        databases:
          - name: tiltaksokonomi
            envVarPrefix: DB
        flags:
          - name: max_connections
            value: "200"
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          # team-mulighetsrommet
          - id: "debefa6e-1865-446d-b22b-9579fc735de3"
        extra:
          - azp_name
  accessPolicy:
    inbound:
      rules:
        - application: mulighetsrommet-arena-adapter-manager
        - application: oebs-po-ap-api
          namespace: team-oebs
          cluster: prod-fss
          permissions:
            roles:
              - oebs-api
    outbound:
      external:
        - host: data.brreg.no
        - host: oebs-po-ap-api.prod-fss-pub.nais.io
