server:
  port: 8084
  host: 0.0.0.0

app:
  services:
    mulighetsrommetApi:
      url: https://mulighetsrommet-api.intern.nav.no
      scope: api://prod-gcp.team-mulighetsrommet.mulighetsrommet-api/.default

  database:
    host: ${DB_HOST}
    port: ${DB_PORT}
    name: ${DB_DATABASE}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    maximumPoolSize: 10

  enableFailedRecordProcessor: true

  kafka:
    brokers: ${KAFKA_BROKERS}
    consumerGroupId: mulighetsrommet-kafka-consumer.v1
    topics:
      pollChangesDelayMs: 10000
      consumer:
        tiltakendret: teamarenanais.aapen-arena-tiltakendret-v1-p
        tiltakgjennomforingendret: teamarenanais.aapen-arena-tiltakgjennomforingendret-v1-p
        tiltakdeltakerendret: teamarenanais.aapen-arena-tiltakdeltakerendret-v1-p
        sakendret: teamarenanais.aapen-arena-sakendret-v1-p
