server:
  port: 8084
  host: 0.0.0.0

app:
  database:
    jdbcUrl: jdbc:postgresql://localhost:5442/mr-arena-adapter?user=valp&password=valp
    maximumPoolSize: 10

  services:
    mulighetsrommetApi:
      url: http://localhost:8080
      scope: default
    tiltakshistorikk:
      url: http://localhost:8080
      scope: default
    arenaEventService:
      channelCapacity: 100
      numChannelConsumers: 10
      maxRetries: 5
    arenaOrdsProxy:
      url: http://localhost:8090/arena-ords-proxy
      scope: default

  tasks:
    retryFailedEvents:
      delayOfMinutes: 1

    notifyFailedEvents:
      maxRetries: 5
      cron: '0 0 7 * * MON-FRI'

  enableFailedRecordProcessor: true

  auth:
    azure:
      issuer: http://localhost:8081/azure
      jwksUri: http://localhost:8081/azure/jwks
      audience: mulighetsrommet-api
      tokenEndpointUrl: http://localhost:8081/azure/token

  kafka:
    brokerUrl: localhost:29092
    consumerGroupId: mulighetsrommet-kafka-consumer.v1
    consumers:
      arenaTiltakEndret:
        id: arena-tiltakstype-endret
        topic: tiltak-endret
      arenaTiltakgjennomforingEndret:
        id: arena-tiltakgjennomforing-endret
        topic: tiltakgjennomforingendret
      arenaTiltakdeltakerEndret:
        id: arena-tiltakdeltaker-endret
        topic: tiltakdeltakerendret
      arenaHistTiltakdeltakerEndret:
        id: arena-hist-tiltakdeltaker-endret
        topic: histtiltakdeltakerendret
      arenaSakEndret:
        id: arena-sakendret-endret
        topic: sakendret
      arenaAvtaleInfoEndret:
        id: arena-avtaleinfo-endret
        topic: avtaleinfoendret

  slack:
    token: ${SLACK_TOKEN:-}
    channel: "#team-valp-monitoring"
    enable: false
