server:
  port: 8084
  host: 0.0.0.0

app:
  endpoints:
    mulighetsrommetApi: ${MR_API_URI:-http://localhost:8080}
  database:
    host: ${DB_HOST:-localhost}
    port: ${DB_PORT:-5443}
    name: ${DB_DATABASE:-mulighetsrommet-arena-adapter-db}
    user: ${DB_USERNAME:-valp}
    password: ${DB_PASSWORD:-valp}
  kafka:
    brokers: ${KAFKA_BROKERS:-localhost:29092}
    consumerGroupId: mulighetsrommet-kafka-consumer.v1
    topics:
      consumer:
        tiltakendret: ${MR_KAFKA_TOPIC_TILTAKENDRET:-tiltakendret}
        tiltakgjennomforingendret: ${MR_KAFKA_TOPIC_TILTAKGJENNOMFORINGENDRET:-tiltakgjennomforingendret}
        tiltakdeltakerendret: ${MR_KAFKA_TOPIC_TILTAKDELTAKERENDRET:-tiltakdeltakerendret}
