server:
  port: 8084
  host: 0.0.0.0

app:
  database:
    host: localhost
    port: 5443
    name: mulighetsrommet-arena-adapter-db
    user: valp
    password: valp
    maximumPoolSize: 10

  services:
    mulighetsrommetApi:
      url: http://localhost:8080
      scope: default
    arenaEventService:
      channelCapacity: 100
      numChannelConsumers: 10
      maxRetries: 5
    arenaOrdsProxy:
      url: http://localhost:8090/arena-ords-proxy
      scope: default

  tasks:
    retryFailedEvents:
      delayOfMinutes: 1

  enableFailedRecordProcessor: true

  auth:
    azure:
      issuer: http://localhost:8081/azure
      jwksUri: http://localhost:8081/azure/jwks
      audience: mulighetsrommet-api
      tokenEndpointUrl: http://localhost:8081/azure/token

  kafka:
    brokerUrl: localhost:29092
    consumerGroupId: mulighetsrommet-kafka-consumer.v1
    topics:
      topicStatePollDelay: 10000
      consumer:
        tiltakendret: tiltakendret
        tiltakgjennomforingendret: tiltakgjennomforingendret
        tiltakdeltakerendret: tiltakdeltakerendret
        sakendret: sakendret
        avtaleinfoendret: avtaleinfoendret

  slack:
    token: ${SLACK_TOKEN:-""}
    channel: "#team-valp-monitoring"
    enable: false
