server:
  port: 8084
  host: 0.0.0.0

app:
  database:
    jdbcUrl: ${DB_JDBC_URL}
    maximumPoolSize: 20

  services:
    mulighetsrommetApi:
      url: http://mulighetsrommet-api
      scope: api://prod-gcp.team-mulighetsrommet.mulighetsrommet-api/.default
    arenaEventService:
      channelCapacity: 10000
      numChannelConsumers: 100
      maxRetries: 10
    arenaOrdsProxy:
      url: https://amt-arena-ords-proxy.prod-fss-pub.nais.io/api
      scope: api://prod-fss.amt.amt-arena-ords-proxy/.default

  tasks:
    retryFailedEvents:
      delayOfMinutes: 15

    notifyFailedEvents:
      maxRetries: 10
      cron: '0 0 7 * * MON-FRI'

  enableFailedRecordProcessor: true

  auth:
    azure:
      issuer: ${AZURE_OPENID_CONFIG_ISSUER}
      jwksUri: ${AZURE_OPENID_CONFIG_JWKS_URI}
      audience: ${AZURE_APP_CLIENT_ID}
      tokenEndpointUrl: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}

  kafka:
    consumerGroupId: mulighetsrommet-kafka-consumer.v1
    consumers:
      arenaTiltakEndret:
        id: arena-tiltakstype-endret
        topic: teamarenanais.aapen-arena-tiltakendret-v1-p
      arenaTiltakgjennomforingEndret:
        id: arena-tiltakgjennomforing-endret
        topic: teamarenanais.aapen-arena-tiltakgjennomforingendret-v1-p
      arenaTiltakdeltakerEndret:
        id: arena-tiltakdeltaker-endret
        topic: teamarenanais.aapen-arena-tiltakdeltakerendret-v1-p
      arenaSakEndret:
        id: arena-sakendret-endret
        topic: teamarenanais.aapen-arena-tiltakssakendret-v1-p
      arenaAvtaleInfoEndret:
        id: arena-avtaleinfo-endret
        topic: teamarenanais.aapen-arena-avtaleinfoendret-v1-p

  slack:
    token: ${SLACK_TOKEN}
    channel: "#team-valp-monitoring"
    enable: true
