# Dette er en liste over anbefalte Alerts, kopiert inn fra https://doc.nais.io/observability/alerts/recommended_alerts/
---
apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: "mulighetsrommet-alarmer"
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
spec:
  receivers:
    slack:
      channel: "#team-valp-feil"
  alerts:
    - alert: applikasjon nede
      # Change <appname> to the name of the app you want to monitor
      expr: kube_deployment_status_replicas_available{deployment="mulighetsrommet-api"} == 0
      for: 2m
      description: "App {{ $labels.app }} er nede i namespace {{ $labels.kubernetes_namespace }}"
      action: "`kubectl describe pod -l app={{ $labels.app }} -n {{ $labels.namespace }}` for events, og `kubectl logs -l app={{ $labels.app }} -n {{ $labels.namespace }}` for logger"
    - alert: høy feilrate i logger
      # Change <appname> to the name of the app you want to monitor
      expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="mulighetsrommet-api",log_level=~"Warning|Error"}[3m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="mulighetsrommet-api"}[3m]))) > 10
      for: 3m
      action: "Sjekk loggene til app {{ $labels.log_app }} i namespace {{ $labels.log_namespace }}, for å se hvorfor det er så mye feil"
    - alert: feil i selftest # This alert uses a custom metric provided by https://github.com/navikt/common-java-modules
      # Change <appname> to the name of the app you want to monitor
      expr: selftests_aggregate_result_status{app="mulighetsrommet-api"} > 0
      for: 1m
      action: "Sjekk app {{ $labels.app }} i namespace {{ $labels.kubernetes_namespace }} sine selftest for å se hva som er galt"
    - alert: Høy andel HTTP serverfeil (5xx responser) for mulighetsrommet-api
      severity: danger
      # Change <appname> to the name of the app you want to monitor and <namespace> to the namespace of the app
      expr: (100 * (sum by (backend) (rate(response_total{status_code=~"^5\\d\\d", namespace="team-mulighetsrommet", app="mulighetsrommet-api"}[3m])) / sum by (backend) (rate(response_total{namespace="team-mulighetsrommet", app="mulighetsrommet-api"}[3m])))) > 10
      for: 3m
      action: "Sjekk loggene for å se hvorfor returnerer HTTP feilresponser"
    - alert: Høy andel HTTP klientfeil (4xx responser) for mulighetsrommet-api
      severity: warning
      # Change <appname> to the name of the app you want to monitor and <namespace> to the namespace of the app
      expr: (100 * (sum by (backend) (rate(response_total{status_code=~"4.*", status_code!="409", namespace="team-mulighetsrommet", app="mulighetsrommet-api"}[3m])) / sum by (backend) (rate(response_total{namespace="team-mulighetsrommet", app="mulighetsrommet-api"}[3m])))) > 10
      for: 3m
      action: "Sjekk loggene for å se hvorfor returnerer HTTP feilresponser"
