server:
  port: 8080
  host: 0.0.0.0

app:
  database:
    host: ${DB_HOST}
    port: ${DB_PORT}
    name: ${DB_DATABASE}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    maximumPoolSize: 10
    migrationConfig:
      strategy: Migrate

  kafka:
    producerId: mulighetsrommet-api-kafka-producer.v1
    consumerGroupId: mulighetsrommet-api-kafka-consumer.v1
    producers:
      tiltaksgjennomforinger:
        topic: team-mulighetsrommet.siste-tiltaksgjennomforinger-v1
      tiltakstyper:
        topic: team-mulighetsrommet.siste-tiltakstyper-v1
    consumers:
      amtDeltakerV1:
        id: amt-deltaker
        topic: amt.deltaker-v1
      amtVirksomheterV1:
        id: amt-virksomheter
        topic: amt.virksomheter-v1

  auth:
    azure:
      issuer: ${AZURE_OPENID_CONFIG_ISSUER}
      jwksUri: ${AZURE_OPENID_CONFIG_JWKS_URI}
      audience: ${AZURE_APP_CLIENT_ID}
      tokenEndpointUrl: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}

  sanity:
    dataset: ${SANITY_DATASET}
    projectId: ${SANITY_PROJECT_ID}
    token: ${SANITY_AUTH_TOKEN}

  veilarbvedtaksstotteConfig:
    url: https://veilarbvedtaksstotte.prod-fss-pub.nais.io/veilarbvedtaksstotte/api
    scope: api://prod-fss.pto.veilarbvedtaksstotte/.default

  veilarboppfolgingConfig:
    url: https://veilarboppfolging.prod-fss-pub.nais.io/veilarboppfolging/api
    scope: api://prod-fss.pto.veilarboppfolging/.default

  veilarbpersonConfig:
    url: https://veilarbperson.prod-fss-pub.nais.io/veilarbperson/api
    scope: api://prod-fss.pto.veilarbperson/.default

  veilarbveilederConfig:
    url: https://veilarbveileder.prod-fss-pub.nais.io/veilarbveileder/api
    scope: api://prod-fss.pto.veilarbveileder/.default

  veilarbdialogConfig:
    url: https://veilarbdialog.prod-fss-pub.nais.io/veilarbdialog/api
    scope: api://prod-fss.pto.veilarbdialog/.default

  poaoTilgang:
    url: http://poao-tilgang.poao
    scope: api://prod-gcp.poao.poao-tilgang/.default

  amtEnhetsregister:
    url: http://amt-enhetsregister.amt
    scope: api://prod-gcp.amt.amt-enhetsregister/.default

  msGraphConfig:
    url: https://graph.microsoft.com
    scope: https://graph.microsoft.com/.default

  arenaAdapter:
    url: http://mulighetsrommet-arena-adapter
    scope: api://prod-gcp.team-mulighetsrommet.mulighetsrommet-arena-adapter/.default

  tasks:
    synchronizeNorgEnheter:
      delayOfMinutes: 360 # Hver 6. time
    synchronizeEnheterFraSanityTilApi:
      delayOfMinutes: 360 # Hver 6. time
    synchronizeTilgjengelighetsstatuser:
      cronPattern: "0 0/30 6-18 * * *" # Hver halvtime fra kl 06:00 til 18:00
    synchronizeNavAnsatte:
      disabled: true
      cronPattern: "0 0 6 * * *" # Hver dag kl 06:00
      groups:
        - 676673aa-ec8f-4606-8399-723dce26b361 # team-mulighetsrommet
        - dde41c4b-42af-401f-bedf-9e537bcbdd37 # 0000-GA-mr-admin-flate_betabruker
    notifySluttdatoForGjennomforingerNarmerSeg:
      disabled: false
      cronPattern: "0 0 6 * * *" # Hver morgen kl. 06.00

  norg2:
    baseUrl: https://norg2.prod-fss-pub.nais.io/norg2/api/v1

  brreg:
    baseUrl: https://data.brreg.no/enhetsregisteret/api

  slack:
    token: ${SLACK_TOKEN}
    channel: "#team-valp-monitoring"
    enable: true
