server:
  port: 8080
  host: 0.0.0.0

app:
  database:
    host: ${DB_HOST}
    port: ${DB_PORT}
    name: ${DB_DATABASE}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  auth:
    azure:
      issuer: ${AZURE_OPENID_CONFIG_ISSUER:-http://localhost:8081/azure}
      jwksUri: ${AZURE_OPENID_CONFIG_JWKS_URI:-http://localhost:8081/azure/jwks}
      audience: ${AZURE_APP_CLIENT_ID:-mulighetsrommet-api}
