server:
  port: 8080
  host: 0.0.0.0

app:
  database:
    jdbcUrl: ${DB_JDBC_URL}
    maximumPoolSize: 10
  flyway:
    strategy: RepairAndMigrate

  migrerteTiltak:
    - ARBEIDSFORBEREDENDE_TRENING
    - ARBEIDSRETTET_REHABILITERING
    - AVKLARING
    - DIGITALT_OPPFOLGINGSTILTAK
    - GRUPPE_ARBEIDSMARKEDSOPPLAERING
    - JOBBKLUBB
    - OPPFOLGING
    - VARIG_TILRETTELAGT_ARBEID_SKJERMET

  pameldingIModia:
    - ARBEIDSFORBEREDENDE_TRENING

  pameldingKommerSnartIModia:
    - ARBEIDSFORBEREDENDE_TRENING

  kafka:
    producerId: mulighetsrommet-api-kafka-producer.v1
    consumerGroupId: mulighetsrommet-api-kafka-consumer.v1
    producers:
      arenaMigreringTiltaksgjennomforinger:
        topic: team-mulighetsrommet.arena-migrering-tiltaksgjennomforinger-v1
      tiltaksgjennomforinger:
        topic: team-mulighetsrommet.siste-tiltaksgjennomforinger-v1
      tiltakstyper:
        topic: team-mulighetsrommet.siste-tiltakstyper-v2
    consumers:
      tiltaksgjennomforingerV1:
        id: siste-tiltaksgjennomforinger
        topic: team-mulighetsrommet.siste-tiltaksgjennomforinger-v1
      amtDeltakerV1:
        id: amt-deltaker
        topic: amt.deltaker-v1
      amtVirksomheterV1:
        id: amt-virksomheter
        topic: amt.virksomheter-v1

  auth:
    azure:
      issuer: ${AZURE_OPENID_CONFIG_ISSUER}
      jwksUri: ${AZURE_OPENID_CONFIG_JWKS_URI}
      audience: ${AZURE_APP_CLIENT_ID}
      tokenEndpointUrl: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
    roles:
      # team-mulighetsrommet
      - adGruppeId: debefa6e-1865-446d-b22b-9579fc735de3
        rolle: TEAM_MULIGHETSROMMET
      # team-mulighetsrommet
      - adGruppeId: debefa6e-1865-446d-b22b-9579fc735de3
        rolle: TILTAKADMINISTRASJON_GENERELL
      # 0000-GA-TILTAK-ANSVARLIG
      - adGruppeId: 2cf8d881-c2da-47b5-b409-fa088440a629
        rolle: TILTAKADMINISTRASJON_GENERELL
      # 0000-GA-TILTAK-tiltaksgjennomforinger_skriv
      - adGruppeId: 33053061-86da-4d6b-9372-33238fabd25f
        rolle: TILTAKSGJENNOMFORINGER_SKRIV
      # 0000-GA-TILTAK-avtaler_skriv
      - adGruppeId: 46ba8787-eb24-4f7b-830f-4c5e9256de65
        rolle: AVTALER_SKRIV
      # 0000-GA-TILTAK-ENDRINGSMELDING
      - adGruppeId: 4e4bfc3e-58c5-4f1c-879b-df1a86016de9
        rolle: TILTAKADMINISTRASJON_ENDRINGSMELDING
      # (GRP) mr-nav_kontaktperson
      - adGruppeId: 0fdd133a-f47f-4b95-9a5e-f3a5ec87a472
        rolle: KONTAKTPERSON
      # 0000-GA-TILTAK-okonomi_beslutter
      - adGruppeId: 6a1f1984-0fe3-4a0e-ac6e-19225b604a52
        rolle: OKONOMI_BESLUTTER
    tokenx:
      issuer: ${TOKEN_X_ISSUER}
      jwksUri: ${TOKEN_X_JWKS_URI}
      audience: ${TOKEN_X_CLIENT_ID}
      tokenEndpointUrl: ${TOKEN_X_WELL_KNOWN_URL}
    maskinporten:
      issuer: ${MASKINPORTEN_ISSUER}
      jwksUri: ${MASKINPORTEN_JWKS_URI}
      audience: ${MASKINPORTEN_CLIENT_ID}
      tokenEndpointUrl: ${MASKINPORTEN_TOKEN_ENDPOINT}

  sanity:
    dataset: ${SANITY_DATASET}
    projectId: ${SANITY_PROJECT_ID}
    token: ${SANITY_AUTH_TOKEN}

  veilarbvedtaksstotteConfig:
    url: https://veilarbvedtaksstotte.prod-fss-pub.nais.io/veilarbvedtaksstotte/api
    scope: api://prod-fss.pto.veilarbvedtaksstotte/.default

  veilarboppfolgingConfig:
    url: http://veilarboppfolging.poao/veilarboppfolging/api
    scope: api://prod-gcp.poao.veilarboppfolging/.default

  veilarbdialogConfig:
    url: http://veilarbdialog.dab/veilarbdialog/api
    scope: api://prod-gcp.dab.veilarbdialog/.default

  amtDeltakerConfig:
    url: http://amt-deltaker.amt
    scope: api://prod-gcp.amt.amt-deltaker/.default

  poaoTilgang:
    url: http://poao-tilgang.poao
    scope: api://prod-gcp.poao.poao-tilgang/.default

  msGraphConfig:
    url: https://graph.microsoft.com
    scope: https://graph.microsoft.com/.default

  arenaAdapter:
    url: http://mulighetsrommet-arena-adapter
    scope: api://prod-gcp.team-mulighetsrommet.mulighetsrommet-arena-adapter/.default

  tiltakshistorikk:
    url: http://tiltakshistorikk
    scope: api://prod-gcp.team-mulighetsrommet.tiltakshistorikk/.default

  axsys:
    url: https://axsys.prod-fss-pub.nais.io
    scope: api://prod-fss.org.axsys/.default

  pdl:
    url: https://pdl-api.prod-fss-pub.nais.io
    scope: api://prod-fss.pdl.pdl-api/.default

  pamOntologi:
    url: http://pam-ontologi.teampam
    scope: api://prod-gcp.teampam.pam-ontologi/.default

  norg2:
    baseUrl: http://norg2.org

  brreg:
    baseUrl: https://data.brreg.no/enhetsregisteret/api

  altinn:
    url: dummy
    apiKey: dummy
    scope: dummy

  tasks:
    synchronizeNorgEnheter:
      delayOfMinutes: 360 # Hver 6. time
    synchronizeNavAnsatte:
      cronPattern: "0 0 6 * * *" # Hver morgen kl. 06:00
    synchronizeUtdanninger:
      cronPattern: "0 0 6 * * *" # Hver morgen kl. 06:00
    notifySluttdatoForGjennomforingerNarmerSeg:
      cronPattern: "0 0 6 * * *" # Hver morgen kl. 06:00
    notifySluttdatoForAvtalerNarmerSeg:
      cronPattern: "0 0 6 * * *" # Hver morgen kl. 06:00
    notifyFailedKafkaEvents:
      maxRetries: 5
      cronPattern: "0 */15 * ? * MON-FRI"
    generateValidationReport:
      bucketName: mulighetsrommet-api-uploads-prod
    updateApentForInnsok:
      disabled: false
      cronPattern: "0 55 23 * * *" # 23.55 hver kveld
    generateRefusjonskrav:
      disabled: true
      cronPattern: "0 0 5 7 * *"

  slack:
    token: ${SLACK_TOKEN}
    channel: "#team-valp-monitoring"
    enable: true

  unleash:
    appName: ${NAIS_APP_NAME}
    url: ${UNLEASH_SERVER_API_URL}
    token: ${UNLEASH_SERVER_API_TOKEN}
    instanceId: ${NAIS_CLIENT_ID}
    environment: production

  utdanning:
    baseurl: https://api.utdanning.no
