server:
  port: 8080
  host: 0.0.0.0

app:
  database:
    host: ${DB_HOST}
    port: ${DB_PORT}
    name: ${DB_DATABASE}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    maximumPoolSize: 10

  auth:
    azure:
      issuer: ${AZURE_OPENID_CONFIG_ISSUER}
      jwksUri: ${AZURE_OPENID_CONFIG_JWKS_URI}
      audience: ${AZURE_APP_CLIENT_ID}
      tokenEndpointUrl: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}

  sanity:
    dataset: ${SANITY_DATASET}
    projectId: ${SANITY_PROJECT_ID}
    authToken: ${SANITY_AUTH_TOKEN}

  sentry:
    dsn: https://658d2a7841654209b04b77e2c179d224@sentry.gc.nav.no/134

  veilarbvedtaksstotteConfig:
    url: https://veilarbvedtaksstotte.prod-fss-pub.nais.io/veilarbvedtaksstotte/api
    scope: api://prod-fss.pto.veilarbvedtaksstotte/.default

  veilarboppfolgingConfig:
    url: https://veilarboppfolging.prod-fss-pub.nais.io/veilarboppfolging/api
    scope: api://prod-fss.pto.veilarboppfolging/.default

  veilarbpersonConfig:
    url: https://veilarbperson.prod-fss-pub.nais.io/veilarbperson/api
    scope: api://prod-fss.pto.veilarbperson/.default

  veilarbveilederConfig:
    url: https://veilarbveileder.prod-fss-pub.nais.io/veilarbveileder/api
    scope: api://prod-fss.pto.veilarbveileder/.default

  veilarbdialogConfig:
    url: https://veilarbdialog.prod-fss-pub.nais.io/veilarbdialog/api
    scope: api://prod-fss.pto.veilarbdialog/.default

  veilarbarenaConfig:
    url: https://veilarbarena.dev-fss-pub.nais.io/veilarbarena/api
    scope: api://prod-fss.pto.veilarbarena/.default

  poaoGcpProxy:
    url: https://poao-gcp-proxy.prod-fss-pub.nais.io
    scope: api://prod-fss.pto.poao-gcp-proxy/.default

  poaoTilgang:
    url: http://poao-tilgang.poao
    scope: api://prod-gcp.poao.poao-tilgang/.default

  amtEnhetsregister:
    url: http://amt-enhetsregister.amt
    scope: api://prod-gcp.amt.amt-enhetsregister/.default

  arenaOrdsProxy:
    url: https://amt-arena-ords-proxy.prod-fss-pub.nais.io/api
    scope: api://prod-fss.amt.amt-arena-ords-proxy/.default
