server:
  port: 8074
  host: 0.0.0.0

app:
  database:
    jdbcUrl: jdbc:postgresql://localhost:5442/mr-tiltaksokonomi?user=valp&password=valp
    maximumPoolSize: 10

  auth:
    azure:
      issuer: http://localhost:8081/azure
      jwksUri: http://localhost:8081/azure/jwks
      audience: mr-tiltaksokonomi
      tokenEndpointUrl: http://localhost:8081/azure/token
