# Dette er en liste over anbefalte Alerts basert på https://doc.nais.io/observability/alerts/recommended_alerts/
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: "mulighetsrommet-alarmer"
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
spec:
  groups:
    - name: API nede
      rules:
        - alert: applikasjon nede
          expr: kube_deployment_status_replicas_available{deployment="mulighetsrommet-api"} == 0
          for: 2m
          annotations:
            consequence: "mulighetsrommet-api er nede i namespace {{ $labels.namespace }}"
            action: "`kubectl describe pod -l app={{ $labels.deployment }} -n {{ $labels.namespace }}` for events, og `kubectl logs -l app={{ $labels.deployment }} -n {{ $labels.namespace }}` for logger"
            summary: |-
              API er nede og vil ikke motta forespørsel.
          labels:
            namespace: team-mulighetsrommet
            severity: critical
    - name: Feilrate
      rules:
        - alert: "høy feilrate i logger for mulighetsrommet-api"
          expr: (100 * sum by (app, namespace) (rate(log_messages_errors{app="mulighetsrommet-api", level=~"Error|Warning"}[3m])) / sum by (app, namespace) (rate(log_messages_errors{app="mulighetsrommet-api", level=~"Error|Warning"}[3m]))) > 10
          for: 3m
          annotations:
            consequence: Konsumenter kan oppleve ustabilitet mot API
            summary: |-
              Vi ser mange feilmeldinger i loggene.
              Det kan resultere i ustabile tjenester hos konsumenter som
              trenger data fra API.
            action: "Sjekk loggene til mulighetsrommet-api  [logs.adeo.no](https://logs.adeo.no/app/discover#/view/a6a558c0-e657-11ec-a21b-2f67f808c51c?_g=(filters:!(),refreshInterval:(pause:!t,value:60000),time:(from:now-15m,to:now))&_a=(columns:!(message,envclass,level,application,pod,cluster),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:ca314120-3e9b-11ea-9aca-19a3af0c6171,key:application,negate:!f,params:!(mulighetsrommet-api,mulighetsrommet-arena-adapter),type:phrases,value:!(mulighetsrommet-api,mulighetsrommet-arena-adapter)),query:(bool:(minimum_should_match:1,should:!((match_phrase:(application:mulighetsrommet-api)),(match_phrase:(application:mulighetsrommet-arena-adapter)))))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'96e648c0-980a-11e9-830a-e17bbd64b4db',key:level,negate:!f,params:!(Error,Warning),type:phrases,value:!(Error,Warning)),query:(bool:(minimum_should_match:1,should:!((match_phrase:(level:Error)),(match_phrase:(level:Warning)))))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'96e648c0-980a-11e9-830a-e17bbd64b4db',key:cluster,negate:!f,params:(query:prod-gcp),type:phrase),query:(match_phrase:(cluster:prod-gcp)))),hideChart:!f,index:'96e648c0-980a-11e9-830a-e17bbd64b4db',interval:auto,query:(language:lucene,query:''),sort:!(!('@timestamp',desc)))) i namespace {{ $labels.log_namespace }}, for å se hvorfor det er så mye feil"
          labels:
            namespace: team-mulighetsrommet
            severity: warning

        - alert: Høy andel HTTP serverfeil (5xx responser)
          expr: (100 * (sum by (app, route) (rate(ktor_http_server_requests_seconds_count{status=~"^5\\d\\d", namespace="team-mulighetsrommet", app="mulighetsrommet-api"}[3m])) / sum by (app, route) (rate(ktor_http_server_requests_seconds_count{namespace="team-mulighetsrommet", app="mulighetsrommet-api", status=~"^5\\d\\d"}[3m])))) > 10
          for: 3m
          annotations:
            consequence: 500-feil fra API
            action: "Sjekk loggene til <https://logs.adeo.no/app/r/s/UBCLx|mulighetsrommet-api> for å se hvorfor '{{ $labels.route }}' returnerer feilkoder"
            summary: |-
              Vi ser mange 500-feil fra API. Vi bør undersøke hvorfor, da det kan tyde på en feil som må rettes opp i.
          labels:
            namespace: team-mulighetsrommet
            severity: warning

        - alert: Høy andel HTTP 404-klientfeil
          # Følgende endepunkt er unntatt fra denne alarmen:
          #  - /api/v1/tiltaksgjennomforinger/{id}: endepunktet blir kalt av Komet for alle endringer på deltakere og vil resultere i mye 404
          #  - /api/v1/tiltaksgjennomforinger/id/{arenaId}: endepunktet blir kalt av Komet for alle endringer på deltakere og vil resultere i mye 404
          #  - /api/v1/tiltaksgjennomforinger/arenadata/{id}: endepunktet blir kalt av Komet for alle endringer på deltakere og vil resultere i mye 404
          expr: (100 * (sum by (app, route) (rate(ktor_http_server_requests_seconds_count{status=~"^404", namespace="team-mulighetsrommet", app="mulighetsrommet-api", route!~'.*(/api/v1/tiltaksgjennomforinger/{id}|/api/v1/tiltaksgjennomforinger/id/{arenaId}|/api/v1/tiltaksgjennomforinger/arenadata/{id})'}[3m])) / sum by (app, route) (rate(ktor_http_server_requests_seconds_count{namespace="team-mulighetsrommet", app="mulighetsrommet-api", status=~"^404"}[3m])))) > 10
          for: 3m
          annotations:
            consequense: API returnerer mange 404-feil
            action: "Sjekk loggene til <https://logs.adeo.no/app/r/s/HeTOE|mulighetsrommet-api> for å se hvorfor '{{ $labels.route }}' returnerer feilkoder"
            summary: |-
              API returnerer mange 404-feil. Dette gjør at konsumenter kan oppleve ustabilitet mot API.
          labels:
            namespace: team-mulighetsrommet
            severity: warning

        - alert: Høy andel HTTP 401-klientfeil
          expr: (100 * (sum by (app, route) (rate(ktor_http_server_requests_seconds_count{status=~"^401", namespace="team-mulighetsrommet", app="mulighetsrommet-api"}[3m])) / sum by (app, route) (rate(ktor_http_server_requests_seconds_count{namespace="team-mulighetsrommet", app="mulighetsrommet-api", status=~"^401"}[3m])))) > 10
          for: 3m
          annotations:
            consequense: API returnerer mange 401-feil
            action: "Sjekk loggene til <https://logs.adeo.no/app/r/s/ohJK9|mulighetsrommet-api> for å se hvorfor '{{ $labels.route }}' returnerer feilkoder"
            summary: |-
              API returnerer mange 401-feil. Dette gjør at konsumenter kan oppleve ustabilitet mot API.
          labels:
            namespace: team-mulighetsrommet
            severity: warning
