kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: mulighetsrommet-api
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
spec:
  image: "{{image}}"
  port: 8080
  ingresses:
    - https://mulighetsrommet-api.intern.dev.nav.no
  replicas:
    min: 1
    max: 2
    scalingStrategy:
      cpu:
        thresholdPercentage: 75
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 1024Mi
  liveness:
    path: /internal/liveness
    initialDelay: 20
  readiness:
    path: /internal/readiness
    initialDelay: 20
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  secureLogs:
    enabled: true
  prometheus:
    enabled: true
    path: /internal/prometheus
  kafka:
    pool: nav-dev
  gcp:
    buckets:
      - name: mulighetsrommet-api-uploads-dev
        cascadingDelete: true
    sqlInstances:
      - name: mulighetsrommet-api-v1
        type: POSTGRES_17
        tier: db-f1-micro
        databases:
          - name: mulighetsrommet-api-db
            envVarPrefix: DB
            users:
              # Ekstra databasebruker for Datastream
              - name: datastream
        diskAutoresize: true
        flags:
          - name: max_connections
            value: "200"
          # Settes for å støtte replication slots i databasen
          - name: cloudsql.logical_decoding
            value: "on"
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        groups:
          # team-mulighetsrommet
          - id: "639e2806-4cc2-484c-a72a-51b4308c52a1"
          # 0000-GA-TILTAK-ANSVARLIG
          - id: "52bb9196-b071-4cc7-9472-be4942d33c4b"
          # 0000-AZ-TILTAK-tiltaksgjennomforinger_skriv
          - id: "279039a0-39fd-4860-afdd-a1a2ccaa6323"
          # 0000-AZ-TILTAK-avtaler_skriv
          - id: "48026f54-6259-4c35-a148-bc4257bcaf03"
          # (GRP) mr-nav_kontaktperson
          - id: "7b1d209a-f6c1-4c6e-84f2-02a1bb4c92ba"
          # 0000-AZ-TILTAK-okonomi_beslutter
          - id: "b00ba197-c90a-4ff9-966e-6c9cf1c882bf"
          # 0000-CA-Tiltaksadministrasjon_saksbehandler-okonomi
          - id: "d776c0f9-9c8a-4299-8d34-aa563925b00b"
          # 0000-CA-Tiltaksadministrasjon_beslutter-tilsagn
          - id: "f2d4a628-c17d-4ae0-b720-0abf9add8c30"
          # 0300-CA-Tiltaksadministrasjon_beslutter-tilsagn
          - id: "059b2db3-e38d-4482-bf2f-21d4a226aa94"
          # 0400-CA-Tiltaksadministrasjon_beslutter-tilsagn
          - id: "3e6fe3c5-58e2-466e-9117-adecb4c1ee74"
          # 5700-CA-Tiltaksadministrasjon_beslutter-tilsagn
          - id: "34902073-90be-4025-9bb0-da6b71b293ff"
          # 0000-CA-Tiltaksadministrasjon_attestant-utbetaling
          - id: "a9fb2838-fd9f-4bbd-aa41-2cabc83b26ac"
          # 0300-CA-Tiltaksadministrasjon_attestant-utbetaling
          - id: "88c9cffb-bb4f-4e9d-9af3-cf66ac11f156"
          # 0400-CA-Tiltaksadministrasjon_attestant-utbetaling
          - id: "e79ba9ba-efd9-456b-8567-dadbe65f8b24"
          # 5700-CA-Tiltaksadministrasjon_attestant-utbetaling
          - id: "f57989e2-410e-45dd-9285-32c3bacc94d4"
        extra:
          - NAVident
          - azp_name
  tokenx:
    enabled: true
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "altinn:authorization/authorize"
        - name: "altinn:accessmanagement/authorizedparties.resourceowner"
  accessPolicy:
    inbound:
      rules:
        - application: arrangor-flate
        - application: mulighetsrommet-arena-adapter
        - application: mulighetsrommet-arena-adapter-manager
        - application: mr-admin-flate
        - application: nav-arbeidsmarkedstiltak
        - application: veilarbpersonflate
          namespace: poao
        - application: amt-tiltak
          namespace: amt
          permissions:
            roles:
              - tiltaksgjennomforing-read
        - application: amt-arena-acl
          namespace: amt
          permissions:
            roles:
              - tiltaksgjennomforing-read
        - application: tiltakspenger-tiltak
          namespace: tpts
          permissions:
            roles:
              - tiltaksgjennomforing-read
    outbound:
      rules:
        - application: pdfgen
        - application: mulighetsrommet-arena-adapter
        - application: tiltakshistorikk
        - application: poao-tilgang
          namespace: poao
        - application: amt-enhetsregister
          namespace: amt
        - application: amt-deltaker
          namespace: amt
        - application: pam-ontologi
          namespace: teampam
        - application: veilarbdialog
          namespace: dab
        - application: veilarbvedtaksstotte
          namespace: obo
        - application: norg2
          namespace: org
        - application: veilarboppfolging
          namespace: poao
        - application: isoppfolgingstilfelle
          namespace: teamsykefravr
        - application: clamav
          namespace: nais-system
      external:
        - host: slack.com
        - host: xegcworx.apicdn.sanity.io
        - host: xegcworx.api.sanity.io
        - host: data.brreg.no
        - host: team-mulighetsrommet-unleash-api.nav.cloud.nais.io
        - host: axsys.dev-fss-pub.nais.io
        - host: pdl-api.dev-fss-pub.nais.io
        - host: api.utdanning.no
        - host: platform.tt02.altinn.no
        - host: test.maskinporten.no
        - host: dokarkiv-q2.dev-fss-pub.nais.io
        - host: sokos-kontoregister-q1.dev-fss-pub.nais.io
  envFrom:
    - secret: mulighetsrommet-api
    - secret: mr-admin-flate-unleash-api-token
