kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: mulighetsrommet-api
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://mulighetsrommet-api.intern.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/readiness
    initialDelay: 20
  liveness:
    path: /internal/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: mulighetsrommet-db
            envVarPrefix: DB
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: poao-openam-proxy
          namespace: pto
          cluster: prod-fss
        - application: mulighetsrommet-arena-adapter
        - application: veilarbpersonflate
          namespace: poao
  envFrom:
    - secret: mulighetsrommet-api-prod
  env:
    - name: VEILARBVEDTAKSSTOTTE_URL
      value: https://veilarbvedtaksstotte.prod-fss-pub.nais.io/veilarbvedtaksstotte/api
    - name: VEILARBVEDTAKSSTOTTE_SCOPE
      value: api://prod-fss.pto.veilarbvedtaksstotte/.default
    - name: VEILARBOPPFOLGING_URL
      value: https://veilarboppfolging.prod-fss-pub.nais.io/veilarboppfolging/api
    - name: VEILARBOPPFOLGING_SCOPE
      value: api://prod-fss.pto.veilarboppfolging/.default
