kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: mulighetsrommet-api
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
  annotations:
    config.linkerd.io/proxy-outbound-connect-timeout: "2s"
spec:
  image: "{{image}}"
  port: 8080
  ingresses:
    - https://mulighetsrommet-api.intern.nav.no
  secureLogs:
    enabled: true
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/readiness
    initialDelay: 20
  liveness:
    path: /internal/liveness
    initialDelay: 20
  replicas:
    min: 2
    max: 4
    scalingStrategy:
      cpu:
        thresholdPercentage: 75
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  gcp:
    buckets:
      - name: mulighetsrommet-api-uploads-prod
        cascadingDelete: true
    sqlInstances:
      - type: POSTGRES_16
        tier: db-custom-1-3840
        pointInTimeRecovery: true
        databases:
          - name: mulighetsrommet-api-db
            envVarPrefix: DB
            users:
            - name: datastream # Ekstra databasebruker for Datastream
        diskAutoresize: true
        flags:
          - name: max_connections
            value: "200"
          - name: cloudsql.logical_decoding # Settes for å støtte replication slots i databasen
            value: "on" # flagget som må settes
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        groups:
          # team-mulighetsrommet
          - id: "debefa6e-1865-446d-b22b-9579fc735de3"
          # 0000-GA-TILTAK-ANSVARLIG
          - id: "2cf8d881-c2da-47b5-b409-fa088440a629"
          # 0000-GA-TILTAK-tiltaksgjennomforinger_skriv
          - id: "33053061-86da-4d6b-9372-33238fabd25f"
          # 0000-GA-TILTAK-avtaler_skriv
          - id: "46ba8787-eb24-4f7b-830f-4c5e9256de65"
          # (GRP) mr-nav_kontaktperson
          - id: "0fdd133a-f47f-4b95-9a5e-f3a5ec87a472"
          # 0000-GA-TILTAK-okonomi_beslutter
          - id: "6a1f1984-0fe3-4a0e-ac6e-19225b604a52"
        extra:
          - NAVident
          - azp_name
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: arrangor-flate
        - application: mulighetsrommet-arena-adapter
        - application: mulighetsrommet-arena-adapter-manager
        - application: mr-admin-flate
        - application: nav-arbeidsmarkedstiltak
        - application: veilarbpersonflate
          namespace: poao
        - application: amt-tiltak
          namespace: amt
          permissions:
            roles:
              - tiltaksgjennomforing-read
        - application: amt-arena-acl
          namespace: amt
          permissions:
            roles:
              - tiltaksgjennomforing-read
        - application: tiltakspenger-tiltak
          namespace: tpts
          permissions:
            roles:
              - tiltaksgjennomforing-read
    outbound:
      rules:
        - application: mulighetsrommet-arena-adapter
        - application: tiltakshistorikk
        - application: poao-tilgang
          namespace: poao
        - application: amt-enhetsregister
          namespace: amt
        - application: amt-deltaker
          namespace: amt
        - application: pam-ontologi
          namespace: teampam
        - application: veilarbdialog
          namespace: dab
        - application: veilarbvedtaksstotte
          namespace: obo
        - application: norg2
          namespace: org
        - application: veilarboppfolging
          namespace: poao
      external:
        - host: slack.com
        - host: data.brreg.no
        - host: team-mulighetsrommet-unleash-api.nav.cloud.nais.io
        - host: axsys.prod-fss-pub.nais.io
        - host: pdl-api.prod-fss-pub.nais.io
        - host: api.utdanning.no
        - host: xegcworx.apicdn.sanity.io
        - host: xegcworx.api.sanity.io
        # Sanity IPs https://www.sanity.io/docs/api-cdn#5fa01dfe1285
        - ipv4: 35.241.31.122
        - ipv4: 35.190.70.79
        - ipv4: 35.186.208.30
        - ipv4: 34.102.229.159
        - ipv4: 34.102.211.197
        - ipv4: 34.102.168.221
        - ipv4: 34.102.220.13
        - ipv4: 34.102.190.179
        - ipv4: 34.102.233.224
        - ipv4: 34.117.95.95
        - ipv4: 34.160.140.40
        - ipv4: 34.111.181.219
        - ipv4: 34.111.150.233
        - ipv4: 34.107.216.191
        - ipv4: 34.102.242.91
        - ipv4: 35.201.85.63
        - ipv4: 35.190.90.94
        - ipv4: 34.117.92.90
        - ipv4: 34.149.250.58
        - ipv4: 34.160.166.218
        - ipv4: 34.160.171.86
        - ipv4: 34.36.58.112
        - ipv4: 34.117.0.159
        - ipv4: 34.117.101.53
        - ipv4: 34.49.170.196
        - ipv4: 34.49.206.188
        - ipv4: 35.201.69.243
        - ipv4: 34.149.200.141
        - ipv4: 34.98.114.57
        - ipv4: 34.36.101.172
        - ipv4: 34.49.15.205
        - ipv4: 34.117.26.18
        - ipv4: 34.95.108.139
        - ipv4: 34.49.19.79
        - ipv4: 34.49.99.193
        - ipv4: 34.110.228.169
  envFrom:
    - secret: mulighetsrommet-api
    - secret: mr-admin-flate-unleash-api-token
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "altinn:authorization/authorize"
        - name: "altinn:accessmanagement/authorizedparties.resourceowner"
  env:
    - name: OTEL_JAVAAGENT_EXCLUDE_CLASSES
      value: "no.nav.mulighetsrommet.api.clients.dialog.*,no.nav.mulighetsrommet.api.services.BrukerService"
