kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: mulighetsrommet-api
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
spec:
  image: "{{image}}"
  port: 8080
  ingresses:
    - https://mulighetsrommet-api.intern.dev.nav.no
  secureLogs:
    enabled: true
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/readiness
    initialDelay: 20
  liveness:
    path: /internal/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 2
    scalingStrategy:
      cpu:
        thresholdPercentage: 75
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  gcp:
    buckets:
      - name: mulighetsrommet-api-uploads-dev
        cascadingDelete: true
    sqlInstances:
      - type: POSTGRES_16
        tier: db-f1-micro
        databases:
          - name: mulighetsrommet-api-db
            envVarPrefix: DB
            users:
              - name: datastream # Ekstra databasebruker for Datastream
        diskAutoresize: true
        flags:
          - name: max_connections
            value: "200"
          - name: cloudsql.logical_decoding # Settes for å støtte replication slots i databasen
            value: "on" # flagget som må settes
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        groups:
          # team-mulighetsrommet
          - id: "639e2806-4cc2-484c-a72a-51b4308c52a1"
          # 0000-GA-TILTAK-ANSVARLIG
          - id: "52bb9196-b071-4cc7-9472-be4942d33c4b"
          # 0000-AZ-TILTAK-tiltaksgjennomforinger_skriv
          - id: "279039a0-39fd-4860-afdd-a1a2ccaa6323"
          # 0000-AZ-TILTAK-avtaler_skriv
          - id: "48026f54-6259-4c35-a148-bc4257bcaf03"
          # (GRP) mr-nav_kontaktperson
          - id: "7b1d209a-f6c1-4c6e-84f2-02a1bb4c92ba"
          # 0000-AZ-TILTAK-okonomi_beslutter
          - id: "b00ba197-c90a-4ff9-966e-6c9cf1c882bf"
        extra:
          - NAVident
          - azp_name
  accessPolicy:
    inbound:
      rules:
        - application: mulighetsrommet-arena-adapter
        - application: mulighetsrommet-arena-adapter-manager
        - application: mr-admin-flate
        - application: nav-arbeidsmarkedstiltak
        - application: veilarbpersonflate
          namespace: poao
        - application: amt-tiltak
          namespace: amt
          permissions:
            roles:
              - tiltaksgjennomforing-read
        - application: amt-arena-acl
          namespace: amt
          permissions:
            roles:
              - tiltaksgjennomforing-read
        - application: tiltakspenger-tiltak
          namespace: tpts
          permissions:
            roles:
              - tiltaksgjennomforing-read
    outbound:
      rules:
        - application: mulighetsrommet-arena-adapter
        - application: tiltakshistorikk
        - application: poao-tilgang
          namespace: poao
        - application: amt-enhetsregister
          namespace: amt
        - application: amt-deltaker
          namespace: amt
        - application: pam-ontologi
          namespace: teampam
        - application: veilarbdialog
          namespace: dab
        - application: norg2
          namespace: org
      external:
        - host: slack.com
        - host: xegcworx.apicdn.sanity.io
        - host: xegcworx.api.sanity.io
        - host: data.brreg.no
        - host: team-mulighetsrommet-unleash-api.nav.cloud.nais.io
        - host: axsys.dev-fss-pub.nais.io
        - host: pdl-api.dev-fss-pub.nais.io
        - host: utdanning.no
  envFrom:
    - secret: mulighetsrommet-api
    - secret: mr-admin-flate-unleash-api-token
