kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: mulighetsrommet-api
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
  annotations:
    config.linkerd.io/proxy-outbound-connect-timeout: "2s"
spec:
  image: "{{image}}"
  port: 8080
  ingresses:
    - https://mulighetsrommet-api.intern.nav.no
  replicas:
    min: 2
    max: 4
    scalingStrategy:
      cpu:
        thresholdPercentage: 75
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      memory: 1024Mi
  liveness:
    path: /internal/liveness
    initialDelay: 20
  readiness:
    path: /internal/readiness
    initialDelay: 20
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  secureLogs:
    enabled: true
  prometheus:
    enabled: true
    path: /internal/prometheus
  kafka:
    pool: nav-prod
  gcp:
    buckets:
      - name: mulighetsrommet-api-uploads-prod
        cascadingDelete: true
    sqlInstances:
      - name: mulighetsrommet-api-v1
        type: POSTGRES_17
        tier: db-custom-1-3840
        pointInTimeRecovery: false
        databases:
          - name: mulighetsrommet-api-db
            envVarPrefix: DB
            users:
              # Ekstra databasebruker for Datastream
              - name: datastream
        diskAutoresize: true
        flags:
          - name: max_connections
            value: "200"
          # Settes for å støtte replication slots i databasen
          - name: cloudsql.logical_decoding
            value: "on"
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        groups:
          # team-mulighetsrommet
          - id: "debefa6e-1865-446d-b22b-9579fc735de3"
          # 0000-GA-TILTAK-ANSVARLIG
          - id: "2cf8d881-c2da-47b5-b409-fa088440a629"
          # 0000-GA-TILTAK-tiltaksgjennomforinger_skriv
          - id: "33053061-86da-4d6b-9372-33238fabd25f"
          # 0000-GA-TILTAK-avtaler_skriv
          - id: "46ba8787-eb24-4f7b-830f-4c5e9256de65"
          # 0000-CA-Tiltaksadministrasjon_kontaktperson
          - id: "0fdd133a-f47f-4b95-9a5e-f3a5ec87a472"
          # 0000-CA-Tiltaksadministrasjon_saksbehandler-økonomi
          - id: "a54fd054-4047-46a6-be7c-f1b69f346be8"
          # 0200-CA-Tiltaksadministrasjon_attestant-utbetaling
          - id: "8eb13232-5a99-4e03-8f43-059dbd368ece"
          # 0200-CA-Tiltaksadministrasjon_beslutter-tilsagn
          - id: "7db540e4-f2a7-4942-ab5f-dc54203a088f"
          # 0300-CA-Tiltaksadministrasjon_attestant-utbetaling
          - id: "af433bab-7bf6-4ed2-81bc-e9675fb763ef"
          # 0300-CA-Tiltaksadministrasjon_beslutter-tilsagn
          - id: "fd2a78f7-934d-4abf-95af-a6ee967cbe5d"
          # 0400-CA-Tiltaksadministrasjon_attestant-utbetaling
          - id: "edc8a889-ffc2-4813-921b-8eea4fe0fd76"
          # 0400-CA-Tiltaksadministrasjon_beslutter-tilsagn
          - id: "77b9322c-9ac7-479a-9403-ead8706b6d66"
          # 0600-CA-Tiltaksadministrasjon_attestant-utbetaling
          - id: "5d5bc9ae-fe49-43dc-8255-cabac857542b"
          # 0600-CA-Tiltaksadministrasjon_beslutter-tilsagn
          - id: "28d01506-93e1-4390-9b8c-7885c876fc10"
          # 0800-CA-Tiltaksadministrasjon_attestant-utbetaling
          - id: "ba86368e-d776-4909-89e5-acb5b7932428"
          # 0800-CA-Tiltaksadministrasjon_beslutter-tilsagn
          - id: "43c8bf56-5c32-41f7-8d79-017d83335dc3"
          # 1000-CA-Tiltaksadministrasjon_attestant-utbetaling
          - id: "c536c283-1407-4043-967a-d4fbf5b44bbf"
          # 1000-CA-Tiltaksadministrasjon_beslutter-tilsagn
          - id: "76ba924c-e029-4e69-a571-e3acc35a4d8b"
          # 1100-CA-Tiltaksadministrasjon_attestant-utbetaling
          - id: "368e20e4-12d4-4026-b852-275f356301be"
          # 1100-CA-Tiltaksadministrasjon_beslutter-tilsagn
          - id: "7bda4d14-01f1-49c0-85f9-c75308188331"
          # 1200-CA-Tiltaksadministrasjon_attestant-utbetaling
          - id: "1d2b9d34-ead6-428d-96de-6e677a77afb0"
          # 1200-CA-Tiltaksadministrasjon_beslutter-tilsagn
          - id: "c9e0307d-355a-47ef-8776-132746ebbb15"
          # 1500-CA-Tiltaksadministrasjon_attestant-utbetaling
          - id: "b9f39ac5-6b6f-47a4-a23a-2218c46ee18d"
          # 1500-CA-Tiltaksadministrasjon_beslutter-tilsagn
          - id: "949db0d2-68ff-413f-87ab-39cd49ec305b"
          # 1800-CA-Tiltaksadministrasjon_attestant-utbetaling
          - id: "7c11c112-f82c-4a4b-86a0-3769335599af"
          # 1800-CA-Tiltaksadministrasjon_beslutter-tilsagn
          - id: "f576ab19-837e-4654-a252-e6ca0b62ba03"
          # 1900-CA-Tiltaksadministrasjon_attestant-utbetaling
          - id: "37706a74-6b78-4719-9f63-11a2f8bfd37c"
          # 1900-CA-Tiltaksadministrasjon_beslutter-tilsagn
          - id: "c2f30e37-c74c-4660-a632-37e8e8e80329"
          # 5700-CA-Tiltaksadministrasjon_attestant-utbetaling
          - id: "92b61aff-7958-4fec-b0c2-604530f45ed5"
          # 5700-CA-Tiltaksadministrasjon_beslutter-tilsagn
          - id: "93b27697-0d6d-4f1f-bf63-2f2134bf2cca"
        extra:
          - NAVident
          - azp_name
  tokenx:
    enabled: true
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "altinn:authorization/authorize"
        - name: "altinn:accessmanagement/authorizedparties.resourceowner"
  accessPolicy:
    inbound:
      rules:
        - application: arrangor-flate
        - application: mulighetsrommet-arena-adapter
          permissions:
            roles:
              - arena-adapter
        - application: mulighetsrommet-arena-adapter-manager
        - application: mr-admin-flate
        - application: nav-arbeidsmarkedstiltak
        - application: veilarbpersonflate
          namespace: poao
        - application: amt-tiltak
          namespace: amt
          permissions:
            roles:
              - tiltaksgjennomforing-read
        - application: amt-arena-acl
          namespace: amt
          permissions:
            roles:
              - tiltaksgjennomforing-read
        - application: tiltakspenger-tiltak
          namespace: tpts
          permissions:
            roles:
              - tiltaksgjennomforing-read
    outbound:
      rules:
        - application: pdfgen
        - application: mulighetsrommet-arena-adapter
        - application: tiltakshistorikk
        - application: poao-tilgang
          namespace: poao
        - application: amt-enhetsregister
          namespace: amt
        - application: amt-deltaker
          namespace: amt
        - application: pam-ontologi
          namespace: teampam
        - application: veilarbdialog
          namespace: dab
        - application: veilarbvedtaksstotte
          namespace: obo
        - application: norg2
          namespace: org
        - application: veilarboppfolging
          namespace: poao
        - application: isoppfolgingstilfelle
          namespace: teamsykefravr
        - application: clamav
          namespace: nais-system
      external:
        - host: slack.com
        - host: xegcworx.apicdn.sanity.io
        - host: xegcworx.api.sanity.io
        - host: data.brreg.no
        - host: team-mulighetsrommet-unleash-api.nav.cloud.nais.io
        - host: pdl-api.prod-fss-pub.nais.io
        - host: api.utdanning.no
        - host: platform.altinn.no
        - host: dokarkiv.prod-fss-pub.nais.io
        - host: sokos-kontoregister.prod-fss-pub.nais.io
        # Sanity IPs https://www.sanity.io/docs/api-cdn#5fa01dfe1285
        - ipv4: 35.241.31.122
        - ipv4: 35.190.70.79
        - ipv4: 35.186.208.30
        - ipv4: 34.102.229.159
        - ipv4: 34.102.211.197
        - ipv4: 34.102.168.221
        - ipv4: 34.102.220.13
        - ipv4: 34.102.190.179
        - ipv4: 34.102.233.224
        - ipv4: 34.117.95.95
        - ipv4: 34.160.140.40
        - ipv4: 34.111.181.219
        - ipv4: 34.111.150.233
        - ipv4: 34.107.216.191
        - ipv4: 34.102.242.91
        - ipv4: 35.201.85.63
        - ipv4: 35.190.90.94
        - ipv4: 34.117.92.90
        - ipv4: 34.149.250.58
        - ipv4: 34.160.166.218
        - ipv4: 34.160.171.86
        - ipv4: 34.36.58.112
        - ipv4: 34.117.0.159
        - ipv4: 34.117.101.53
        - ipv4: 34.49.170.196
        - ipv4: 34.49.206.188
        - ipv4: 35.201.69.243
        - ipv4: 34.149.200.141
        - ipv4: 34.98.114.57
        - ipv4: 34.36.101.172
        - ipv4: 34.49.15.205
        - ipv4: 34.117.26.18
        - ipv4: 34.95.108.139
        - ipv4: 34.49.19.79
        - ipv4: 34.49.99.193
        - ipv4: 34.110.228.169
  envFrom:
    - secret: mulighetsrommet-api
    - secret: mr-admin-flate-unleash-api-token
  env:
    - name: OTEL_JAVAAGENT_EXCLUDE_CLASSES
      value: "no.nav.mulighetsrommet.api.clients.dialog.*,no.nav.mulighetsrommet.api.services.BrukerService"
