kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: mulighetsrommet-api
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://mulighetsrommet-api.intern.nav.no
  secureLogs:
    enabled: true
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/readiness
    initialDelay: 20
  liveness:
    path: /internal/liveness
    initialDelay: 20
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        tier: db-custom-1-3840
        diskAutoresize: true
        pointInTimeRecovery: true
        databases:
          - name: mulighetsrommet-api-db
            envVarPrefix: DB
            users:
              - name: sanity-sync-job
        flags:
          - name: max_connections
            value: "200"
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - NAVident
          - azp_name
  accessPolicy:
    inbound:
      rules:
        - application: mulighetsrommet-arena-adapter
        - application: mulighetsrommet-veileder-flate
        - application: mr-admin-flate
        - application: veilarbpersonflate
          namespace: poao
        - application: amt-tiltak
          namespace: amt
          permissions:
            roles:
              - tiltaksgjennomforing-read
        - application: amt-arena-acl
          namespace: amt
          permissions:
            roles:
              - tiltaksgjennomforing-read
    outbound:
      rules:
        - application: mulighetsrommet-arena-adapter
        - application: poao-tilgang
          namespace: poao
  envFrom:
    - secret: mulighetsrommet-api
