kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: mulighetsrommet-api
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://mulighetsrommet-api.dev.intern.nav.no
  secureLogs:
    enabled: true
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/readiness
    initialDelay: 20
  liveness:
    path: /internal/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: mulighetsrommet-db
            envVarPrefix: DB
            users:
              - name: sanity-sync-job
        flags:
          - name: max_connections
            value: "200"
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
      claims:
        extra:
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: mulighetsrommet-arena-adapter
        - application: veilarbpersonflate
          namespace: poao
    outbound:
      rules:
        - application: poao-tilgang
          namespace: poao
        - application: amt-enhetsregister
          namespace: amt
  envFrom:
    - secret: mulighetsrommet-api
