kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: mulighetsrommet-api
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://mulighetsrommet-api.intern.dev.nav.no
  secureLogs:
    enabled: true
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/readiness
    initialDelay: 20
  liveness:
    path: /internal/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  gcp:
    buckets:
      - name: mulighetsrommet-api-uploads
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: mulighetsrommet-api-db
            envVarPrefix: DB
            users:
              - name: sanity-sync-job
        flags:
          - name: max_connections
            value: "200"
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        groups:
          # team-mulighetsrommet
          - 639e2806-4cc2-484c-a72a-51b4308c52a1
          # 0000-GA-mr-admin-flate_betabruker
          - ee45478c-57a5-4ee6-b28d-b65f8c1733fe
          # (GRP) mr-nav_kontaktperson
          - 7b1d209a-f6c1-4c6e-84f2-02a1bb4c92ba
        extra:
          - NAVident
          - azp_name
  accessPolicy:
    inbound:
      rules:
        - application: mulighetsrommet-arena-adapter
        - application: mulighetsrommet-arena-adapter-manager
        - application: mulighetsrommet-veileder-flate
        - application: mr-admin-flate
        - application: veilarbpersonflate
          namespace: poao
        - application: amt-tiltak
          namespace: amt
          permissions:
            roles:
              - tiltaksgjennomforing-read
        - application: amt-arena-acl
          namespace: amt
          permissions:
            roles:
              - tiltaksgjennomforing-read
        - application: journalforing-frontend-q2
          namespace: isa
          permissions:
            roles:
              - tiltaksgjennomforing-read
        - application: tiltakspenger-tiltak
          namespace: tpts
          permissions:
            roles:
              - tiltaksgjennomforing-read
    outbound:
      rules:
        - application: mulighetsrommet-arena-adapter
        - application: poao-tilgang
          namespace: poao
        - application: amt-enhetsregister
          namespace: amt
      external:
        - host: norg2.dev-fss-pub.nais.io
        - host: slack.com
        - host: xegcworx.apicdn.sanity.io
        - host: xegcworx.api.sanity.io
        - host: data.brreg.no
        - host: team-mulighetsrommet-unleash-api.nav.cloud.nais.io
        - host: axsys.dev-fss-pub.nais.io
  envFrom:
    - secret: mulighetsrommet-api
    - secret: mr-admin-flate-unleash-api-token
