apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: mulighetsrommet-api
  namespace: team-mulighetsrommet
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: team-valp
  secretName: mr-admin-flate-unleash-api-token

  # Specify which environment the API token should be created for.
  # Can be one of: development, or production.
  environment: development
