apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: arena-migrering-tiltaksgjennomforinger-v1
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
spec:
  pool: nav-dev
  config:
    cleanupPolicy: compact
    minimumInSyncReplicas: 2
    partitions: 2
    replication: 3
    retentionHours: 1
    segmentHours: 1
  acl:
    - team: team-mulighetsrommet
      application: mulighetsrommet-api
      access: write
    - team: team-mulighetsrommet
      application: mulighetsrommet-kafka-manager
      access: read
    - team: teamarenanais
      application: arena-tiltakshendelse-q1
      access: read
    - team: teamarenanais
      application: arena-tiltakshendelse-q2
      access: read
    - team: teamarenanais
      application: arena-tiltakshendelse-q4
      access: read
    - team: teamarenanais
      application: arena-tiltakshendelse-u1
      access: read
    - team: teamarenanais
      application: arena-tiltakshendelse-u2
      access: read
    - team: teamarenanais
      application: arena-tiltakshendelse-u3
      access: read
