apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: siste-tiltakstyper-v2
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
spec:
  pool: nav-dev
  config:
    cleanupPolicy: compact
    minimumInSyncReplicas: 2
    partitions: 2
    replication: 3
  acl:
    - team: team-mulighetsrommet
      application: mulighetsrommet-api
      access: readwrite
    - team: team-mulighetsrommet
      application: mulighetsrommet-kafka-manager
      access: read

    # Komet
    - team: amt
      application: amt-deltaker
      access: read
    - team: amt
      application: amt-deltaker-bff
      access: read

    # DVH
    - team: teamoppfolging
      application: teamoppfolging-kafka
      access: read
