apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pdfgen
  namespace: team-mulighetsrommet
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20M"
  labels:
    team: team-mulighetsrommet
spec:
  image: "{{ image }}"
  port: 8080
  replicas:
    min: 1
    max: 2
    scalingStrategy:
      cpu:
        thresholdPercentage: 80
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      memory: 1024Mi
  liveness:
    path: /internal/is_alive
  readiness:
    path: /internal/is_ready
  startup:
    path: /internal/is_alive
    initialDelay: 10
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  prometheus:
    enabled: true
    path: /internal/prometheus
  accessPolicy:
    inbound:
      rules:
        - application: mulighetsrommet-api
