apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pdfgen
  namespace: team-mulighetsrommet
  annotations:
    haproxy.org/backend-config-snippet: |
      option http-buffer-request
      acl body_too_large req.body_size gt 20971520
      http-request deny deny_status 413 if body_too_large
  labels:
    team: team-mulighetsrommet
spec:
  image: "{{ image }}"
  port: 8080
  replicas:
    min: 1
    max: 1
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      memory: 2048Mi
  liveness:
    path: /internal/is_alive
  readiness:
    path: /internal/is_ready
  startup:
    path: /internal/is_alive
    initialDelay: 10
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  prometheus:
    enabled: true
    path: /internal/prometheus
  accessPolicy:
    inbound:
      rules:
        - application: mulighetsrommet-api
