name: Setup backend
description: Steps for setup of the backend modules

runs:
  using: composite
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Set up test environment
      run: docker-compose --profile ci up -d
      shell: bash
