name: Setup backend
description: Steps for setup of the backend modules

runs:
  using: composite
  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Set up test environment
      run: docker compose --profile ci up -d
      shell: bash
