openapi: 3.0.1

info:
  version: 1.0.0
  title: Mulighetsrommet API

paths:
  /internal/ping:
    get:
      tags:
        - internal
      responses:
        200:
          description: API is online and responding
          content:
            text/plain:
              schema:
                type: string
                enum: [ PONG ]

  /api/innsatsgrupper:
    get:
      tags:
        - mulighetsrommet
      operationId: getInnsatsgrupper
      responses:
        200:
          description: Array of innsatsgrupper.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Innsatsgruppe"
  /api/tiltakstyper:
    get:
      tags:
        - mulighetsrommet
      operationId: getTiltakstyper
      responses:
        200:
          description: Array of tiltakstyper.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Tiltakstype"
  /api/tiltakstyper/{tiltakskode}:
    parameters:
      - $ref: "#/components/parameters/Tiltakskode"
    get:
      tags:
        - mulighetsrommet
      operationId: getTiltakstype
      responses:
        200:
          description: the specified tiltakstype.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tiltakstype"
        404:
          description: the specified tiltakstype was not found.
          content:
            text/plain:
              schema:
                type: string
  /api/tiltakstyper/{tiltakskode}/tiltaksgjennomforinger:
    parameters:
      - $ref: "#/components/parameters/Tiltakskode"
    get:
      tags:
        - mulighetsrommet
      operationId: getTiltaksgjennomforingerByTiltakskode
      responses:
        200:
          description: An array of tiltaksgjennomføringer for specified tiltakskode.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Tiltaksgjennomforing"
        404:
          description: the specified tiltakstype was not found.
          content:
            text/plain:
              schema:
                type: string
  /api/tiltaksgjennomforinger:
    get:
      tags:
        - mulighetsrommet
      operationId: getTiltaksgjennomforinger
      responses:
        200:
          description: Array of tiltaksgjennomføringer.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Tiltaksgjennomforing"
  /api/tiltaksgjennomforinger/{id}:
    parameters:
      - $ref: "#/components/parameters/ID"
    get:
      tags:
        - mulighetsrommet
      operationId: getTiltaksgjennomforing
      responses:
        200:
          description: The specified tiltaksgjennomføring.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tiltaksgjennomforing"
        404:
          description: The specified tiltaksgjennomføring was not found.
          content:
            application/json:
              schema:
                type: string

components:
  parameters:
    ID:
      name: id
      in: path
      description: ID
      required: true
      schema:
        type: integer
    Tiltakskode:
      name: tiltakskode
      in: path
      description: Tiltakskode
      required: true
      schema:
        $ref: "#/components/schemas/Tiltakskode"

  schemas:
    Innsatsgruppe:
      type: object
      properties:
        id:
          type: number
        tittel:
          type: string
        beskrivelse:
          type: string
      required:
        - id
        - tittel
        - beskrivelse
    Tiltakstype:
      type: object
      properties:
        id:
          type: integer
        innsatsgruppe:
          type: number
          nullable: true
        sanityId:
          type: number
          nullable: true
        navn:
          type: string
        tiltakskode:
          $ref: "#/components/schemas/Tiltakskode"
        fraDato:
          type: string
          nullable: true
        tilDato:
          type: string
          nullable: true
        createdBy:
          type: string
          nullable: true
        createdAt:
          type: string
          nullable: true
        updatedBy:
          type: string
          nullable: true
        updatedAt:
          type: string
          nullable: true
    Tiltaksgjennomforing:
      type: object
      properties:
        id:
          type: integer
        tittel:
          type: string
        beskrivelse:
          type: string
        tiltakskode:
          $ref: "#/components/schemas/Tiltakskode"
        tiltaksnummer:
          type: string
        fraDato:
          # TODO: Update definition when swagger-ui supports OAS 3.1
          # oneOf:
          #   - type: "null"
          #   - type: string
          #     format: date-time
          type: string
          format: date-time
          nullable: true
        tilDato:
          type: string
          format: date-time
          nullable: true
      required:
        - id
        - tittel
        - beskrivelse
        - tiltakskode
        - tilataksnummer
        - fraDato
        - tilDato
    Tiltakskode:
      type: string
      enum:
        - ABIST
        - ABOPPF
        - ABTBOPPF
        - ABUOPPF
        - AMBF1
        - AMBF2
        - AMBF3
        - AMO
        - AMOB
        - AMOE
        - AMOY
        - ANNUTDANN
        - ARBDOGNSM
        - ARBFORB
        - ARBRDAGSM
        - ARBRRDOGN
        - ARBRRHBAG
        - ARBRRHBSM
        - ARBRRHDAG
        - ARBTREN
        - ASV
        - ATG
        - AVKLARAG
        - AVKLARKV
        - AVKLARSP
        - AVKLARSV
        - AVKLARUS
        - BIA
        - BIO
        - BREVKURS
        - DIGIOPPARB
        - DIVTILT
        - EKSPEBIST
        - ENKELAMO
        - ENKFAGYRKE
        - ETAB
        - FLEKSJOBB
        - FORSAMOENK
        - FORSAMOGRU
        - FORSFAGENK
        - FORSFAGGRU
        - FORSHOYUTD
        - FUNKSJASS
        - GRUFAGYRKE
        - GRUNNSKOLE
        - GRUPPEAMO
        - HOYEREUTD
        - HOYSKOLE
        - INDJOBSTOT
        - INDOPPFAG
        - INDOPPFOLG
        - INDOPPFSP
        - INDOPPRF
        - INKLUTILS
        - INST_S
        - IPSUNG
        - ITGRTILS
        - JOBBBONUS
        - JOBBFOKUS
        - JOBBK
        - JOBBKLUBB
        - JOBBSKAP
        - KAT
        - KURS
        - LONNTIL
        - LONNTILAAP
        - LONNTILL
        - LONNTILS
        - MENTOR
        - MIDLONTIL
        - NETTAMO
        - NETTKURS
        - OPPLT2AAR
        - PRAKSKJERM
        - PRAKSORD
        - PV
        - REAKTUFOR
        - REFINO
        - SPA
        - STATLAERL
        - SUPPEMP
        - SYSSLANG
        - SYSSOFF
        - TIDSUBLONN
        - TILPERBED
        - TILRETTEL
        - TILRTILSK
        - TILSJOBB
        - UFØREPENLØ
        - UTBHLETTPS
        - UTBHPSLD
        - UTBHSAMLI
        - UTDPERMVIK
        - UTDYRK
        - UTVAOONAV
        - UTVOPPFOPL
        - VALS
        - VARLONTIL
        - VASV
        - VATIAROR
        - VIDRSKOLE
        - VIKARBLED
        - VV
        - YHEMMOFF
