openapi: 3.0.1

info:
  version: 1.0.0
  title: Mulighetsrommet API

paths:
  /internal/ping:
    get:
      tags:
        - internal
      responses:
        200:
          description: API is online and responding
          content:
            text/plain:
              schema:
                type: string
                enum: [PONG]

  /api/innsatsgrupper:
    get:
      tags:
        - mulighetsrommet
      operationId: getInnsatsgrupper
      responses:
        200:
          description: Array of innsatsgrupper.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Innsatsgruppe"
  /api/tiltakstyper:
    get:
      tags:
        - mulighetsrommet
      operationId: getTiltakstyper
      parameters:
        - in: query
          name: search
          schema:
            type: string
          description: Search for tiltakstyper
        - in: query
          name: innsatsgrupper
          schema:
            type: array
            items:
              type: number
          description: Innsatsgruppefilter
      responses:
        200:
          description: Array of tiltakstyper.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Tiltakstype"

  /api/tiltakstyper/{id}:
    parameters:
      - $ref: "#/components/parameters/ID"
    get:
      tags:
        - mulighetsrommet
      operationId: getTiltakstype
      responses:
        200:
          description: The specified tiltakstype.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tiltakstype"
        404:
          description: The specified tiltakstype was not found.
          content:
            text/plain:
              schema:
                type: string

  /api/tiltakstyper/{id}/tiltaksgjennomforinger:
    parameters:
      - $ref: "#/components/parameters/ID"
    get:
      tags:
        - mulighetsrommet
      operationId: getTiltaksgjennomforingerByTiltakstype
      responses:
        200:
          description: Tiltaksgjennomføringer for the specified tiltakstype.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Tiltaksgjennomforing"
  /api/tiltaksgjennomforinger:
    get:
      tags:
        - mulighetsrommet
      operationId: getTiltaksgjennomforinger
      responses:
        200:
          description: Array of tiltaksgjennomføringer.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Tiltaksgjennomforing"
  /api/tiltaksgjennomforinger/{id}:
    parameters:
      - $ref: "#/components/parameters/ID"
    get:
      tags:
        - mulighetsrommet
      operationId: getTiltaksgjennomforing
      responses:
        200:
          description: The specified tiltaksgjennomføring.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tiltaksgjennomforing"
        404:
          description: The specified tiltaksgjennomføring was not found.
          content:
            application/json:
              schema:
                type: string

components:
  parameters:
    ID:
      name: id
      in: path
      description: ID
      required: true
      schema:
        type: integer

  schemas:
    Innsatsgruppe:
      type: object
      properties:
        id:
          type: number
        tittel:
          type: string
        beskrivelse:
          type: string
      required:
        - id
        - tittel
        - beskrivelse
    UnsavedTiltakstype:
      type: object
      properties:
        innsatsgruppe:
          type: number
          nullable: true
        tittel:
          type: string
        beskrivelse:
          type: string
        ingress:
          type: string
      required:
        - tittel
        - beskrivelse
        - ingress
    Tiltakstype:
      type: object
      properties:
        id:
          type: integer
        innsatsgruppe:
          type: number
          nullable: true
        tittel:
          type: string
        beskrivelse:
          type: string
        ingress:
          type: string
      required:
        - id
        - tittel
        - beskrivelse
        - ingress
    Tiltaksgjennomforing:
      type: object
      properties:
        id:
          type: integer
        tittel:
          type: string
        beskrivelse:
          type: string
        tiltakstypeId:
          type: integer
        tiltaksnummer:
          type: string
        fraDato:
          # TODO: Update definition when swagger-ui supports OAS 3.1
          # oneOf:
          #   - type: "null"
          #   - type: string
          #     format: date-time
          type: string
          format: date-time
          nullable: true
        tilDato:
          type: string
          format: date-time
          nullable: true
      required:
        - id
        - tittel
        - beskrivelse
        - tiltakstypeId
        - tilataksnummer
        - fraDato
        - tilDato
