openapi: 3.0.1

info:
  version: 1.0.0
  title: Mulighetsrommet API

security:
  - bearerAuth: [ ]

paths:

  /api/v1/bruker:
    parameters:
      - $ref: "#/components/parameters/Fnr"
    get:
      tags:
        - Bruker
      operationId: getBrukerdata
      responses:
        200:
          description: Data about the 'bruker' in the context of 'veileder'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Bruker"
        404:
          description: "Could not find data about 'bruker'"
          content:
            application/json:
              schema:
                type: string

  /api/v1/innsatsgrupper:
    get:
      tags:
        - Innsatsgrupper
      operationId: getInnsatsgrupper
      responses:
        200:
          description: An array of innsatsgrupper
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Innsatsgruppe"

  /api/v1/tiltaksgjennomforinger:
    get:
      tags:
        - Tiltaksgjennomføringer
      operationId: getTiltaksgjennomforinger
      parameters:
        - in: query
          name: search
          schema:
            type: string
          description: Search for tiltaksgjennomføringer
        - in: query
          name: innsatsgrupper
          schema:
            type: array
            items:
              type: number
          description: Innsatsgruppefilter
        - in: query
          name: tiltakstyper
          schema:
            type: array
            items:
              type: number
          description: Tiltakstypefilter
          style: form
          explode: false
      responses:
        200:
          description: Array of tiltaksgjennomføringer.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Tiltaksgjennomforing"

  /api/v1/tiltaksgjennomforinger/{id}:
    parameters:
      - $ref: "#/components/parameters/ID"
    get:
      tags:
        - Tiltaksgjennomføringer
      operationId: getTiltaksgjennomforing
      responses:
        200:
          description: The specified tiltaksgjennomføring.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tiltaksgjennomforing"
        404:
          description: The specified tiltaksgjennomføring was not found.
          content:
            application/json:
              schema:
                type: string

  /api/v1/tiltakstyper:
    get:
      tags:
        - Tiltakstyper
      operationId: getTiltakstyper
      parameters:
        - in: query
          name: search
          schema:
            type: string
          description: Search for tiltakstyper
        - in: query
          name: innsatsgrupper
          schema:
            type: array
            items:
              type: number
          description: Innsatsgruppefilter
          style: form
          explode: false
      responses:
        200:
          description: Array of tiltakstyper.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Tiltakstype"

  /api/v1/tiltakstyper/{tiltakskode}:
    get:
      tags:
        - Tiltakstyper
      operationId: getTiltakstype
      parameters:
        - $ref: "#/components/parameters/Tiltakskode"
      responses:
        200:
          description: the specified tiltakstype.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tiltakstype"
        404:
          description: The specified tiltakstype was not found.
          content:
            text/plain:
              schema:
                type: string

  /api/v1/tiltakstyper/{tiltakskode}/tiltaksgjennomforinger:
    parameters:
      - $ref: "#/components/parameters/Tiltakskode"
    get:
      tags:
        - Tiltakstyper
      operationId: getTiltaksgjennomforingerByTiltakskode
      responses:
        200:
          description: An array of tiltaksgjennomføringer for specified tiltakskode.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Tiltaksgjennomforing"
        404:
          description: the specified tiltakstype was not found.
          content:
            text/plain:
              schema:
                type: string

  /api/v1/sanity:
    get:
      tags:
        - Sanity
      operationId: sanityQuery
      parameters:
        - in: query
          name: query
          schema:
            type: string
          description: Sanity query as a Groq-string. See https://www.sanity.io/docs/groq for more information.
          required: true
        - in: query
          name: fnr
          schema:
            type: string
          description: SSN for the user which will be used to filter based on the users 'oppfølgingsenhet'
      responses:
        200:
          description: Sanity query result
          content:
            application/json:
              schema: { }


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    ID:
      name: id
      in: path
      description: ID
      required: true
      schema:
        type: integer
    Tiltakskode:
      name: tiltakskode
      in: path
      description: Tiltakskode
      required: true
      schema:
        $ref: "#/components/schemas/Tiltakskode"
    Fnr:
      name: fnr
      in: query
      description: Fødselsnummer
      required: true
      schema:
        type: string

  schemas:
    Tiltakstype:
      type: object
      required:
        - id
        - innsatsgruppe
        - navn
        - tiltakskode
      properties:
        id:
          type: integer
        innsatsgruppe:
          type: number
          nullable: true
        navn:
          type: string
        tiltakskode:
          $ref: "#/components/schemas/Tiltakskode"

    Tiltaksgjennomforing:
      type: object
      properties:
        id:
          type: integer
        navn:
          type: string
        tiltakskode:
          $ref: "#/components/schemas/Tiltakskode"
        tiltaksnummer:
          type: integer
        aar:
          type: integer
        tilgjenglighet:
          type: string
          enum:
            - Ledig
            - Venteliste
            - Stengt
      required:
        - id
        - navn
        - tiltakskode
        - tiltaksnummer
        - aar
        - tilgjengelighet

    Tiltakskode:
      type: string
      enum:
        - ABIST
        - ABOPPF
        - ABTBOPPF
        - ABUOPPF
        - AMBF1
        - AMBF2
        - AMBF3
        - AMO
        - AMOB
        - AMOE
        - AMOY
        - ANNUTDANN
        - ARBDOGNSM
        - ARBFORB
        - ARBRDAGSM
        - ARBRRDOGN
        - ARBRRHBAG
        - ARBRRHBSM
        - ARBRRHDAG
        - ARBTREN
        - ASV
        - ATG
        - AVKLARAG
        - AVKLARKV
        - AVKLARSP
        - AVKLARSV
        - AVKLARUS
        - BIA
        - BIO
        - BREVKURS
        - DIGIOPPARB
        - DIVTILT
        - EKSPEBIST
        - ENKELAMO
        - ENKFAGYRKE
        - ETAB
        - FLEKSJOBB
        - FORSAMOENK
        - FORSAMOGRU
        - FORSFAGENK
        - FORSFAGGRU
        - FORSHOYUTD
        - FUNKSJASS
        - GRUFAGYRKE
        - GRUNNSKOLE
        - GRUPPEAMO
        - HOYEREUTD
        - HOYSKOLE
        - INDJOBSTOT
        - INDOPPFAG
        - INDOPPFOLG
        - INDOPPFSP
        - INDOPPRF
        - INKLUTILS
        - INST_S
        - IPSUNG
        - ITGRTILS
        - JOBBBONUS
        - JOBBFOKUS
        - JOBBK
        - JOBBKLUBB
        - JOBBSKAP
        - KAT
        - KURS
        - LONNTIL
        - LONNTILAAP
        - LONNTILL
        - LONNTILS
        - MENTOR
        - MIDLONTIL
        - NETTAMO
        - NETTKURS
        - OPPLT2AAR
        - PRAKSKJERM
        - PRAKSORD
        - PV
        - REAKTUFOR
        - REFINO
        - SPA
        - STATLAERL
        - SUPPEMP
        - SYSSLANG
        - SYSSOFF
        - TIDSUBLONN
        - TILPERBED
        - TILRETTEL
        - TILRTILSK
        - TILSJOBB
        - UFØREPENLØ
        - UTBHLETTPS
        - UTBHPSLD
        - UTBHSAMLI
        - UTDPERMVIK
        - UTDYRK
        - UTVAOONAV
        - UTVOPPFOPL
        - VALS
        - VARLONTIL
        - VASV
        - VATIAROR
        - VIDRSKOLE
        - VIKARBLED
        - VV
        - YHEMMOFF

    Bruker:
      type: object
      properties:
        fnr:
          type: string
        innsatsgruppe:
          $ref: "#/components/schemas/Innsatsgruppe"
        oppfolgingsenhet:
          type: "#/components/schemas/Oppfolgingsenhet"
        fornavn:
          type: string
      required:
        - fnr
        - oppfolgingsenhet

    Innsatsgruppe:
      type: string
      enum:
        - STANDARD_INNSATS
        - SITUASJONSBESTEMT_INNSATS
        - SPESIELT_TILPASSET_INNSATS
        - VARIG_TILPASSET_INNSATS
    Oppfolgingsenhet:
      type: object
      properties:
        navn:
          type: string
        enhetId:
          type: string
      required:
        - navn
        - enhetId
    FrontendEvent:
      type: object
      properties:
        name:
          type: string
        fields:
          type: object
          additionalProperties: true
        tags:
          type: object
          additionalProperties: true
      required:
        - name

  examples:
    Tiltakstype:
      summary: "Tiltakstype eksempel"
      value:
        id: null
        navn: "Ny tiltakstype"
        innsatsgruppe: 1
        tiltakskode: "SPA"
        sanityId: null
        fraDato: "2022-04-06T07:14:19.780"
        tilDato: "2023-04-06T07:14:19.780"
