openapi: 3.0.1

info:
  version: 1.0.0
  title: Mulighetsrommet API

security:
  - bearerAuth: [ ]

paths:
  /api/v1/internal/bruker:
    parameters:
      - $ref: "#/components/parameters/Fnr"
    get:
      tags:
        - Bruker
      operationId: getBrukerdata
      responses:
        200:
          description: Data about the 'bruker' in the context of 'veileder'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Bruker"
        404:
          description: "Could not find data about 'bruker'"
          content:
            application/json:
              schema:
                type: string

  /api/v1/internal/tiltaksgjennomforinger:
    get:
      tags:
        - Tiltaksgjennomforinger
      operationId: getTiltaksgjennomforinger
      parameters:
        - in: query
          name: page
          schema:
            type: number
          description: Page number, default 1
        - in: query
          name: size
          schema:
            type: number
          description: Page size, default 50
      responses:
        200:
          description: Object of paginated tiltaksgjennomføringer.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaginertTiltaksgjennomforing"

  /api/v1/internal/tiltaksgjennomforinger/{id}:
    parameters:
      - $ref: "#/components/parameters/ID"
    get:
      tags:
        - Tiltaksgjennomforinger
      operationId: getTiltaksgjennomforing
      responses:
        200:
          description: The specified tiltaksgjennomføring with data about tiltakstype.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tiltaksgjennomforing"
        404:
          description: "The specified tiltaksgjennomføring was not found."
          content:
            application/json:
              schema:
                type: string

  /api/v1/internal/tiltaksgjennomforinger/tiltakstype/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      - in: query
        name: page
        schema:
          type: number
        description: Page number, default 1
      - in: query
        name: size
        schema:
          type: number
        description: Page size, default 50
    get:
      tags:
        - Tiltaksgjennomforinger
      operationId: getAllByTiltakstype
      responses:
        200:
          description: En liste med tiltaksgjennomføringer basert på id til tiltakstype.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaginertTiltaksgjennomforing"
        404:
          description: "Fant ingen tiltaksgjennomføringer med gitt tiltakstype id."
          content:
            application/json:
              schema:
                type: string

  /api/v1/internal/tiltaksgjennomforinger/enhet/{enhet}:
    parameters:
      - in: path
        name: enhet
        schema:
          type: string
        required: true
      - in: query
        name: page
        schema:
          type: number
        description: Page number, default 1
      - in: query
        name: size
        schema:
          type: number
        description: Page size, default 50
    get:
      tags:
        - Tiltaksgjennomforinger
      operationId: getAllByEnhet
      responses:
        200:
          description: En liste med tiltaksgjennomføringer tilknyttet en enhet
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaginertTiltaksgjennomforing"
        404:
          description: "Fant ingen tiltaksgjennomføringer for enhet"
          content:
            application/json:
              schema:
                type: string
  
  /api/v1/internal/tiltaksgjennomforinger/mine:
    parameters:
      - in: query
        name: page
        schema:
          type: number
        description: Page number, default 1
      - in: query
        name: size
        schema:
          type: number
        description: Page size, default 50
    get:
      tags:
        - Tiltaksgjennomforinger
      operationId: getAnsattsGjennomforinger
      responses:
        200:
          description: En liste med tiltaksgjennomføringer tilknyttet en ansatt
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaginertTiltaksgjennomforing"
        404:
          description: "Fant ingen tiltaksgjennomføringer for den ansatte"
          content:
            application/json:
              schema:
                type: string
    post:
      tags:
        - Tiltaksgjennomforinger
      operationId: lagreTilMinListe
      requestBody:
        description: En id for en tiltaksgjennomføring som skal i listen
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        200:
          description: Lagrer en tiltaksgjennomføring til ansatts liste over gjennomføringer
    delete:
      tags:
        - Tiltaksgjennomforinger
      operationId: fjernFraMinListe
      requestBody:
        description: En id for en tiltaksgjennomføring som skal fjernes fra listen
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        200:
          description: Fjernet en gjennomføring gitt en id for en tiltaksgjennomføring


  /api/v1/internal/tiltaksgjennomforinger/sok:
    get:
      tags:
        - Tiltaksgjennomforinger
      operationId: sokEtterTiltaksgjennomforinger
      parameters:
        - in: query
          name: tiltaksnummer
          schema:
            type: string
          description: Whole or part of tiltaksnummer
      responses:
        200:
          description: List of tiltaksgjennomføringer with tiltakstypedata
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Tiltaksgjennomforing"

  /api/v1/internal/tiltakstyper:
    get:
      tags:
        - Tiltakstyper
      operationId: getTiltakstyper
      parameters:
        - in: query
          name: search
          schema:
            type: string
          description: Search for tiltakstyper
        - in: query
          name: page
          schema:
            type: number
          description: Page number, default 1
        - in: query
          name: size
          schema:
            type: number
          description: Page size, default 50
      responses:
        200:
          description: Object of paginerte tiltakstyper.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaginertTiltakstype"

  /api/v1/internal/tiltakstyper/{id}:
    get:
      tags:
        - Tiltakstyper
      operationId: getTiltakstypeById
      parameters:
        - $ref: "#/components/parameters/ID"
      responses:
        200:
          description: the specified tiltakstype
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tiltakstype"
        404:
          description: "The specified tiltakstype was not found."
          content:
            text/plain:
              schema:
                type: string

  /api/v1/internal/sanity:
    get:
      tags:
        - Sanity
      operationId: sanityQuery
      parameters:
        - in: query
          name: query
          schema:
            type: string
          description: Sanity query as a Groq-string. See https://www.sanity.io/docs/groq for more information.
          required: true
        - in: query
          name: fnr
          schema:
            type: string
          description: SSN for the user which will be used to filter based on the users 'oppfølgingsenhet'
      responses:
        200:
          description: Sanity query result
          content:
            application/json:
              schema: { }

  /api/v1/internal/dialog:
    post:
      tags:
        - dialogen
      operationId: delMedDialogen
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DialogRequest"
      responses:
        200:
          description: Dialog response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DialogResponse"
        409:
          description: "Sending message to Dialogen failed"
          content:
            application/json:
              schema:
                type: string

  /api/v1/internal/bruker/historikk:
    get:
      tags:
        - Historikk
      operationId: hentHistorikkForBruker
      responses:
        200:
          description: Historical data about the user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/HistorikkForBruker"

  /api/v1/internal/ansatt/me:
    get:
      tags:
        - Ansatt
      operationId: hentInfoOmAnsatt
      responses:
        200:
          description: Information about employee
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Ansatt"
        404:
          description: "Could not find data about 'ansatt'"
          content:
            application/json:
              schema:
                type: string

  /logger/event:
    post:
      tags:
        - Internal
      operationId: logFrontendEvent
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FrontendEvent"
      responses:
        201:
          description: "Logged frontend event"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FrontendEvent"
        500:
          description: "Logging to frontend failed"
          content:
            application/json:
              schema:
                type: string

  /api/v1/internal/delMedBruker/{tiltaksnummer}:
    get:
      tags:
        - Del med bruker
      operationId: getDelMedBruker
      parameters:
        - in: query
          name: "fnr"
          schema:
            type: string
          description: "Brukers fnr"
        - in: path
          name: "tiltaksnummer"
          description: "Tiltaksnummer for et tiltak"
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Last entry in database about share with user"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DelMedBruker"
        204:
          description: "No content found"

  /api/v1/internal/delMedBruker:
    post:
      tags:
        - Del med bruker
      operationId: postDelMedBruker
      parameters:
        - in: path
          name: "tiltaksnummer"
          description: "Tiltaksnummer for et tiltak"
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DelMedBruker"
      responses:
        200:
          description: "Stored data from insertion in database"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DelMedBruker"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    ID:
      name: id
      in: path
      description: ID
      required: true
      schema:
        type: string
        format: uuid
    Tiltakskode:
      name: tiltakskode
      in: path
      description: Tiltakskode
      required: true
      schema:
        $ref: "#/components/schemas/Tiltakskode"
    Fnr:
      name: fnr
      in: query
      description: Fødselsnummer
      required: true
      schema:
        type: string

  schemas:
    ManuellStatus:
      type: object
      properties:
        erUnderManuellOppfolging:
          type: boolean
          nullable: true
        krrStatus:
          type: object
          properties:
            kanVarsles:
              type: boolean
              nullable: true
            erReservert:
              type: boolean
              nullable: true

    Pagination:
      type: object
      properties:
        totalCount:
          type: integer
        currentPage:
          type: integer
        pageSize:
          type: integer

    PaginertTiltakstype:
      type: object
      required:
        - pagination
        - data
      properties:
        pagination:
          $ref: "#/components/schemas/Pagination"
        data:
          type: array
          items:
            $ref: "#/components/schemas/Tiltakstype"

    PaginertTiltaksgjennomforing:
      type: object
      required:
        - pagination
        - data
      properties:
        pagination:
          $ref: "#/components/schemas/Pagination"
        data:
          type: array
          items:
            $ref: "#/components/schemas/Tiltaksgjennomforing"

    Tiltakstype:
      type: object
      required:
        - id
        - navn
        - arenaKode
      properties:
        id:
          type: string
          format: uuid
        navn:
          type: string
        arenaKode:
          $ref: "#/components/schemas/Tiltakskode"

    Tiltaksgjennomforing:
      type: object
      properties:
        id:
          type: string
          format: uuid
        tiltakstype:
          $ref: "#/components/schemas/Tiltakstype"
        navn:
          type: string
        tiltaksnummer:
          type: string
        virksomhetsnummer:
          type: string
        startDato:
          type: string
          format: date
        sluttDato:
          type: string
          format: date
        enhet:
          type: string
      required:
        - id
        - tiltakstype
        - navn
        - tiltaksnummer
        - virksomhetsnummer

    Tiltakskode:
      type: string
      enum:
        - ABIST
        - ABOPPF
        - ABTBOPPF
        - ABUOPPF
        - AMBF1
        - AMBF2
        - AMBF3
        - AMO
        - AMOB
        - AMOE
        - AMOY
        - ANNUTDANN
        - ARBDOGNSM
        - ARBFORB
        - ARBRDAGSM
        - ARBRRDOGN
        - ARBRRHBAG
        - ARBRRHBSM
        - ARBRRHDAG
        - ARBTREN
        - ASV
        - ATG
        - AVKLARAG
        - AVKLARKV
        - AVKLARSP
        - AVKLARSV
        - AVKLARUS
        - BIA
        - BIO
        - BREVKURS
        - DIGIOPPARB
        - DIVTILT
        - EKSPEBIST
        - ENKELAMO
        - ENKFAGYRKE
        - ETAB
        - FLEKSJOBB
        - FORSAMOENK
        - FORSAMOGRU
        - FORSFAGENK
        - FORSFAGGRU
        - FORSHOYUTD
        - FUNKSJASS
        - GRUFAGYRKE
        - GRUNNSKOLE
        - GRUPPEAMO
        - HOYEREUTD
        - HOYSKOLE
        - INDJOBSTOT
        - INDOPPFAG
        - INDOPPFOLG
        - INDOPPFSP
        - INDOPPRF
        - INKLUTILS
        - INST_S
        - IPSUNG
        - ITGRTILS
        - JOBBBONUS
        - JOBBFOKUS
        - JOBBK
        - JOBBKLUBB
        - JOBBSKAP
        - KAT
        - KURS
        - LONNTIL
        - LONNTILAAP
        - LONNTILL
        - LONNTILS
        - MENTOR
        - MIDLONTIL
        - NETTAMO
        - NETTKURS
        - OPPLT2AAR
        - PRAKSKJERM
        - PRAKSORD
        - PV
        - REAKTUFOR
        - REFINO
        - SPA
        - STATLAERL
        - SUPPEMP
        - SYSSLANG
        - SYSSOFF
        - TIDSUBLONN
        - TILPERBED
        - TILRETTEL
        - TILRTILSK
        - TILSJOBB
        - UFØREPENLØ
        - UTBHLETTPS
        - UTBHPSLD
        - UTBHSAMLI
        - UTDPERMVIK
        - UTDYRK
        - UTVAOONAV
        - UTVOPPFOPL
        - VALS
        - VARLONTIL
        - VASV
        - VATIAROR
        - VIDRSKOLE
        - VIKARBLED
        - VV
        - YHEMMOFF

    Bruker:
      type: object
      properties:
        fnr:
          type: string
        innsatsgruppe:
          $ref: "#/components/schemas/Innsatsgruppe"
        servicegruppe:
          type: string
        oppfolgingsenhet:
          $ref: "#/components/schemas/Oppfolgingsenhet"
        fornavn:
          type: string
        manuellStatus:
          $ref: "#/components/schemas/ManuellStatus"
      required:
        - fnr
        - oppfolgingsenhet

    Ansatt:
      type: object
      properties:
        etternavn:
          type: string
        fornavn:
          type: string
        ident:
          type: string
        navn:
          type: string
        tilganger:
          type: array
          items:
            type: string
        hovedenhet:
          type: string
        hovedenhetNavn:
          type: string

    Innsatsgruppe:
      type: string
      enum:
        - STANDARD_INNSATS
        - SITUASJONSBESTEMT_INNSATS
        - SPESIELT_TILPASSET_INNSATS
        - VARIG_TILPASSET_INNSATS
    Oppfolgingsenhet:
      type: object
      properties:
        navn:
          type: string
        enhetId:
          type: string
      required:
        - navn
        - enhetId

    FrontendEvent:
      type: object
      properties:
        name:
          type: string
        fields:
          type: object
          additionalProperties: true
        tags:
          type: object
          additionalProperties: true
      required:
        - name

    DialogRequest:
      type: object
      properties:
        overskrift:
          type: string
        tekst:
          type: string
      required:
        - overskrift
        - tekst

    DialogResponse:
      type: object
      properties:
        id:
          type: string
      required:
        - id

    HistorikkForBruker:
      type: object
      properties:
        id:
          type: string
        fnr:
          type: string
        fraDato:
          type: string
          nullable: true
        tilDato:
          type: string
          nullable: true
        status:
          type: string
          enum:
            - VENTER
            - AVSLUTTET
            - DELTAR
            - IKKE_AKTUELL
        tiltaksnavn:
          type: string
          nullable: true
        tiltakstype:
          type: string
        arrangor:
          type: string
          nullable: true
      required:
        - id
        - fnr
        - fraDato
        - tilDato
        - status
        - tiltaksnavn
        - tiltakstype
        - arrangor

    DelMedBruker:
      type: object
      properties:
        id:
          type: string
        bruker_fnr:
          type: string
        navident:
          type: string
        tiltaksnummer:
          type: string
        dialogId:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
        created_by:
          type: string
        updated_by:
          type: string
