apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: tiltaksokonomi-bestilling-v1
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
spec:
  pool: nav-prod
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 2
    partitions: 2
    replication: 3
    # 90 days retention (24 h * 90 d)
    retentionHours: 2160
  acl:
    - team: team-mulighetsrommet
      application: mulighetsrommet-api
      access: readwrite
    - team: team-mulighetsrommet
      application: tiltaksokonomi
      access: read
