apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: mulighetsrommet-veileder-flate
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/poao/poao-frontend:2023.12.11_07.47-3b141178cd58
  port: 8080
  ingresses:
    - https://mulighetsrommet-veileder-flate.intern.dev.nav.no
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    min: 1
    max: 1
    scalingStrategy:
      cpu:
        thresholdPercentage: 75
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  azure:
    application:
      enabled: true
      allowAllUsers: true
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /assets/*
        - /asset-manifest.json
  gcp:
    buckets:
      - name: mulighetsrommet-veilederflate-dev
        cascadingDelete: false
  accessPolicy:
    outbound:
      rules:
        - application: mulighetsrommet-api
  env:
    - name: JSON_CONFIG
      value: >
        {
          "gcs": {
            "bucketName": "mulighetsrommet-veilederflate-dev"
          },
          "auth": {
            "loginProvider": "AZURE_AD"
          },
          "cors": {
            "origin": "https://veilarbpersonflate.intern.dev.nav.no"
          },
          "header": {
            "csp": {
              "imgSrc": ["'self'", "*.nav.no", "cdn.sanity.io"],
              "styleSrc": ["'self'", "*.nav.no"]
            }
          },
          "proxies": [
            {
              "fromPath": "/mulighetsrommet-api",
              "toUrl": "http://mulighetsrommet-api",
              "preserveFromPath": false,
              "toApp": {
                "name": "mulighetsrommet-api",
                "namespace": "team-mulighetsrommet",
                "cluster": "dev-gcp"
              }
            }
          ]
        }
