apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: mulighetsrommet-veileder-flate
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
spec:
  image: ghcr.io/navikt/poao-frontend/poao-frontend:2023.02.20_07.25-25d2fa8d05b8
  port: 8080
  ingresses:
    - https://mulighetsrommet-veileder-flate.dev.intern.nav.no
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  azure:
    application:
      enabled: true
      allowAllUsers: true
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /assets/*
        - /asset-manifest.json
  gcp:
    buckets:
      - name: mulighetsrommet-veilederflate-dev
        cascadingDelete: false
  accessPolicy:
    outbound:
      rules:
        - application: poao-unleash
          namespace: poao
          cluster: dev-gcp
        - application: mulighetsrommet-api
  env:
    - name: JSON_CONFIG
      value: >
        {
          "gcs": {
            "bucketName": "mulighetsrommet-veilederflate-dev"
          },
          "auth": {
            "loginProvider": "AZURE_AD"
          },
          "cors": {
            "origin": "https://veilarbpersonflate.dev.intern.nav.no"
          },
          "proxies": [
            {
              "fromPath": "/veilarbpersonflatefs",
              "toUrl": "http://poao-unleash.poao.svc.cluster.local",
              "preserveFromPath": false,
               "toApp": {
                "name": "poao-unleash",
                "namespace": "poao",
                "cluster": "dev-gcp"
              }
            },
            {
              "fromPath": "/mulighetsrommet-api",
              "toUrl": "http://mulighetsrommet-api",
              "preserveFromPath": false,
              "toApp": {
                "name": "mulighetsrommet-api",
                "namespace": "team-mulighetsrommet",
                "cluster": "dev-gcp"
              }
            }
          ]
        }
