apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: mulighetsrommet-veileder-flate
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
spec:
  image: ghcr.io/navikt/poao-frontend/poao-frontend:2022.10.10_05.52-a9bb795e0ffe
  port: 8080
  ingresses:
    - https://mulighetsrommet-veileder-flate.intern.nav.no
  liveness:
    path: /internal/isalive
    initialDelay: 10
  readiness:
    path: /internal/isready
    initialDelay: 10
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  azure:
    application:
      enabled: true
    sidecar:
      enabled: true
  gcp:
    buckets:
      - name: mulighetsrommet-veilederflate-prod
        cascadingDelete: false
  accessPolicy:
    outbound:
      rules:
        - application: mulighetsrommet-api
  env:
    - name: JSON_CONFIG
      value: >
        {
          "gcs": {
            "bucketName": "mulighetsrommet-veilederflate-prod",
          },
          "auth": {
            "loginProvider": "AZURE_AD"
          },
          "cors": {
            "origin": "https://veilarbpersonflate.intern.nav.no"
          },
          "proxies": [  
            {
              "fromPath": "/mulighetsrommet-api",
              "toUrl": "http://mulighetsrommet-api",
              "preserveFromPath": false,
              "toApp": {
                "name": "mulighetsrommet-api",
                "namespace": "team-mulighetsrommet",
                "cluster": "prod-gcp"
              }
            }
          ]
        }