db:
  host: ${DB_SANITY_SYNC_JOB_HOST}
  port: ${DB_SANITY_SYNC_JOB_PORT}
  name: ${DB_SANITY_SYNC_JOB_DATABASE}
  user: ${DB_SANITY_SYNC_JOB_USERNAME}
  password: ${DB_SANITY_SYNC_JOB_PASSWORD}
  maximumPoolSize: 10
