db:
  host: localhost
  port: 5442
  name: mulighetsrommet-api-db
  user: valp
  password: valp
  maximumPoolSize: 10

sanity:
  projectId: xegcworx
  dataset: test
  apiVersion: 2022-08-01
  token: ${SANITY_AUTH_TOKEN}
