kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-informasjon-api
  namespace: {{namespace}}
  labels:
    team: team-mulighetsrommet
  annotations:
    nais.io/security-does-not-matter: "true"
spec:
  port: 8080
  image: {{image}}-api-{{image_label}}:{{image_tag}}
  {{#if ingresses}}
  ingresses:
    {{#each ingresses}}
    - {{this}}
    {{/each}}
  {{/if}}
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/readiness
    initialDelay: 20
  liveness:
    path: /internal/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: amt-informasjon-api
            envVarPrefix: DB
  azure:
    application:
      enabled: true
