kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: mulighetsrommet-api
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
  annotations:
    nais.io/security-does-not-matter: "true"
spec:
  port: 8080
  image: ghcr.io/navikt/mulighetsrommet/mulighetsrommet-api-{{image_label}}:{{image_tag}}
  ingresses:
    - https://mulighetsrommet-api.dev.intern.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/readiness
    initialDelay: 20
  liveness:
    path: /internal/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: mulighetsrommet-db
            envVarPrefix: DB
  kafka:
    pool: nav-dev
    streams: true
  azure:
    application:
      enabled: true
