server:
  port: 8087
  host: 0.0.0.0

app:
  ords:
    url: ${ARENA_ORDS_URL:-http://localhost:9898}
    clientId: ${ARENA_ORDS_CLIENT_ID:-clientId}
    clientSecret: ${ARENA_ORDS_CLIENT_SECRET:-clientSecret}
