server:
  port: 8070
  host: 0.0.0.0

app:
  database:
    jdbcUrl: jdbc:postgresql://localhost:5442/mr-tiltakshistorikk?user=valp&password=valp
    maximumPoolSize: 10

  auth:
    azure:
      issuer: http://localhost:8081/azure
      jwksUri: http://localhost:8081/azure/jwks
      audience: mr-tiltakshistorikk
      tokenEndpointUrl: http://localhost:8081/azure/token

  kafka:
    brokerUrl: localhost:29092
    consumerGroupId: tiltakshistorikk-kafka-consumer.v1
    consumers:
      amtDeltakerV1:
        id: amt-deltaker
        topic: amt-deltaker-v1
      sisteTiltaksgjennomforingerV1:
        id: siste-tiltaksgjennomforinger
        topic: siste-tiltaksgjennomforinger
