server:
  port: 8080
  host: 0.0.0.0

app:
  database:
    jdbcUrl: ${DB_JDBC_URL}
    maximumPoolSize: 10

  auth:
    azure:
      issuer: ${AZURE_OPENID_CONFIG_ISSUER}
      jwksUri: ${AZURE_OPENID_CONFIG_JWKS_URI}
      audience: ${AZURE_APP_CLIENT_ID}
      tokenEndpointUrl: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}

  kafka:
    consumerGroupId: tiltakshistorikk-kafka-consumer.v1
    consumers:
      amtDeltakerV1:
        id: amt-deltaker
        topic: amt.deltaker-v1
      sisteTiltaksgjennomforingerV1:
        id: siste-tiltaksgjennomforinger
        topic: team-mulighetsrommet.siste-tiltaksgjennomforinger-v1

  clients:
    tiltakDatadeling:
      url: http://tiltak-datadeling.team-tiltak
      scope: api://dev-gcp.team-tiltak.tiltak-datadeling/.default

  arbeidsgiverTiltakCutOffDatoMapping:
    MIDLERTIDIG_LONNSTILSKUDD: 2023-2-1
    VARIG_LONNSTILSKUDD: 2023-2-1
    ARBEIDSTRENING: 2025-1-24
