# Dette er en liste over anbefalte Alerts basert på https://doc.nais.io/observability/alerts/recommended_alerts/
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: mulighetsrommet-alarmer-arena-adapter
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
spec:
  groups:
  - name: Arena-adapter nede
    rules:
    - alert: "applikasjon nede"
      expr: kube_deployment_status_replicas_available{deployment="mulighetsrommet-arena-adapater"} == 0
      for: 2m
      annotations:
        consequence: "mulighetsrommet-arena-adapter er nede i namespace {{ $labels.namespace }}"
        action: "`kubectl describe pod -l app={{ $labels.deployment }} -n {{ $labels.namespace }}` for events, og `kubectl logs -l app={{ $labels.deployment }} -n {{ $labels.namespace }}` for logger"
        summary: |-
          mulighetsrommet-arena-adapter er nede og vil ikke konsumere data eller tilby data til API. Dette bør fikses asap.
      labels:
        namespace: team-mulighetsrommet
        severity: critical
  - name: Feilrate i loggen
    rules:
    - alert: "høy feilrate i logger for mulighetsrommet-arena-adapter"
      expr: (100 * sum by (app, namespace) (rate(log_messages_errors{app="mulighetsrommet-arena-adapter", level=~"Error|Warning"}[3m])) / sum by (app, namespace) (rate(log_messages_errors{app="mulighetsrommet-arena-adapter", level=~"Error|Warning"}[3m]))) > 10
      for: 3m
      annotations:
        consequence: "Det er mye feil i loggene for arena-adapter"
        action: "Sjekk loggene til mulighetsrommet-arena-adapter i namespace {{ $labels.log_namespace }}, for å se hvorfor det er så mye feil"
      labels:
        namespace: team-mulighetsrommet
        severity: warning
    - alert: "Høy andel HTTP serverfeil (5xx)"
      expr: (100 * (sum by (app, route) (rate(ktor_http_server_requests_seconds_count{status=~"^5\\d\\d", namespace="team-mulighetsrommet", app="mulighetsrommet-arena-adapter"}[3m])) / sum by (app, route) (rate(ktor_http_server_requests_seconds_count{namespace="team-mulighetsrommet", app="mulighetsrommet-arena-adapter", status=~"^5\\d\\d"}[3m])))) > 10
      for: 3m
      annotations:
        consequence: "mulighetsrommet-arena-adapter logger mange 5xx feil. Det kan tyde på en bug eller dårlig feilhåndtering i tjenesten."
        action: "Sjekk loggene til mulighetsrommet-arena-adapter for å se hvorfor '{{ $labels.route }}' returnerer feilkoder"
      labels:
        namespace: team-mulighetsrommet
        severity: warning
    - alert: Høy andel HTTP klientfeil (4xx responser)
      # Følgende endepunkt er unntatt fra denne alarmen:
      #  - /api/exchange/{arenaId}: endepunktet blir kalt av transitivt fra Komet for alle endringer på deltakere og vil resultere i mye 404
      expr: (100 * (sum by (app, route) (rate(ktor_http_server_requests_seconds_count{status=~"^4\\d\\d", namespace="team-mulighetsrommet", app="mulighetsrommet-arena-adapter", route!~'.*(/api/exchange/{arenaId})'}[3m])) / sum by (app, route) (rate(ktor_http_server_requests_seconds_count{namespace="team-mulighetsrommet", app="mulighetsrommet-arena-adapter"}[3m])))) > 10
      for: 3m
      annotations:
        consequence: "mulighetsrommet-arena-adapter returnerer mye 4xx feil til konsumenter. Det kan føre til ustabilitet hos klientene og bør sees på."
        action: "Sjekk loggene til mulighetsrommet-arena-adapter for å se hvorfor '{{ $labels.route }}' returnerer feilkoder"
      labels:
        namespace: team-mulighetsrommet
        severity: warning
