kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: mulighetsrommet-arena-adapter
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
spec:
  image: {{image}}
  port: 8084
  ingresses:
    - https://mulighetsrommet-arena-adapter.intern.dev.nav.no
  secureLogs:
    enabled: true
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/readiness
    initialDelay: 20
  liveness:
    path: /internal/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 2
    scalingStrategy:
      cpu:
        thresholdPercentage: 75
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 8192Mi
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: mulighetsrommet-arena-adapter-db
            envVarPrefix: DB
        flags:
          - name: max_connections
            value: "200"
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: 639e2806-4cc2-484c-a72a-51b4308c52a1 # team-mulighetsrommet
        extra:
          - azp_name
  accessPolicy:
    inbound:
      rules:
        - application: mulighetsrommet-arena-adapter-manager
        - application: mulighetsrommet-api
    outbound:
      rules:
        - application: mulighetsrommet-api
        - application: tiltakshistorikk
      external:
        - host: amt-arena-ords-proxy.dev-fss-pub.nais.io
        - host: slack.com

  envFrom:
    - secret: mulighetsrommet-arena-adapter
