kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: mulighetsrommet-arena-adapter
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
spec:
  image: {{image}}
  port: 8084
  ingresses:
    - https://mulighetsrommet-arena-adapter.intern.nav.no
  secureLogs:
    enabled: true
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/readiness
    initialDelay: 20
  liveness:
    path: /internal/liveness
    initialDelay: 20
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 4000m
      memory: 8192Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        tier: db-custom-2-7680
        diskAutoresize: true
        pointInTimeRecovery: true
        databases:
          - name: mulighetsrommet-arena-adapter-db
            envVarPrefix: DB
        flags:
          - name: max_connections
            value: "200"
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: 676673aa-ec8f-4606-8399-723dce26b361 # team-mulighetsrommet
        extra:
          - azp_name
  accessPolicy:
    inbound:
      rules:
        - application: mulighetsrommet-arena-adapter-manager
        - application: mulighetsrommet-api
    outbound:
      rules:
        - application: mulighetsrommet-api

  envFrom:
    - secret: mulighetsrommet-arena-adapter
