kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: mulighetsrommet-arena-adapter
  namespace: team-mulighetsrommet
  labels:
    team: team-mulighetsrommet
spec:
  image: {{image}}
  port: 8084
  ingresses:
    - https://mulighetsrommet-arena-adapter.dev.intern.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/readiness
    initialDelay: 20
  liveness:
    path: /internal/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: mulighetsrommet-arena-adapter-db
            envVarPrefix: DB
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
  env:
    - name: MR_API_URL
      value: https://mulighetsrommet-api.dev.intern.nav.no
    - name: MR_API_SCOPE
      value: api://dev-gcp.team-mulighetsrommet.mulighetsrommet-api/.default
    - name: START_KAFKA_TOPIC_CONSUMPTION
      value: false
    - name: START_FAILED_RECORD_PROCESSOR
      value: true
    - name: MR_KAFKA_TOPIC_TILTAKENDRET
      value: teamarenanais.aapen-arena-tiltakendret-v1-q2
    - name: MR_KAFKA_TOPIC_TILTAKGJENNOMFORINGENDRET
      value: teamarenanais.aapen-arena-tiltakgjennomforingendret-v1-q2
    - name: MR_KAFKA_TOPIC_TILTAKDELTAKERENDRET
      value: teamarenanais.aapen-arena-tiltakdeltakerendret-v1-q2
    - name: MR_KAFKA_TOPIC_SAKENDRET
      value: teamarenanais.aapen-arena-sakendret-v1-q2
