insert into tiltakstype (arena_tiltakskode, tiltakskode, navn)
values ('ABIST', null, 'Arbeid med Bistand (AB)'),
       ('ABOPPF', null, 'Arbeid med bistand A oppfølging'),
       ('ABTBOPPF', null, 'Arbeid med bistand B'),
       ('ABUOPPF', null, 'Arbeid med bistand A utvidet oppfølging'),
       ('AMBF1', null, 'AMB Avklaring (fase 1)'),
       ('AMBF2', null, 'Kvalifisering i arbeidsmarkedsbedrift'),
       ('AMBF3', null, 'Tilrettelagt arbeid i arbeidsmarkedsbedrift'),
       ('AMO', null, 'Arbeidsmarkedsopplæring (AMO)'),
       ('AMOB', null, 'Arbeidsmarkedsopplæring (AMO) i bedrift'),
       ('AMOE', null, 'Arbeidsmarkedsopplæring (AMO) enkeltplass'),
       ('AMOY', null, 'Arbeidsmarkedsopplæring (AMO) yrkeshemmede'),
       ('ANNUTDANN', null, 'Annen utdanning'),
       ('ARBDOGNSM', null, 'Arbeidsrettet rehabilitering (døgn) - sykmeldt arbeidstaker'),
       ('ARBFORB', 'ARBEIDSFORBEREDENDE_TRENING', 'Arbeidsforberedende trening'),
       ('ARBRDAGSM', null, 'Arbeidsrettet rehabilitering (dag) - sykmeldt arbeidstaker'),
       ('ARBRRDOGN', null, 'Arbeidsrettet rehabilitering (døgn)'),
       ('ARBRRHBAG', null, 'Arbeidsrettet rehabilitering'),
       ('ARBRRHBSM', null, 'Arbeidsrettet rehabilitering - sykmeldt arbeidstaker'),
       ('ARBRRHDAG', 'ARBEIDSRETTET_REHABILITERING', 'Arbeidsrettet rehabilitering'),
       ('ARBTREN', 'ARBEIDSTRENING', 'Arbeidstrening'),
       ('ASV', null, 'Arbeidssamvirke (ASV)'),
       ('ATG', null, 'Arbeidstreningsgrupper'),
       ('AVKLARAG', 'AVKLARING', 'Avklaring'),
       ('AVKLARKV', null, 'Avklaring av kortere varighet'),
       ('AVKLARSP', null, 'Avklaring - sykmeldt arbeidstaker'),
       ('AVKLARSV', null, 'Avklaring i skjermet virksomhet'),
       ('AVKLARUS', null, 'Avklaring'),
       ('BIA', null, 'Bedriftsintern attføring'),
       ('BIO', null, 'Bedriftsintern opplæring (BIO)'),
       ('BREVKURS', null, 'Brevkurs'),
       ('DIGIOPPARB', 'DIGITALT_OPPFOLGINGSTILTAK', 'Digitalt jobbsøkerkurs'),
       ('DIVTILT', null, 'Diverse tiltak'),
       ('EKSPEBIST', null, 'Ekspertbistand'),
       ('ENKELAMO', 'ENKELTPLASS_ARBEIDSMARKEDSOPPLAERING', 'Arbeidsmarkedsopplæring (enkeltplass)'),
       ('ENKFAGYRKE', 'ENKELTPLASS_FAG_OG_YRKESOPPLAERING', 'Fag- og yrkesopplæring eller fagskole (enkeltplass)'),
       ('ETAB', null, 'Egenetablering'),
       ('FLEKSJOBB', null, 'Fleksibel jobb - lønnstilskudd av lengre varighet'),
       ('FORSAMOENK', null, 'Forsøk AMO enkeltplass'),
       ('FORSAMOGRU', null, 'Forsøk AMO gruppe'),
       ('FORSFAGENK', null, 'Forsøk fag- og yrkesopplæring enkeltplass'),
       ('FORSFAGGRU', null, 'Forsøk fag- og yrkesopplæring gruppe'),
       ('FORSHOYUTD', null, 'Forsøk høyere utdanning'),
       ('FORSOPPLEV', null, 'Forsøk opplæringstiltak av lengre varighet'),
       ('FUNKSJASS', null, 'Funksjonsassistanse'),
       ('GRUFAGYRKE', 'GRUPPE_FAG_OG_YRKESOPPLAERING', 'Fag- og yrkesopplæring (gruppe)'),
       ('GRUNNSKOLE', null, 'Grunnskole'),
       ('GRUPPEAMO', 'GRUPPE_ARBEIDSMARKEDSOPPLAERING', 'Arbeidsmarkedsopplæring (gruppe)'),
       ('HOYEREUTD', 'HOYERE_UTDANNING', 'Høyere utdanning'),
       ('HOYSKOLE', null, 'Høyskole/Universitet'),
       ('INDJOBSTOT', null, 'IPS (individuell jobbstøtte)'),
       ('INDOPPFAG', 'OPPFOLGING', 'Oppfølging'),
       ('INDOPPFOLG', null, 'Individuelt oppfølgingstiltak'),
       ('INDOPPFSP', null, 'Oppfølging - sykmeldt arbeidstaker'),
       ('INDOPPRF', null, 'Resultatbasert finansiering av formidlingsbistand'),
       ('INKLUTILS', 'INKLUDERINGSTILSKUDD', 'Inkluderingstilskudd'),
       ('INST_S', null, 'Nye plasser institusjonelle tiltak'),
       ('IPSUNG', null, 'IPS Ung'),
       ('ITGRTILS', null, 'Integreringstilskudd'),
       ('JOBBBONUS', null, 'Jobbklubb med bonusordning'),
       ('JOBBFOKUS', null, 'Jobbfokus/Utvidet formidlingsbistand'),
       ('JOBBK', 'JOBBKLUBB', 'Jobbklubb'),
       ('JOBBKLUBB', null, 'Intern jobbklubb'),
       ('JOBBSKAP', null, 'Jobbskapingsprosjekter'),
       ('KAT', null, 'Formidlingstjenester'),
       ('KURS', null, 'Andre kurs'),
       ('LONNTIL', null, 'Tidsbegrenset lønnstilskudd'),
       ('LONNTILAAP', null, 'Arbeidsavklaringspenger som lønnstilskudd'),
       ('LONNTILL', null, 'Lønnstilskudd av lengre varighet'),
       ('LONNTILS', null, 'Lønnstilskudd'),
       ('MENTOR', 'MENTOR', 'Mentor'),
       ('MIDLONTIL', 'MIDLERTIDIG_LONNSTILSKUDD', 'Midlertidig lønnstilskudd'),
       ('NETTAMO', null, 'Nettbasert arbeidsmarkedsopplæring (AMO)'),
       ('NETTKURS', null, 'Nettkurs'),
       ('OPPLT2AAR', null, '2-årig opplæringstiltak'),
       ('PRAKSKJERM', null, 'Arbeidspraksis i skjermet virksomhet'),
       ('PRAKSORD', null, 'Arbeidspraksis i ordinær virksomhet'),
       ('PV', null, 'Produksjonsverksted (PV)'),
       ('REAKTUFOR', null, 'Lønnstilskudd - reaktivisering av uførepensjonister'),
       ('REFINO', null, 'Resultatbasert finansiering av oppfølging'),
       ('SPA', null, 'Spa prosjekter'),
       ('STATLAERL', null, 'Lærlinger i statlige etater'),
       ('SUPPEMP', null, 'Supported Employment'),
       ('SYSSLANG', null, 'Sysselsettingstiltak for langtidsledige'),
       ('SYSSOFF', null, 'Sysselsettingstiltak i offentlig sektor for yrkeshemmede'),
       ('TIDSUBLONN', null, 'Tidsubestemt lønnstilskudd'),
       ('TILPERBED', null, 'Tilretteleggingstilskudd for arbeidssøker'),
       ('TILRETTEL', null, 'Tilrettelegging for arbeidstaker'),
       ('TILRTILSK', null, 'Forebyggings- og tilretteleggingstilskudd IA virksomheter og BHT-honorar'),
       ('TILSJOBB', 'SOMMERJOBB', 'Tilskudd til sommerjobb'),
       ('UFØREPENLØ', null, 'Uførepensjon som lønnstilskudd'),
       ('UTBHLETTPS', null, 'Utredning/behandling lettere psykiske lidelser'),
       ('UTBHPSLD', null, 'Utredning/behandling lettere psykiske og sammensatte lidelser'),
       ('UTBHSAMLI', null, 'Utredning/behandling sammensatte lidelser'),
       ('UTDPERMVIK', null, 'Utdanningspermisjoner'),
       ('UTDYRK', null, 'Utdanning'),
       ('UTVAOONAV', null, 'Arbeid med støtte'),
       ('UTVOPPFOPL', null, 'Utvidet oppfølging i opplæring'),
       ('VALS', null, 'Formidlingstjenester - Ventelønn'),
       ('VARLONTIL', 'VARIG_LONNSTILSKUDD', 'Varig lønnstilskudd'),
       ('VASV', 'VARIG_TILRETTELAGT_ARBEID_SKJERMET', 'Varig tilrettelagt arbeid i skjermet virksomhet'),
       ('VATIAROR', 'VTAO', 'Varig tilrettelagt arbeid i ordinær virksomhet'),
       ('VIDRSKOLE', null, 'Videregående skole'),
       ('VIKARBLED', null, 'Utdanningsvikariater'),
       ('VV', null, 'Varig vernet arbeid (VVA)'),
       ('YHEMMOFF', null, 'Sysselsettingstiltak for yrkeshemmede');
