name: Deploy alerts to NAIS for Mulighetsrommet-api
on:
  push:
    branches:
      - main
    paths:
      - mulighetsrommet-api/alerts-api.yaml
      - .github/workflows/alert-deploy-api.yaml

jobs:
  apply-alerts:
    name: Apply alerts to cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: deploy to dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: mulighetsrommet-api/alerts-api.yaml
      - name: deploy to prod
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: mulighetsrommet-api/alerts-api.yaml
