name: Deploy alerts to NAIS for Mulighetsrommet-arena-adapter
on:
  push:
    branches:
      - main
    paths:
      - mulighetsrommet-arena-adapter/alerts-arena-adapter.yaml
      - .github/workflows/alert-deploy-arena-adapter.yaml

jobs:
  apply-alerts:
    name: Apply alerts to cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: deploy to dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: mulighetsrommet-arena-adapter/alerts-arena-adapter.yaml
      - name: deploy to prod
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: mulighetsrommet-arena-adapter/alerts-arena-adapter.yaml
