name: Build

on: [pull_request]

jobs:
  change-check:
    name: Check changes
    runs-on: ubuntu-latest
    outputs:
      changed-be: ${{ steps.changed-be.outputs.changed }}
      changed-fe: ${{ steps.changed-fe.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - name: Backend
        uses: marceloprado/has-changed-path@v1
        id: changed-be
        with:
          paths: backend
      - name: Frontend
        uses: marceloprado/has-changed-path@v1
        id: changed-fe
        with:
          paths: frontend

  build-be:
    name: Build (backend)
    runs-on: ubuntu-latest
    needs: change-check
    if: needs.change-check.outputs.changed-be == 'true'
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew test build --info
      - name: Publish test report
        uses: ScaCap/action-surefire-report@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: "**/build/test-results/test/TEST-*.xml"

  build-fe:
    name: Build (frontend)
    runs-on: ubuntu-latest
    needs: change-check
    if: needs.change-check.outputs.changed-fe == 'true'
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - name: Install and build
        run: |
          npm ci
          npm run build
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: frontend
          browser: chrome
          headless: true
          wait-on: http://localhost:3000
          start: npm start
          install: false
