name: Build and deploy backend
on:
  push:
    branches: [dev]

env:
  IMAGE_TAG: ${{ github.sha }}
  IMAGE: ghcr.io/navikt/mulighetsrommet
  IMAGE_LABEL: dev
  REACT_APP_BACKEND_API_ROOT: https://mulighetsrommet-flate.dev.intern.nav.no
  CI: true
  TZ: Europe/Amsterdam

jobs:
  change-check:
    name: Check changes
    runs-on: ubuntu-latest
    outputs:
      changed-be: ${{ steps.changed-be.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - name: Backend
        uses: marceloprado/has-changed-path@v1
        id: changed-be
        with:
          paths: backend

  build-backend:
    name: Build (backend)
    runs-on: ubuntu-latest
    needs: change-check
    if: needs.change-check.outputs.changed-be == 'true'
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
          cache: gradle
        # Disable test until we can mock out the koin components initialized at start
        #      - name: Build with Gradle
        # run: ./gradlew test build --info
  #        run: ./gradlew build -x test --info
  #      - name: Publish test report
  #        uses: ScaCap/action-surefire-report@v1
  #        with:
  #          github_token: ${{ secrets.GITHUB_TOKEN }}
  #          report_paths: "**/build/test-results/test/TEST-*.xml"

  build-docker-image-backend:
    name: Build Docker image (backend)
    runs-on: ubuntu-latest
    needs: change-check
    if: needs.change-check.outputs.changed-be == 'true'
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
          cache: gradle
      - name: Build with Gradle
        # Disable test until we can mock out the koin components initialized at start
        # run: ./gradlew test build --info
        run: ./gradlew build -x test --info
      - name: Build and push Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} --password-stdin
          echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${{github.actor}} --password-stdin
          docker build -t ${IMAGE}/mulighetsrommet-api-${IMAGE_LABEL}:${IMAGE_TAG} .
          docker push ${IMAGE}/mulighetsrommet-api-${IMAGE_LABEL}:${IMAGE_TAG}

  deploy-backend:
    name: Deploy Docker image (backend)
    runs-on: ubuntu-latest
    needs: build-docker-image-be
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: backend/.nais/nais.yaml
          VAR: image_tag=${{env.IMAGE_TAG}},image_label=${{env.IMAGE_LABEL}}
      - name: Create release tag
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release/dev@${{ env.IMAGE_TAG }}
          release_name: Release to dev
          prerelease: true
