name: Check OpenAPI Specs

on:
  push:
    paths:
      - .github/workflows/check-openapi-specs.yaml
      - mulighetsrommet-api/src/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CI: true
  TZ: Europe/Amsterdam

jobs:
  check-openapi:
    name: Check OpenAPI Spec Generation
    runs-on:
      labels: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup backend
        uses: ./.github/actions/setup-backend

      - name: Generate OpenAPI Specs
        run: ./gradlew :mulighetsrommet-api:generateOpenApi

      - name: Check for uncommitted changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "::error::OpenAPI specs are not up to date! Please run './gradlew :mulighetsrommet-api:generateOpenApi' locally and commit the changes."
            echo "The following files need to be committed:"
            git status --porcelain
            exit 1
          else
            echo "✅ OpenAPI specs are up to date."
          fi
