name: CI/CD (frontend-common)

on:
  push:
    paths:
      - .github/workflows/cicd-frontend-common.yaml
      - .github/workflows/actions/*
      - package.json
      - pnpm-lock.yaml
      - turbo.json
      - frontend/frontend-common/**
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CI: true
  TZ: Europe/Amsterdam

permissions:
  contents: read
  id-token: write

jobs:
  playwright-version:
    name: Get playwright version
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: frontend/arrangor-flate
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - id: get-version
        run: echo "version=$(cat package.json | jq -r '.devDependencies.playwright' | sed -e 's/^[\^\~]//')" >> "$GITHUB_OUTPUT"

  ci:
    name: CI
    runs-on: ubuntu-latest
    needs: playwright-version
    container:
      image: mcr.microsoft.com/playwright:v${{ needs.playwright-version.outputs.version }}-jammy
    steps:
      - uses: actions/checkout@v4
      - name: Setup frontend
        uses: ./.github/actions/setup-frontend
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Test
        run: npx turbo run test --filter=@mr/frontend-common
