name: Deploy BigQuery Views - template
on:
  workflow_call:
    inputs:
      cluster:
        required: true
        type: string
      project:
        required: true
        type: string

jobs:
  deploy-views:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: nais/deploy/actions/deploy@a7f8690f9b367fcbf5348a0a1e21d44f1aae50eb # v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ inputs.cluster }}
          RESOURCE: iac/bigquery-views/tiltakstyper.yaml,iac/bigquery-views/tiltaksgjennomforing.yaml,iac/bigquery-views/tiltaksgjennomforing_opphav_antall_opprettet.yaml
          VAR: project=${{ inputs.project }}
          PRINT_PAYLOAD: true


