name: Deploy Sanity Studio

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: npm
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npx sanity deploy
        working-directory: sanity
        env: 
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
