name: Deploy BigQuery Views - template
on:
  workflow_call:
    inputs:
      cluster:
        required: true
        type: string
      project:
        required: true
        type: string

jobs:
  deploy-views:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: nais/deploy/actions/deploy@fa754451577294aae42872a69b888b3470478ec1 # v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ inputs.cluster }}
          RESOURCE: iac/bigquery-views/tiltakstyper.yaml,iac/bigquery-views/tiltaksgjennomforing.yaml,iac/bigquery-views/tiltaksgjennomforing_opphav_antall_opprettet.yaml
          VAR: project=${{ inputs.project }}
          PRINT_PAYLOAD: true


