name: Deploy BigQuery Views

on:
  push:
    paths:
      - iac/bigquery-views/**
      - .github/workflows/deploy-bigquery-views.yaml
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        required: true
        default: dev
        options:
          - dev
          - dev_and_prod

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint
        uses: ./.github/actions/lint-yaml
        with:
          path: iac/bigquery-views

  deploy-dev-views:
    needs: [ci]
    if: github.event_name == 'push' && github.ref_name == 'main' || github.event_name == 'workflow_dispatch'
    permissions:
      id-token: write # Needed for `nais/deploy/actions/deploy`
    uses: ./.github/workflows/deploy-views.yaml
    secrets: inherit
    with:
      cluster: dev-gcp
      project: team-mulighetsrommet-dev-a2d7

  deploy-prod-views:
    needs: [ci]
    if: github.event_name == 'push' && github.ref_name == 'main' || github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'dev_and_prod'
    permissions:
      id-token: write # Needed for `nais/deploy/actions/deploy`
    uses: ./.github/workflows/deploy-views.yaml
    secrets: inherit
    with:
      cluster: prod-gcp
      project: team-mulighetsrommet-prod-5492
