name: Deploy BigQuery Views - template
on:
  workflow_call:
    inputs:
      cluster:
        required: true
        type: string
      project:
        required: true
        type: string

jobs:
  deploy-views:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: nais/deploy/actions/deploy@849e900e3cfa7faf7ad1532bb3a3e6499c932199 # v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ inputs.cluster }}
          RESOURCE: iac/bigquery-views/tiltakstyper.yaml,iac/bigquery-views/tiltaksgjennomforing.yaml,iac/bigquery-views/tiltaksgjennomforing_opphav_antall_opprettet.yaml
          VAR: project=${{ inputs.project }}
          PRINT_PAYLOAD: true


