name: Deploy Sanity Studio

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: npm
      - run: npm ci
      - name: Cache Turborepo
        uses: actions/cache@v3
        with:
          path: node_modules/.cache/turbo
          key: turborepo-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turborepo-${{ github.ref_name }}-
            turborepo-
      - run: npx turbo run mulighetsrommet-cms#deploy
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
