name: "Check for newer image versions"

on:
  workflow_dispatch:
  schedule:
    # At the end of every day
    - cron: "0 0 * * *"

jobs:
  digest-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v7.0.1 # Immutable release
        with:
          persist-credentials: false
      - id: digestabot
        uses: navikt/digestabot@v1.2 # Immutable release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          team: team-mulighetsrommet
          branch-for-pr: VALP-BAU/update-digests
      - name: Enable auto-merge for digestabot PR
        if: ${{ steps.digestabot.outputs.pull_request_number != '' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge "${{ steps.digestabot.outputs.pull_request_number }}" --auto --merge
