name: Gradle Dependency Submission

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/gradle-dependency-submission.yaml
      - build.gradle.kts
      - settings.gradle.kts
      - gradle.properties
      - gradle/libs.versions.toml
      - common/**
      - mulighetsrommet-api/**
      - mulighetsrommet-arena-adapter/**

permissions:
  contents: write

jobs:
  dependency-submission:
    name: Submit dependency graph
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v3
