name: Deploy kafka manager to dev
on:
  push:
    paths:
      - "iac/kafka-manager/dev/*.yaml"

jobs:
  deploy-dev:
    name: Deploy kafka manager to dev
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: List resource files
        run: echo "RESOURCE_FILES=$(find iac/kafka-manager/dev -type f | tr '\n' ',' | sed 's/,$/\n/')" >> $GITHUB_ENV
      - name: Deploy kafka manager
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: ${{ env.RESOURCE_FILES }}
          PRINT_PAYLOAD: true