name: Alerts (mr-api)

on:
  merge_queue:
  pull_request:
    paths:
      - .github/workflows/mr-api-alerts.yaml
      - mulighetsrommet-api/.nais/alerts.yaml
  push:
    branches:
      - main
    paths:
      - .github/workflows/mr-api-alerts.yaml
      - mulighetsrommet-api/.nais/alerts.yaml

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint
        uses: ./.github/actions/lint-yaml
        with:
          path: mulighetsrommet-api/.nais/alerts.yaml

  apply-alerts:
    name: Apply alerts to cluster
    runs-on: ubuntu-latest
    needs: [ci]
    if: github.event_name == 'push' && github.ref_name == 'main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: deploy to dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: mulighetsrommet-api/.nais/alerts.yaml
      - name: deploy to prod
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: mulighetsrommet-api/.nais/alerts.yaml
