name: Deploy Pull Request Branch
on:
  pull_request:
    branches:
      - main
env:
  CI: true
  TZ: Europe/Oslo

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup frontend
        uses: ./.github/actions/setup-frontend
      - name: Lint
        run: npx turbo run lint --filter=mr-admin-flate
      - name: Vitest
        run: npx turbo run test:ci --filter=mr-admin-flate

  deploy-pull-request-branch:
    name: Deploy Pull Request Branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup frontend
        uses: ./.github/actions/setup-frontend
      - name: Build
        env:
         VITE_BASE: /pr-${{ github.event.number }}/
        run: npx turbo run build --filter=mr-admin-flate
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.DEPLOY_DEV_GCP_BUCKET_FRONTEND }}
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v0
      - name: Upload files to GCS
        run: gsutil -m rsync -r /home/runner/work/mulighetsrommet/mulighetsrommet/frontend/mr-admin-flate/dist gs://mr-admin-flate-dev/pr-${{ github.event.number }}