name: POAO-frontend (mr-arena-adapter-manager)

on:
  push:
    paths:
      - .github/workflows/mr-arena-adapter-manager-container.yaml
      - frontend/arena-adapter-manager/.nais/**
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        required: true
        default: dev
        options:
          - dev
          - dev_and_prod

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint
        uses: ./.github/actions/lint-yaml
        with:
          path: frontend/arena-adapter-manager/.nais

  deploy-dev:
    runs-on: ubuntu-latest
    needs: [ci]
    if: github.event_name == 'push' && github.ref_name == 'main' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v3
      - name: deploy gcp dev
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: dev-gcp
          RESOURCE: frontend/arena-adapter-manager/.nais/nais-dev.yaml

  deploy-prod:
    runs-on: ubuntu-latest
    needs: [ci, deploy-dev]
    if: github.event_name == 'push' && github.ref_name == 'main' || github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'dev_and_prod'
    steps:
      - uses: actions/checkout@v3
      - name: deploy gcp prod
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: prod-gcp
          RESOURCE: frontend/arena-adapter-manager/.nais/nais-prod.yaml
