name: Labs - CI/CD (mr-admin-flate)

on:
  push:
    paths:
      - .github/workflows/mr-admin-flate-labs.yaml
      - package.json
      - package-lock.json
      - turbo.json
      - frontend/mr-admin-flate/**
  workflow_dispatch:

env:
  CI: true
  TZ: Europe/Amsterdam

jobs:
  build-test-and-deploy-labs:
    name: Build, test and deploy for labs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup frontend
        uses: ./.github/actions/setup-frontend
      - name: Build
        run: npx turbo run build:labs --filter=mr-admin-flate
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: frontend/mr-admin-flate
          browser: chrome
          headed: true
          wait-on: http://localhost:5173
          start: npm start
          install: false
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.DEPLOY_DEV_GCP_BUCKET_FRONTEND }}
        if: github.event_name == 'push' && github.ref_name == 'main' || github.event_name == 'workflow_dispatch'
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v0
        if: github.event_name == 'push' && github.ref_name == 'main' || github.event_name == 'workflow_dispatch'
      - name: Upload files to GCS
        run: gsutil -m rsync -r /home/runner/work/mulighetsrommet/mulighetsrommet/frontend/mr-admin-flate/dist gs://mr-admin-flate-dev
        if: github.event_name == 'push' && github.ref_name == 'main' || github.event_name == 'workflow_dispatch'