name: POAO-frontend (mr-veileder-flate)

on:
  push:
    paths:
      - .github/workflows/mr-veileder-flate-container.yaml
      - frontend/mulighetsrommet-veileder-flate/.nais/**
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        required: true
        default: dev
        options:
          - dev
          - dev_and_prod

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint
        uses: ./.github/actions/lint-yaml
        with:
          path: frontend/mulighetsrommet-veileder-flate/.nais

  deploy-demo:
    runs-on: ubuntu-latest
    needs: [ci]
    if: github.event_name == 'push' && github.ref_name == 'main' || github.event_name == 'workflow_dispatch'
    permissions:
      id-token: write # Needed for `nais/deploy/actions/deploy`
    steps:
      - uses: actions/checkout@v4
      - name: Deploy (demo)
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: frontend/mulighetsrommet-veileder-flate/.nais/nais-demo.yaml

  deploy-modia-dev:
    runs-on: ubuntu-latest
    needs: [ci]
    if: github.event_name == 'push' && github.ref_name == 'main' || github.event_name == 'workflow_dispatch'
    permissions:
      id-token: write # Needed for `nais/deploy/actions/deploy`
    steps:
      - uses: actions/checkout@v4
      - name: Deploy (dev)
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: frontend/mulighetsrommet-veileder-flate/.nais/nais-dev.yaml

  deploy-modia-prod:
    runs-on: ubuntu-latest
    needs: [deploy-modia-dev]
    if: github.event_name == 'push' && github.ref_name == 'main' || github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'dev_and_prod'
    permissions:
      id-token: write # Needed for `nais/deploy/actions/deploy`
    steps:
      - uses: actions/checkout@v4
      - name: Deploy (prod)
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: frontend/mulighetsrommet-veileder-flate/.nais/nais-prod.yaml

  deploy-nav-dev:
    runs-on: ubuntu-latest
    needs: [ci]
    if: github.event_name == 'push' && github.ref_name == 'main' || github.event_name == 'workflow_dispatch'
    permissions:
      id-token: write # Needed for `nais/deploy/actions/deploy`
    steps:
      - uses: actions/checkout@v4
      - name: Deploy (dev)
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: frontend/mulighetsrommet-veileder-flate/.nais/nais.yaml
          VARS: frontend/mulighetsrommet-veileder-flate/.nais/nav-dev.yaml

  deploy-nav-prod:
    runs-on: ubuntu-latest
    needs: [deploy-nav-dev]
    if: github.event_name == 'push' && github.ref_name == 'main' || github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'dev_and_prod'
    permissions:
      id-token: write # Needed for `nais/deploy/actions/deploy`
    steps:
      - uses: actions/checkout@v4
      - name: Deploy (prod)
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: frontend/mulighetsrommet-veileder-flate/.nais/nais.yaml
          VARS: frontend/mulighetsrommet-veileder-flate/.nais/nav-prod.yaml
