name: CI/CD (mr-veileder-flate)

on:
  push:
    paths:
      - .github/workflows/mr-veileder-flate.yaml
      - package.json
      - package-lock.json
      - turbo.json
      - frontend/mulighetsrommet-veileder-flate/**
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        required: true
        default: dev
        options:
          - dev
          - dev_and_prod

env:
  CI: true
  TZ: Europe/Amsterdam

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup frontend
        uses: ./.github/actions/setup-frontend
      - name: Lint
        run: npx turbo run lint --filter=mulighetsrommet-veileder-flate
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: frontend/mulighetsrommet-veileder-flate
          browser: chrome
          headed: true
          wait-on: http://localhost:3000
          start: npm start
          install: false
        env:
          VITE_SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
          VITE_SANITY_DATASET: ${{ secrets.SANITY_DATASET }}

  deploy-dev:
    name: Deploy (dev)
    runs-on: ubuntu-latest
    needs: [ build-and-test ]
    permissions:
      id-token: 'write' # Used to authenticate with Google Cloud
    if: github.event_name == 'push' && github.ref_name == 'main' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v3
      - name: Setup frontend
        uses: ./.github/actions/setup-frontend
      - name: Build
        run: npx turbo run build:preprod --filter=mulighetsrommet-veileder-flate
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/932652929200/locations/global/workloadIdentityPools/github/providers/github-action
          service_account: dev-deploy@team-mulighetsrommet-dev-a2d7.iam.gserviceaccount.com
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
      - name: Upload files to GCS
        run: gsutil -m rsync -r /home/runner/work/mulighetsrommet/mulighetsrommet/frontend/mulighetsrommet-veileder-flate/dist gs://mulighetsrommet-veilederflate-dev

  deploy-prod:
    name: Deploy (prod)
    runs-on: ubuntu-latest
    needs: [ build-and-test, deploy-dev ]
    if: github.event_name == 'push' && github.ref_name == 'main' || github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'dev_and_prod'
    steps:
      - uses: actions/checkout@v3
      - name: Setup frontend
        uses: ./.github/actions/setup-frontend
      - name: Build
        run: npx turbo run build --filter=mulighetsrommet-veileder-flate
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.DEPLOY_PROD_GCP_BUCKET_FRONTEND }}
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v0
      - name: Upload files to GCS
        run: gsutil -m rsync -r /home/runner/work/mulighetsrommet/mulighetsrommet/frontend/mulighetsrommet-veileder-flate/dist gs://mulighetsrommet-veilederflate-prod
