name: CI/CD (mulighetsrommet-veileder-flate)

on:
  push:
    paths:
      - .github/workflows/mulighetsrommet-veileder-flate.yaml
      - package.json
      - package-lock.json
      - turbo.json
      - frontend/**
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        required: true
        default: prod
        options:
          - prod

env:
  IMAGE: ghcr.io/navikt/mulighetsrommet/mulighetsrommet-veileder-flate:${{ github.sha }}
  CI: true
  TZ: Europe/Amsterdam

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup frontend
        uses: ./.github/actions/setup-frontend
      - name: Build
        run: npx turbo run build --filter=mulighetsrommet-veileder-flate
#TODO skru på denne når tc-122 er good
#      - name: Cypress run
#        uses: cypress-io/github-action@v3
#        with:
#          working-directory: frontend/mulighetsrommet-veileder-flate
#          browser: chrome
#          headless: true
#          wait-on: http://localhost:3000
#          start: npm start
#          install: false
      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: C026FHSRFEJ
          status: FAILED
          color: danger
      - name: Build and publish Docker image
        if: github.event_name == 'push' && github.ref_name == 'main' || github.event_name == 'workflow_dispatch'
        working-directory: frontend/mulighetsrommet-veileder-flate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} --password-stdin
          echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${{github.actor}} --password-stdin
          docker build -t ${IMAGE} .
          docker push ${IMAGE}

  deploy-prod:
    name: Deploy (prod)
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_name == 'main' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: frontend/mulighetsrommet-veileder-flate/.nais/nais.yaml
          VAR: image=${{ env.IMAGE }}
          VARS: frontend/mulighetsrommet-veileder-flate/.nais/prod-gcp.yaml
