name: CI/CD (mulighetsrommet-arena-adapter-frontend)

on:
  push:
    paths:
      - .github/workflows/mulighetsrommet-arena-adapter-frontend.yaml
      - package.json
      - package-lock.json
      - turbo.json
      - mulighetsrommet-arena-adapter/src/web/**
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        required: true
        default: dev
        options:
          - dev
          - dev_and_prod

env:
  CI: true
  TZ: Europe/Amsterdam

jobs:
  build-test-and-deploy-dev:
    name: Build, test and deploy for dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup frontend
        uses: ./.github/actions/setup-frontend
      - name: Build
        run: npx turbo run build --filter=arena-adapter-management
      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: C026FHSRFEJ
          status: FAILED
          color: danger
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.DEPLOY_DEV_GCP_BUCKET_FRONTEND }}
        if: github.event_name == 'push' && github.ref_name == 'main' || github.event_name == 'workflow_dispatch'
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v0
        if: github.event_name == 'push' && github.ref_name == 'main' || github.event_name == 'workflow_dispatch'
      - name: Upload files to GCS
        run: gsutil -m rsync -r /home/runner/work/mulighetsrommet/mulighetsrommet/mulighetsrommet-arena-adapter/src/web/dist gs://mulighetsrommet-arena-adapter-frontend-dev
        if: github.event_name == 'push' && github.ref_name == 'main' || github.event_name == 'workflow_dispatch'
