name: POAO-frontend for mulighetsrommet-veileder-flate

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/mulighetsrommet-veileder-flate-container.yaml'
      - 'frontend/mulighetsrommet-veileder-flate/.nais/**'
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        required: true
        default: dev
        options:
          - dev
          - dev_and_prod

concurrency:
  group: mulighetsrommet_frontend_container
  cancel-in-progress: true

env:
  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: deploy gcp dev
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: dev-gcp
          RESOURCE: frontend/mulighetsrommet-veileder-flate/.nais/nais-dev.yaml

  deploy-prod:
    if: github.event_name == 'push' && github.ref_name == 'main' || github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'dev_and_prod'
    runs-on: ubuntu-latest
    needs: [ "deploy-dev" ]
    steps:
      - uses: actions/checkout@v3
      - name: deploy gcp prod
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: prod-gcp
          RESOURCE: frontend/mulighetsrommet-veileder-flate/.nais/nais-prod.yaml
