name: CI/CD (mulighetsrommet-arena-ords-proxy)

on:
  push:
    paths:
      - .github/workflows/mulighetsrommet-arena-ords-proxy.yaml
      - build.gradle.kts
      - settings.gradle.kts
      - mulighetsrommet-arena-ords-proxy/**
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        required: true
        default: dev
        options:
          - dev

env:
  IMAGE: ghcr.io/navikt/mulighetsrommet/mulighetsrommet-arena-ords-proxy:${{ github.sha }}
  CI: true
  TZ: Europe/Amsterdam

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup backend
        uses: ./.github/actions/setup-backend
        working-directory: mulighetsrommet-arena-ords-proxy
        run: ./gradlew build
