name: CI/CD (mulighetsrommet-arena-adapter-manager)

on:
  push:
    paths:
      - .github/workflows/mulighetsrommet-arena-adapter-manager.yaml
      - package.json
      - package-lock.json
      - turbo.json
      - frontend/arena-adapter-manager/**
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        required: true
        default: dev
        options:
          - dev
          - dev_and_prod

env:
  CI: true
  TZ: Europe/Amsterdam

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup frontend
        uses: ./.github/actions/setup-frontend
      - name: Build
        run: npx turbo run build --filter=arena-adapter-manager
      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: C026FHSRFEJ
          status: FAILED
          color: danger
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: frontend/arena-adapter-manager/dist

  deploy-dev:
    name: Deploy to dev
    runs-on: ubuntu-latest
    needs: [ "build" ]
    if: github.event_name == 'push' && github.ref_name == 'main' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.DEPLOY_DEV_GCP_BUCKET_FRONTEND }}
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v0
      - name: Upload files to GCS
        run: gsutil -m rsync -r dist gs://mulighetsrommet-arena-adapter-manager-dev

  deploy-prod:
    name: Deploy to prod
    runs-on: ubuntu-latest
    needs: [ "build", "deploy-dev" ]
    if: github.event_name == 'push' && github.ref_name == 'main' || github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'dev_and_prod'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.DEPLOY_PROD_GCP_BUCKET_FRONTEND }}
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v0
      - name: Upload files to GCS
        run: gsutil -m rsync -r dist gs://mulighetsrommet-arena-adapter-manager-prod

