name: CI/CD (mulighetsrommet-veileder-flate)

on:
  push:
    paths:
      - .github/workflows/mulighetsrommet-veileder-flate.yaml
      - package.json
      - package-lock.json
      - turbo.json
      - frontend/**
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        required: true
        default: dev
        options:
          - dev
          - dev_and_prod

env:
  IMAGE_DEV: ghcr.io/navikt/mulighetsrommet/mulighetsrommet-veileder-flate-dev:${{ github.sha }}
  IMAGE_PROD: ghcr.io/navikt/mulighetsrommet/mulighetsrommet-veileder-flate-prod:${{ github.sha }}
  CI: true
  TZ: Europe/Amsterdam

jobs:
  build-test-and-deploy-dev:
    name: Build, test and deploy for dev
    runs-on: ubuntu-latest
    env:
      VITE_SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
      VITE_SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
      VITE_SANITY_ACCESS_TOKEN: ${{ secrets.SANITY_TEST_DATA_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup frontend
        uses: ./.github/actions/setup-frontend
      - name: Build
        run: npx turbo run build:preprod --filter=mulighetsrommet-veileder-flate
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: frontend/mulighetsrommet-veileder-flate
          browser: chrome
          headed: true
          wait-on: http://localhost:3000
          start: npm start
          install: false
      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: C026FHSRFEJ
          status: FAILED
          color: danger
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.DEPLOY_DEV_GCP_BUCKET_FRONTEND }}
        if: github.event_name == 'push' && github.ref_name == 'main' || github.event_name == 'workflow_dispatch'
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v0
        if: github.event_name == 'push' && github.ref_name == 'main' || github.event_name == 'workflow_dispatch'
      - name: Upload files to GCS
        run: gsutil -m rsync -r /home/runner/work/mulighetsrommet/mulighetsrommet/frontend/mulighetsrommet-veileder-flate/dist gs://mulighetsrommet-veilederflate-dev
        if: github.event_name == 'push' && github.ref_name == 'main' || github.event_name == 'workflow_dispatch'
        

  build-test-and-deploy-prod:
    name: Build, test and deploy for production
    runs-on: ubuntu-latest
    needs: ["build-test-and-deploy-dev"]
    env:
      VITE_SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
      VITE_SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
      VITE_SANITY_ACCESS_TOKEN: ${{ secrets.SANITY_TEST_DATA_AUTH_TOKEN }}
    if: github.event_name == 'push' && github.ref_name == 'main' || github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'dev_and_prod'
    steps:
      - uses: actions/checkout@v3
      - name: Setup frontend
        uses: ./.github/actions/setup-frontend
      - name: Build
        run: npx turbo run build --filter=mulighetsrommet-veileder-flate
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: frontend/mulighetsrommet-veileder-flate
          browser: chrome
          headed: true
          wait-on: http://localhost:3000
          start: npm start
          install: false
      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: C026FHSRFEJ
          status: FAILED
          color: danger
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.DEPLOY_PROD_GCP_BUCKET_FRONTEND }}
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v0
      - name: Upload files to GCS
        run: gsutil -m rsync -r /home/runner/work/mulighetsrommet/mulighetsrommet/frontend/mulighetsrommet-veileder-flate/dist gs://mulighetsrommet-veilederflate-prod
