name: Build and deploy mulighetsrommet-veileder-flate-mock

on:
  push:
    branches:
      - dev
    paths:
      - package.json
      - package-lock.json
      - turbo.json
      - frontend/**
  pull_request:
    paths:
      - package.json
      - package-lock.json
      - turbo.json
      - frontend/**
# TODO: support workflow_dispatch
#  workflow_dispatch:

env:
  IMAGE: ghcr.io/navikt/mulighetsrommet/mulighetsrommet-veileder-flate:${{ github.sha }}
  CI: true
  TZ: Europe/Amsterdam

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup frontend
        uses: ./.github/actions/setup-frontend
      - name: Build
        run: npx turbo run build:mock --filter=mulighetsrommet-veileder-flate
      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          working-directory: frontend/mulighetsrommet-veileder-flate
          browser: chrome
          headless: true
          wait-on: http://localhost:3000
          start: npm start
          install: false
      - name: Build and publish Docker image
        if: github.ref_name == 'dev'
        working-directory: frontend/mulighetsrommet-veileder-flate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} --password-stdin
          echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${{github.actor}} --password-stdin
          docker build -t ${IMAGE} .
          docker push ${IMAGE}

  deploy-labs:
    name: Deploy (labs)
    runs-on: ubuntu-latest
    needs: [build-and-test]
    if: github.ref_name == 'dev'
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: labs-gcp
          RESOURCE: frontend/mulighetsrommet-veileder-flate/.nais/nais.yaml
          VAR: image=${IMAGE}
          VARS: frontend/mulighetsrommet-veileder-flate/.nais/labs-gcp.yaml
