name: Run Cypress
on: pull_request

jobs:
  change-check:
    name: Check changes
    runs-on: ubuntu-latest
    outputs:
      changed-fe: ${{ steps.changed-fe.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - name: Frontend
        uses: marceloprado/has-changed-path@v1
        id: changed-fe
        with:
          paths: frontend

  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: frontend
          browser: chrome
          headless: true
          start: npm start cypress:run
          wait-on: http://localhost:3000
