name: Unleash api-tokens (mr-api)

on:
  push:
    paths:
      - .github/workflows/unleash-apitoken.yaml
      - mulighetsrommet-api/.nais/unleash-apitoken-dev.yaml
      - mulighetsrommet-api/.nais/unleash-apitoken-prod.yaml

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint
        uses: ./.github/actions/lint-yaml
        with:
          path: mulighetsrommet-api/.nais

  apply-apitoken-unleash:
    name: Apply ApiToken for Unleash to cluster
    runs-on: ubuntu-latest
    needs: [ci]
    if: github.event_name == 'push' && github.ref_name == 'main'
    permissions:
      id-token: write # Needed for `nais/deploy/actions/deploy`
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: deploy to dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: mulighetsrommet-api/.nais/unleash-apitoken-dev.yaml
      - name: deploy to prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: mulighetsrommet-api/.nais/unleash-apitoken-prod.yaml
